require 'ffi'
require 'singleton'

class ModelShim

  # WARNING: this is not thread safe
  def initialize
    reset
  end

  def reset
    Model.reset
  end

  def method_missing(name, *arguments)
    if arguments.size == 0
      get(name)
    elsif arguments.size == 1
      set(name, arguments.first)
    else
      super
    end 
  end

  def get(name)
    return 0 unless Model.respond_to?(name)
    ruby_value_from_excel_value(Model.send(name))
  end

  def ruby_value_from_excel_value(excel_value)
    case excel_value[:type]
    when :ExcelNumber; excel_value[:number]
    when :ExcelString; excel_value[:string].read_string.force_encoding("utf-8")
    when :ExcelBoolean; excel_value[:number] == 1
    when :ExcelEmpty; nil
    when :ExcelRange
      r = excel_value[:rows]
      c = excel_value[:columns]
      p = excel_value[:array]
      s = Model::ExcelValue.size
      a = Array.new(r) { Array.new(c) }
      (0...r).each do |row|
        (0...c).each do |column|
          a[row][column] = ruby_value_from_excel_value(Model::ExcelValue.new(p + (((row*c)+column)*s)))
        end
      end 
      return a
    when :ExcelError; [:value,:name,:div0,:ref,:na][excel_value[:number]]
    else
      raise Exception.new("ExcelValue type #{excel_value[:type].inspect} not recognised")
    end
  end

  def set(name, ruby_value)
    name = name.to_s
    name = "set_#{name[0..-2]}" if name.end_with?('=')
    return false unless Model.respond_to?(name)
    Model.send(name, excel_value_from_ruby_value(ruby_value))
  end

  def excel_value_from_ruby_value(ruby_value, excel_value = Model::ExcelValue.new)
    case ruby_value
    when Numeric
      excel_value[:type] = :ExcelNumber
      excel_value[:number] = ruby_value
    when String
      excel_value[:type] = :ExcelString
      excel_value[:string] = FFI::MemoryPointer.from_string(ruby_value.encode('utf-8'))
    when TrueClass, FalseClass
      excel_value[:type] = :ExcelBoolean
      excel_value[:number] = ruby_value ? 1 : 0
    when nil
      excel_value[:type] = :ExcelEmpty
    when Array
      excel_value[:type] = :ExcelRange
      # Presumed to be a row unless specified otherwise
      if ruby_value.first.is_a?(Array)
        excel_value[:rows] = ruby_value.size
        excel_value[:columns] = ruby_value.first.size
      else
        excel_value[:rows] = 1
        excel_value[:columns] = ruby_value.size
      end
      ruby_values = ruby_value.flatten
      pointer = FFI::MemoryPointer.new(Model::ExcelValue, ruby_values.size)
      excel_value[:array] = pointer
      ruby_values.each.with_index do |v,i|
        excel_value_from_ruby_value(v, Model::ExcelValue.new(pointer[i]))
      end
    when Symbol
      excel_value[:type] = :ExcelError
      excel_value[:number] = [:value, :name, :div0, :ref, :na].index(ruby_value)
    else
      raise Exception.new("Ruby value #{ruby_value.inspect} not translatable into excel")
    end
    excel_value
  end

end
    

module Model
  extend FFI::Library
  ffi_lib  File.join(File.dirname(__FILE__),FFI.map_library_name('model'))
  ExcelType = enum :ExcelEmpty, :ExcelNumber, :ExcelString, :ExcelBoolean, :ExcelError, :ExcelRange
                
  class ExcelValue < FFI::Struct
    layout :type, ExcelType,
  	       :number, :double,
  	       :string, :pointer,
         	 :array, :pointer,
           :rows, :int,
           :columns, :int             
  end
  

  # use this function to reset all cell values
  attach_function 'reset', [], :void

  # start of Model
  attach_function 'set_model_c22', [ExcelValue.by_value], :void
  attach_function 'set_model_c46', [ExcelValue.by_value], :void
  attach_function 'set_model_c31', [ExcelValue.by_value], :void
  attach_function 'set_model_c59', [ExcelValue.by_value], :void
  attach_function 'set_model_c62', [ExcelValue.by_value], :void
  attach_function 'set_model_c60', [ExcelValue.by_value], :void
  attach_function 'set_model_c63', [ExcelValue.by_value], :void
  attach_function 'set_model_c24', [ExcelValue.by_value], :void
  attach_function 'set_model_c47', [ExcelValue.by_value], :void
  attach_function 'set_model_c26', [ExcelValue.by_value], :void
  attach_function 'set_model_c25', [ExcelValue.by_value], :void
  attach_function 'set_model_c50', [ExcelValue.by_value], :void
  attach_function 'set_model_c52', [ExcelValue.by_value], :void
  attach_function 'set_model_c57', [ExcelValue.by_value], :void
  attach_function 'set_model_c55', [ExcelValue.by_value], :void
  attach_function 'set_model_c56', [ExcelValue.by_value], :void
  attach_function 'set_model_c43', [ExcelValue.by_value], :void
  attach_function 'set_model_c42', [ExcelValue.by_value], :void
  attach_function 'set_model_c41', [ExcelValue.by_value], :void
  attach_function 'set_model_c29', [ExcelValue.by_value], :void
  attach_function 'set_model_c34', [ExcelValue.by_value], :void
  attach_function 'set_model_p31', [ExcelValue.by_value], :void
  attach_function 'set_model_p32', [ExcelValue.by_value], :void
  attach_function 'set_model_p33', [ExcelValue.by_value], :void
  attach_function 'set_model_p34', [ExcelValue.by_value], :void
  attach_function 'set_model_c39', [ExcelValue.by_value], :void
  attach_function 'set_model_c38', [ExcelValue.by_value], :void
  attach_function 'set_model_c37', [ExcelValue.by_value], :void
  attach_function 'set_model_c30', [ExcelValue.by_value], :void
  attach_function 'set_model_c35', [ExcelValue.by_value], :void
  attach_function 'set_model_c23', [ExcelValue.by_value], :void
  attach_function 'set_model_c33', [ExcelValue.by_value], :void
  attach_function 'set_model_c51', [ExcelValue.by_value], :void
  attach_function 'model_c22', [], ExcelValue.by_value
  attach_function 'model_c46', [], ExcelValue.by_value
  attach_function 'model_c31', [], ExcelValue.by_value
  attach_function 'model_p24', [], ExcelValue.by_value
  attach_function 'model_p25', [], ExcelValue.by_value
  attach_function 'model_p23', [], ExcelValue.by_value
  attach_function 'model_c59', [], ExcelValue.by_value
  attach_function 'model_c62', [], ExcelValue.by_value
  attach_function 'model_p28', [], ExcelValue.by_value
  attach_function 'model_c60', [], ExcelValue.by_value
  attach_function 'model_c63', [], ExcelValue.by_value
  attach_function 'model_c24', [], ExcelValue.by_value
  attach_function 'model_p37', [], ExcelValue.by_value
  attach_function 'model_p38', [], ExcelValue.by_value
  attach_function 'model_p39', [], ExcelValue.by_value
  attach_function 'model_c47', [], ExcelValue.by_value
  attach_function 'model_c26', [], ExcelValue.by_value
  attach_function 'model_c25', [], ExcelValue.by_value
  attach_function 'model_c50', [], ExcelValue.by_value
  attach_function 'model_c52', [], ExcelValue.by_value
  attach_function 'model_c57', [], ExcelValue.by_value
  attach_function 'model_c55', [], ExcelValue.by_value
  attach_function 'model_c56', [], ExcelValue.by_value
  attach_function 'model_c43', [], ExcelValue.by_value
  attach_function 'model_c42', [], ExcelValue.by_value
  attach_function 'model_c41', [], ExcelValue.by_value
  attach_function 'model_c166', [], ExcelValue.by_value
  attach_function 'model_d166', [], ExcelValue.by_value
  attach_function 'model_e166', [], ExcelValue.by_value
  attach_function 'model_f166', [], ExcelValue.by_value
  attach_function 'model_g166', [], ExcelValue.by_value
  attach_function 'model_h166', [], ExcelValue.by_value
  attach_function 'model_i166', [], ExcelValue.by_value
  attach_function 'model_j166', [], ExcelValue.by_value
  attach_function 'model_k166', [], ExcelValue.by_value
  attach_function 'model_l166', [], ExcelValue.by_value
  attach_function 'model_m166', [], ExcelValue.by_value
  attach_function 'model_n166', [], ExcelValue.by_value
  attach_function 'model_o166', [], ExcelValue.by_value
  attach_function 'model_p166', [], ExcelValue.by_value
  attach_function 'model_q166', [], ExcelValue.by_value
  attach_function 'model_r166', [], ExcelValue.by_value
  attach_function 'model_s166', [], ExcelValue.by_value
  attach_function 'model_t166', [], ExcelValue.by_value
  attach_function 'model_u166', [], ExcelValue.by_value
  attach_function 'model_v166', [], ExcelValue.by_value
  attach_function 'model_w166', [], ExcelValue.by_value
  attach_function 'model_x166', [], ExcelValue.by_value
  attach_function 'model_y166', [], ExcelValue.by_value
  attach_function 'model_z166', [], ExcelValue.by_value
  attach_function 'model_aa166', [], ExcelValue.by_value
  attach_function 'model_ab166', [], ExcelValue.by_value
  attach_function 'model_ac166', [], ExcelValue.by_value
  attach_function 'model_ad166', [], ExcelValue.by_value
  attach_function 'model_ae166', [], ExcelValue.by_value
  attach_function 'model_af166', [], ExcelValue.by_value
  attach_function 'model_ag166', [], ExcelValue.by_value
  attach_function 'model_ah166', [], ExcelValue.by_value
  attach_function 'model_ai166', [], ExcelValue.by_value
  attach_function 'model_aj166', [], ExcelValue.by_value
  attach_function 'model_ak166', [], ExcelValue.by_value
  attach_function 'model_al166', [], ExcelValue.by_value
  attach_function 'model_am166', [], ExcelValue.by_value
  attach_function 'model_an166', [], ExcelValue.by_value
  attach_function 'model_ao166', [], ExcelValue.by_value
  attach_function 'model_c155', [], ExcelValue.by_value
  attach_function 'model_d155', [], ExcelValue.by_value
  attach_function 'model_e155', [], ExcelValue.by_value
  attach_function 'model_f155', [], ExcelValue.by_value
  attach_function 'model_g155', [], ExcelValue.by_value
  attach_function 'model_h155', [], ExcelValue.by_value
  attach_function 'model_i155', [], ExcelValue.by_value
  attach_function 'model_j155', [], ExcelValue.by_value
  attach_function 'model_k155', [], ExcelValue.by_value
  attach_function 'model_l155', [], ExcelValue.by_value
  attach_function 'model_m155', [], ExcelValue.by_value
  attach_function 'model_n155', [], ExcelValue.by_value
  attach_function 'model_o155', [], ExcelValue.by_value
  attach_function 'model_p155', [], ExcelValue.by_value
  attach_function 'model_q155', [], ExcelValue.by_value
  attach_function 'model_r155', [], ExcelValue.by_value
  attach_function 'model_s155', [], ExcelValue.by_value
  attach_function 'model_t155', [], ExcelValue.by_value
  attach_function 'model_u155', [], ExcelValue.by_value
  attach_function 'model_v155', [], ExcelValue.by_value
  attach_function 'model_w155', [], ExcelValue.by_value
  attach_function 'model_x155', [], ExcelValue.by_value
  attach_function 'model_y155', [], ExcelValue.by_value
  attach_function 'model_z155', [], ExcelValue.by_value
  attach_function 'model_aa155', [], ExcelValue.by_value
  attach_function 'model_ab155', [], ExcelValue.by_value
  attach_function 'model_ac155', [], ExcelValue.by_value
  attach_function 'model_ad155', [], ExcelValue.by_value
  attach_function 'model_ae155', [], ExcelValue.by_value
  attach_function 'model_af155', [], ExcelValue.by_value
  attach_function 'model_ag155', [], ExcelValue.by_value
  attach_function 'model_ah155', [], ExcelValue.by_value
  attach_function 'model_ai155', [], ExcelValue.by_value
  attach_function 'model_aj155', [], ExcelValue.by_value
  attach_function 'model_ak155', [], ExcelValue.by_value
  attach_function 'model_al155', [], ExcelValue.by_value
  attach_function 'model_am155', [], ExcelValue.by_value
  attach_function 'model_an155', [], ExcelValue.by_value
  attach_function 'model_ao155', [], ExcelValue.by_value
  attach_function 'model_c29', [], ExcelValue.by_value
  attach_function 'model_c157', [], ExcelValue.by_value
  attach_function 'model_d157', [], ExcelValue.by_value
  attach_function 'model_e157', [], ExcelValue.by_value
  attach_function 'model_f157', [], ExcelValue.by_value
  attach_function 'model_g157', [], ExcelValue.by_value
  attach_function 'model_h157', [], ExcelValue.by_value
  attach_function 'model_i157', [], ExcelValue.by_value
  attach_function 'model_j157', [], ExcelValue.by_value
  attach_function 'model_k157', [], ExcelValue.by_value
  attach_function 'model_l157', [], ExcelValue.by_value
  attach_function 'model_m157', [], ExcelValue.by_value
  attach_function 'model_n157', [], ExcelValue.by_value
  attach_function 'model_o157', [], ExcelValue.by_value
  attach_function 'model_p157', [], ExcelValue.by_value
  attach_function 'model_q157', [], ExcelValue.by_value
  attach_function 'model_r157', [], ExcelValue.by_value
  attach_function 'model_s157', [], ExcelValue.by_value
  attach_function 'model_t157', [], ExcelValue.by_value
  attach_function 'model_u157', [], ExcelValue.by_value
  attach_function 'model_v157', [], ExcelValue.by_value
  attach_function 'model_w157', [], ExcelValue.by_value
  attach_function 'model_x157', [], ExcelValue.by_value
  attach_function 'model_y157', [], ExcelValue.by_value
  attach_function 'model_z157', [], ExcelValue.by_value
  attach_function 'model_aa157', [], ExcelValue.by_value
  attach_function 'model_ab157', [], ExcelValue.by_value
  attach_function 'model_ac157', [], ExcelValue.by_value
  attach_function 'model_ad157', [], ExcelValue.by_value
  attach_function 'model_ae157', [], ExcelValue.by_value
  attach_function 'model_af157', [], ExcelValue.by_value
  attach_function 'model_ag157', [], ExcelValue.by_value
  attach_function 'model_ah157', [], ExcelValue.by_value
  attach_function 'model_ai157', [], ExcelValue.by_value
  attach_function 'model_aj157', [], ExcelValue.by_value
  attach_function 'model_ak157', [], ExcelValue.by_value
  attach_function 'model_al157', [], ExcelValue.by_value
  attach_function 'model_am157', [], ExcelValue.by_value
  attach_function 'model_an157', [], ExcelValue.by_value
  attach_function 'model_ao157', [], ExcelValue.by_value
  attach_function 'model_c154', [], ExcelValue.by_value
  attach_function 'model_d154', [], ExcelValue.by_value
  attach_function 'model_e154', [], ExcelValue.by_value
  attach_function 'model_f154', [], ExcelValue.by_value
  attach_function 'model_g154', [], ExcelValue.by_value
  attach_function 'model_h154', [], ExcelValue.by_value
  attach_function 'model_i154', [], ExcelValue.by_value
  attach_function 'model_j154', [], ExcelValue.by_value
  attach_function 'model_k154', [], ExcelValue.by_value
  attach_function 'model_l154', [], ExcelValue.by_value
  attach_function 'model_m154', [], ExcelValue.by_value
  attach_function 'model_n154', [], ExcelValue.by_value
  attach_function 'model_o154', [], ExcelValue.by_value
  attach_function 'model_p154', [], ExcelValue.by_value
  attach_function 'model_q154', [], ExcelValue.by_value
  attach_function 'model_r154', [], ExcelValue.by_value
  attach_function 'model_s154', [], ExcelValue.by_value
  attach_function 'model_t154', [], ExcelValue.by_value
  attach_function 'model_u154', [], ExcelValue.by_value
  attach_function 'model_v154', [], ExcelValue.by_value
  attach_function 'model_w154', [], ExcelValue.by_value
  attach_function 'model_x154', [], ExcelValue.by_value
  attach_function 'model_y154', [], ExcelValue.by_value
  attach_function 'model_z154', [], ExcelValue.by_value
  attach_function 'model_aa154', [], ExcelValue.by_value
  attach_function 'model_ab154', [], ExcelValue.by_value
  attach_function 'model_ac154', [], ExcelValue.by_value
  attach_function 'model_ad154', [], ExcelValue.by_value
  attach_function 'model_ae154', [], ExcelValue.by_value
  attach_function 'model_af154', [], ExcelValue.by_value
  attach_function 'model_ag154', [], ExcelValue.by_value
  attach_function 'model_ah154', [], ExcelValue.by_value
  attach_function 'model_ai154', [], ExcelValue.by_value
  attach_function 'model_aj154', [], ExcelValue.by_value
  attach_function 'model_ak154', [], ExcelValue.by_value
  attach_function 'model_al154', [], ExcelValue.by_value
  attach_function 'model_am154', [], ExcelValue.by_value
  attach_function 'model_an154', [], ExcelValue.by_value
  attach_function 'model_ao154', [], ExcelValue.by_value
  attach_function 'model_c34', [], ExcelValue.by_value
  attach_function 'model_c156', [], ExcelValue.by_value
  attach_function 'model_d156', [], ExcelValue.by_value
  attach_function 'model_e156', [], ExcelValue.by_value
  attach_function 'model_f156', [], ExcelValue.by_value
  attach_function 'model_g156', [], ExcelValue.by_value
  attach_function 'model_h156', [], ExcelValue.by_value
  attach_function 'model_i156', [], ExcelValue.by_value
  attach_function 'model_j156', [], ExcelValue.by_value
  attach_function 'model_k156', [], ExcelValue.by_value
  attach_function 'model_l156', [], ExcelValue.by_value
  attach_function 'model_m156', [], ExcelValue.by_value
  attach_function 'model_n156', [], ExcelValue.by_value
  attach_function 'model_o156', [], ExcelValue.by_value
  attach_function 'model_p156', [], ExcelValue.by_value
  attach_function 'model_q156', [], ExcelValue.by_value
  attach_function 'model_r156', [], ExcelValue.by_value
  attach_function 'model_s156', [], ExcelValue.by_value
  attach_function 'model_t156', [], ExcelValue.by_value
  attach_function 'model_u156', [], ExcelValue.by_value
  attach_function 'model_v156', [], ExcelValue.by_value
  attach_function 'model_w156', [], ExcelValue.by_value
  attach_function 'model_x156', [], ExcelValue.by_value
  attach_function 'model_y156', [], ExcelValue.by_value
  attach_function 'model_z156', [], ExcelValue.by_value
  attach_function 'model_aa156', [], ExcelValue.by_value
  attach_function 'model_ab156', [], ExcelValue.by_value
  attach_function 'model_ac156', [], ExcelValue.by_value
  attach_function 'model_ad156', [], ExcelValue.by_value
  attach_function 'model_ae156', [], ExcelValue.by_value
  attach_function 'model_af156', [], ExcelValue.by_value
  attach_function 'model_ag156', [], ExcelValue.by_value
  attach_function 'model_ah156', [], ExcelValue.by_value
  attach_function 'model_ai156', [], ExcelValue.by_value
  attach_function 'model_aj156', [], ExcelValue.by_value
  attach_function 'model_ak156', [], ExcelValue.by_value
  attach_function 'model_al156', [], ExcelValue.by_value
  attach_function 'model_am156', [], ExcelValue.by_value
  attach_function 'model_an156', [], ExcelValue.by_value
  attach_function 'model_ao156', [], ExcelValue.by_value
  attach_function 'model_c161', [], ExcelValue.by_value
  attach_function 'model_d161', [], ExcelValue.by_value
  attach_function 'model_e161', [], ExcelValue.by_value
  attach_function 'model_f161', [], ExcelValue.by_value
  attach_function 'model_g161', [], ExcelValue.by_value
  attach_function 'model_h161', [], ExcelValue.by_value
  attach_function 'model_i161', [], ExcelValue.by_value
  attach_function 'model_j161', [], ExcelValue.by_value
  attach_function 'model_k161', [], ExcelValue.by_value
  attach_function 'model_l161', [], ExcelValue.by_value
  attach_function 'model_m161', [], ExcelValue.by_value
  attach_function 'model_n161', [], ExcelValue.by_value
  attach_function 'model_o161', [], ExcelValue.by_value
  attach_function 'model_p161', [], ExcelValue.by_value
  attach_function 'model_q161', [], ExcelValue.by_value
  attach_function 'model_r161', [], ExcelValue.by_value
  attach_function 'model_s161', [], ExcelValue.by_value
  attach_function 'model_t161', [], ExcelValue.by_value
  attach_function 'model_u161', [], ExcelValue.by_value
  attach_function 'model_v161', [], ExcelValue.by_value
  attach_function 'model_w161', [], ExcelValue.by_value
  attach_function 'model_x161', [], ExcelValue.by_value
  attach_function 'model_y161', [], ExcelValue.by_value
  attach_function 'model_z161', [], ExcelValue.by_value
  attach_function 'model_aa161', [], ExcelValue.by_value
  attach_function 'model_ab161', [], ExcelValue.by_value
  attach_function 'model_ac161', [], ExcelValue.by_value
  attach_function 'model_ad161', [], ExcelValue.by_value
  attach_function 'model_ae161', [], ExcelValue.by_value
  attach_function 'model_af161', [], ExcelValue.by_value
  attach_function 'model_ag161', [], ExcelValue.by_value
  attach_function 'model_ah161', [], ExcelValue.by_value
  attach_function 'model_ai161', [], ExcelValue.by_value
  attach_function 'model_aj161', [], ExcelValue.by_value
  attach_function 'model_ak161', [], ExcelValue.by_value
  attach_function 'model_al161', [], ExcelValue.by_value
  attach_function 'model_am161', [], ExcelValue.by_value
  attach_function 'model_an161', [], ExcelValue.by_value
  attach_function 'model_ao161', [], ExcelValue.by_value
  attach_function 'model_c163', [], ExcelValue.by_value
  attach_function 'model_d163', [], ExcelValue.by_value
  attach_function 'model_e163', [], ExcelValue.by_value
  attach_function 'model_f163', [], ExcelValue.by_value
  attach_function 'model_g163', [], ExcelValue.by_value
  attach_function 'model_h163', [], ExcelValue.by_value
  attach_function 'model_i163', [], ExcelValue.by_value
  attach_function 'model_j163', [], ExcelValue.by_value
  attach_function 'model_k163', [], ExcelValue.by_value
  attach_function 'model_l163', [], ExcelValue.by_value
  attach_function 'model_m163', [], ExcelValue.by_value
  attach_function 'model_n163', [], ExcelValue.by_value
  attach_function 'model_o163', [], ExcelValue.by_value
  attach_function 'model_p163', [], ExcelValue.by_value
  attach_function 'model_q163', [], ExcelValue.by_value
  attach_function 'model_r163', [], ExcelValue.by_value
  attach_function 'model_s163', [], ExcelValue.by_value
  attach_function 'model_t163', [], ExcelValue.by_value
  attach_function 'model_u163', [], ExcelValue.by_value
  attach_function 'model_v163', [], ExcelValue.by_value
  attach_function 'model_w163', [], ExcelValue.by_value
  attach_function 'model_x163', [], ExcelValue.by_value
  attach_function 'model_y163', [], ExcelValue.by_value
  attach_function 'model_z163', [], ExcelValue.by_value
  attach_function 'model_aa163', [], ExcelValue.by_value
  attach_function 'model_ab163', [], ExcelValue.by_value
  attach_function 'model_ac163', [], ExcelValue.by_value
  attach_function 'model_ad163', [], ExcelValue.by_value
  attach_function 'model_ae163', [], ExcelValue.by_value
  attach_function 'model_af163', [], ExcelValue.by_value
  attach_function 'model_ag163', [], ExcelValue.by_value
  attach_function 'model_ah163', [], ExcelValue.by_value
  attach_function 'model_ai163', [], ExcelValue.by_value
  attach_function 'model_aj163', [], ExcelValue.by_value
  attach_function 'model_ak163', [], ExcelValue.by_value
  attach_function 'model_al163', [], ExcelValue.by_value
  attach_function 'model_am163', [], ExcelValue.by_value
  attach_function 'model_an163', [], ExcelValue.by_value
  attach_function 'model_ao163', [], ExcelValue.by_value
  attach_function 'model_c160', [], ExcelValue.by_value
  attach_function 'model_d160', [], ExcelValue.by_value
  attach_function 'model_e160', [], ExcelValue.by_value
  attach_function 'model_f160', [], ExcelValue.by_value
  attach_function 'model_g160', [], ExcelValue.by_value
  attach_function 'model_h160', [], ExcelValue.by_value
  attach_function 'model_i160', [], ExcelValue.by_value
  attach_function 'model_j160', [], ExcelValue.by_value
  attach_function 'model_k160', [], ExcelValue.by_value
  attach_function 'model_l160', [], ExcelValue.by_value
  attach_function 'model_m160', [], ExcelValue.by_value
  attach_function 'model_n160', [], ExcelValue.by_value
  attach_function 'model_o160', [], ExcelValue.by_value
  attach_function 'model_p160', [], ExcelValue.by_value
  attach_function 'model_q160', [], ExcelValue.by_value
  attach_function 'model_r160', [], ExcelValue.by_value
  attach_function 'model_s160', [], ExcelValue.by_value
  attach_function 'model_t160', [], ExcelValue.by_value
  attach_function 'model_u160', [], ExcelValue.by_value
  attach_function 'model_v160', [], ExcelValue.by_value
  attach_function 'model_w160', [], ExcelValue.by_value
  attach_function 'model_x160', [], ExcelValue.by_value
  attach_function 'model_y160', [], ExcelValue.by_value
  attach_function 'model_z160', [], ExcelValue.by_value
  attach_function 'model_aa160', [], ExcelValue.by_value
  attach_function 'model_ab160', [], ExcelValue.by_value
  attach_function 'model_ac160', [], ExcelValue.by_value
  attach_function 'model_ad160', [], ExcelValue.by_value
  attach_function 'model_ae160', [], ExcelValue.by_value
  attach_function 'model_af160', [], ExcelValue.by_value
  attach_function 'model_ag160', [], ExcelValue.by_value
  attach_function 'model_ah160', [], ExcelValue.by_value
  attach_function 'model_ai160', [], ExcelValue.by_value
  attach_function 'model_aj160', [], ExcelValue.by_value
  attach_function 'model_ak160', [], ExcelValue.by_value
  attach_function 'model_al160', [], ExcelValue.by_value
  attach_function 'model_am160', [], ExcelValue.by_value
  attach_function 'model_an160', [], ExcelValue.by_value
  attach_function 'model_ao160', [], ExcelValue.by_value
  attach_function 'model_c164', [], ExcelValue.by_value
  attach_function 'model_d164', [], ExcelValue.by_value
  attach_function 'model_e164', [], ExcelValue.by_value
  attach_function 'model_f164', [], ExcelValue.by_value
  attach_function 'model_g164', [], ExcelValue.by_value
  attach_function 'model_h164', [], ExcelValue.by_value
  attach_function 'model_i164', [], ExcelValue.by_value
  attach_function 'model_j164', [], ExcelValue.by_value
  attach_function 'model_k164', [], ExcelValue.by_value
  attach_function 'model_l164', [], ExcelValue.by_value
  attach_function 'model_m164', [], ExcelValue.by_value
  attach_function 'model_n164', [], ExcelValue.by_value
  attach_function 'model_o164', [], ExcelValue.by_value
  attach_function 'model_p164', [], ExcelValue.by_value
  attach_function 'model_q164', [], ExcelValue.by_value
  attach_function 'model_r164', [], ExcelValue.by_value
  attach_function 'model_s164', [], ExcelValue.by_value
  attach_function 'model_t164', [], ExcelValue.by_value
  attach_function 'model_u164', [], ExcelValue.by_value
  attach_function 'model_v164', [], ExcelValue.by_value
  attach_function 'model_w164', [], ExcelValue.by_value
  attach_function 'model_x164', [], ExcelValue.by_value
  attach_function 'model_y164', [], ExcelValue.by_value
  attach_function 'model_z164', [], ExcelValue.by_value
  attach_function 'model_aa164', [], ExcelValue.by_value
  attach_function 'model_ab164', [], ExcelValue.by_value
  attach_function 'model_ac164', [], ExcelValue.by_value
  attach_function 'model_ad164', [], ExcelValue.by_value
  attach_function 'model_ae164', [], ExcelValue.by_value
  attach_function 'model_af164', [], ExcelValue.by_value
  attach_function 'model_ag164', [], ExcelValue.by_value
  attach_function 'model_ah164', [], ExcelValue.by_value
  attach_function 'model_ai164', [], ExcelValue.by_value
  attach_function 'model_aj164', [], ExcelValue.by_value
  attach_function 'model_ak164', [], ExcelValue.by_value
  attach_function 'model_al164', [], ExcelValue.by_value
  attach_function 'model_am164', [], ExcelValue.by_value
  attach_function 'model_an164', [], ExcelValue.by_value
  attach_function 'model_ao164', [], ExcelValue.by_value
  attach_function 'model_c162', [], ExcelValue.by_value
  attach_function 'model_d162', [], ExcelValue.by_value
  attach_function 'model_e162', [], ExcelValue.by_value
  attach_function 'model_f162', [], ExcelValue.by_value
  attach_function 'model_g162', [], ExcelValue.by_value
  attach_function 'model_h162', [], ExcelValue.by_value
  attach_function 'model_i162', [], ExcelValue.by_value
  attach_function 'model_j162', [], ExcelValue.by_value
  attach_function 'model_k162', [], ExcelValue.by_value
  attach_function 'model_l162', [], ExcelValue.by_value
  attach_function 'model_m162', [], ExcelValue.by_value
  attach_function 'model_n162', [], ExcelValue.by_value
  attach_function 'model_o162', [], ExcelValue.by_value
  attach_function 'model_p162', [], ExcelValue.by_value
  attach_function 'model_q162', [], ExcelValue.by_value
  attach_function 'model_r162', [], ExcelValue.by_value
  attach_function 'model_s162', [], ExcelValue.by_value
  attach_function 'model_t162', [], ExcelValue.by_value
  attach_function 'model_u162', [], ExcelValue.by_value
  attach_function 'model_v162', [], ExcelValue.by_value
  attach_function 'model_w162', [], ExcelValue.by_value
  attach_function 'model_x162', [], ExcelValue.by_value
  attach_function 'model_y162', [], ExcelValue.by_value
  attach_function 'model_z162', [], ExcelValue.by_value
  attach_function 'model_aa162', [], ExcelValue.by_value
  attach_function 'model_ab162', [], ExcelValue.by_value
  attach_function 'model_ac162', [], ExcelValue.by_value
  attach_function 'model_ad162', [], ExcelValue.by_value
  attach_function 'model_ae162', [], ExcelValue.by_value
  attach_function 'model_af162', [], ExcelValue.by_value
  attach_function 'model_ag162', [], ExcelValue.by_value
  attach_function 'model_ah162', [], ExcelValue.by_value
  attach_function 'model_ai162', [], ExcelValue.by_value
  attach_function 'model_aj162', [], ExcelValue.by_value
  attach_function 'model_ak162', [], ExcelValue.by_value
  attach_function 'model_al162', [], ExcelValue.by_value
  attach_function 'model_am162', [], ExcelValue.by_value
  attach_function 'model_an162', [], ExcelValue.by_value
  attach_function 'model_ao162', [], ExcelValue.by_value
  attach_function 'model_r31', [], ExcelValue.by_value
  attach_function 'model_q31', [], ExcelValue.by_value
  attach_function 'model_p31', [], ExcelValue.by_value
  attach_function 'model_r32', [], ExcelValue.by_value
  attach_function 'model_q32', [], ExcelValue.by_value
  attach_function 'model_p32', [], ExcelValue.by_value
  attach_function 'model_r33', [], ExcelValue.by_value
  attach_function 'model_q33', [], ExcelValue.by_value
  attach_function 'model_p33', [], ExcelValue.by_value
  attach_function 'model_r34', [], ExcelValue.by_value
  attach_function 'model_q34', [], ExcelValue.by_value
  attach_function 'model_p34', [], ExcelValue.by_value
  attach_function 'model_c186', [], ExcelValue.by_value
  attach_function 'model_d186', [], ExcelValue.by_value
  attach_function 'model_e186', [], ExcelValue.by_value
  attach_function 'model_f186', [], ExcelValue.by_value
  attach_function 'model_g186', [], ExcelValue.by_value
  attach_function 'model_h186', [], ExcelValue.by_value
  attach_function 'model_i186', [], ExcelValue.by_value
  attach_function 'model_j186', [], ExcelValue.by_value
  attach_function 'model_k186', [], ExcelValue.by_value
  attach_function 'model_l186', [], ExcelValue.by_value
  attach_function 'model_m186', [], ExcelValue.by_value
  attach_function 'model_n186', [], ExcelValue.by_value
  attach_function 'model_o186', [], ExcelValue.by_value
  attach_function 'model_p186', [], ExcelValue.by_value
  attach_function 'model_q186', [], ExcelValue.by_value
  attach_function 'model_r186', [], ExcelValue.by_value
  attach_function 'model_s186', [], ExcelValue.by_value
  attach_function 'model_t186', [], ExcelValue.by_value
  attach_function 'model_u186', [], ExcelValue.by_value
  attach_function 'model_v186', [], ExcelValue.by_value
  attach_function 'model_w186', [], ExcelValue.by_value
  attach_function 'model_x186', [], ExcelValue.by_value
  attach_function 'model_y186', [], ExcelValue.by_value
  attach_function 'model_z186', [], ExcelValue.by_value
  attach_function 'model_aa186', [], ExcelValue.by_value
  attach_function 'model_ab186', [], ExcelValue.by_value
  attach_function 'model_ac186', [], ExcelValue.by_value
  attach_function 'model_ad186', [], ExcelValue.by_value
  attach_function 'model_ae186', [], ExcelValue.by_value
  attach_function 'model_af186', [], ExcelValue.by_value
  attach_function 'model_ag186', [], ExcelValue.by_value
  attach_function 'model_ah186', [], ExcelValue.by_value
  attach_function 'model_ai186', [], ExcelValue.by_value
  attach_function 'model_aj186', [], ExcelValue.by_value
  attach_function 'model_ak186', [], ExcelValue.by_value
  attach_function 'model_al186', [], ExcelValue.by_value
  attach_function 'model_am186', [], ExcelValue.by_value
  attach_function 'model_an186', [], ExcelValue.by_value
  attach_function 'model_ao186', [], ExcelValue.by_value
  attach_function 'model_c184', [], ExcelValue.by_value
  attach_function 'model_d184', [], ExcelValue.by_value
  attach_function 'model_e184', [], ExcelValue.by_value
  attach_function 'model_f184', [], ExcelValue.by_value
  attach_function 'model_g184', [], ExcelValue.by_value
  attach_function 'model_h184', [], ExcelValue.by_value
  attach_function 'model_i184', [], ExcelValue.by_value
  attach_function 'model_j184', [], ExcelValue.by_value
  attach_function 'model_k184', [], ExcelValue.by_value
  attach_function 'model_l184', [], ExcelValue.by_value
  attach_function 'model_m184', [], ExcelValue.by_value
  attach_function 'model_n184', [], ExcelValue.by_value
  attach_function 'model_o184', [], ExcelValue.by_value
  attach_function 'model_p184', [], ExcelValue.by_value
  attach_function 'model_q184', [], ExcelValue.by_value
  attach_function 'model_r184', [], ExcelValue.by_value
  attach_function 'model_s184', [], ExcelValue.by_value
  attach_function 'model_t184', [], ExcelValue.by_value
  attach_function 'model_u184', [], ExcelValue.by_value
  attach_function 'model_v184', [], ExcelValue.by_value
  attach_function 'model_w184', [], ExcelValue.by_value
  attach_function 'model_x184', [], ExcelValue.by_value
  attach_function 'model_y184', [], ExcelValue.by_value
  attach_function 'model_z184', [], ExcelValue.by_value
  attach_function 'model_aa184', [], ExcelValue.by_value
  attach_function 'model_ab184', [], ExcelValue.by_value
  attach_function 'model_ac184', [], ExcelValue.by_value
  attach_function 'model_ad184', [], ExcelValue.by_value
  attach_function 'model_ae184', [], ExcelValue.by_value
  attach_function 'model_af184', [], ExcelValue.by_value
  attach_function 'model_ag184', [], ExcelValue.by_value
  attach_function 'model_ah184', [], ExcelValue.by_value
  attach_function 'model_ai184', [], ExcelValue.by_value
  attach_function 'model_aj184', [], ExcelValue.by_value
  attach_function 'model_ak184', [], ExcelValue.by_value
  attach_function 'model_al184', [], ExcelValue.by_value
  attach_function 'model_am184', [], ExcelValue.by_value
  attach_function 'model_an184', [], ExcelValue.by_value
  attach_function 'model_ao184', [], ExcelValue.by_value
  attach_function 'model_c187', [], ExcelValue.by_value
  attach_function 'model_d187', [], ExcelValue.by_value
  attach_function 'model_e187', [], ExcelValue.by_value
  attach_function 'model_f187', [], ExcelValue.by_value
  attach_function 'model_g187', [], ExcelValue.by_value
  attach_function 'model_h187', [], ExcelValue.by_value
  attach_function 'model_i187', [], ExcelValue.by_value
  attach_function 'model_j187', [], ExcelValue.by_value
  attach_function 'model_k187', [], ExcelValue.by_value
  attach_function 'model_l187', [], ExcelValue.by_value
  attach_function 'model_m187', [], ExcelValue.by_value
  attach_function 'model_n187', [], ExcelValue.by_value
  attach_function 'model_o187', [], ExcelValue.by_value
  attach_function 'model_p187', [], ExcelValue.by_value
  attach_function 'model_q187', [], ExcelValue.by_value
  attach_function 'model_r187', [], ExcelValue.by_value
  attach_function 'model_s187', [], ExcelValue.by_value
  attach_function 'model_t187', [], ExcelValue.by_value
  attach_function 'model_u187', [], ExcelValue.by_value
  attach_function 'model_v187', [], ExcelValue.by_value
  attach_function 'model_w187', [], ExcelValue.by_value
  attach_function 'model_x187', [], ExcelValue.by_value
  attach_function 'model_y187', [], ExcelValue.by_value
  attach_function 'model_z187', [], ExcelValue.by_value
  attach_function 'model_aa187', [], ExcelValue.by_value
  attach_function 'model_ab187', [], ExcelValue.by_value
  attach_function 'model_ac187', [], ExcelValue.by_value
  attach_function 'model_ad187', [], ExcelValue.by_value
  attach_function 'model_ae187', [], ExcelValue.by_value
  attach_function 'model_af187', [], ExcelValue.by_value
  attach_function 'model_ag187', [], ExcelValue.by_value
  attach_function 'model_ah187', [], ExcelValue.by_value
  attach_function 'model_ai187', [], ExcelValue.by_value
  attach_function 'model_aj187', [], ExcelValue.by_value
  attach_function 'model_ak187', [], ExcelValue.by_value
  attach_function 'model_al187', [], ExcelValue.by_value
  attach_function 'model_am187', [], ExcelValue.by_value
  attach_function 'model_an187', [], ExcelValue.by_value
  attach_function 'model_ao187', [], ExcelValue.by_value
  attach_function 'model_c188', [], ExcelValue.by_value
  attach_function 'model_d188', [], ExcelValue.by_value
  attach_function 'model_e188', [], ExcelValue.by_value
  attach_function 'model_f188', [], ExcelValue.by_value
  attach_function 'model_g188', [], ExcelValue.by_value
  attach_function 'model_h188', [], ExcelValue.by_value
  attach_function 'model_i188', [], ExcelValue.by_value
  attach_function 'model_j188', [], ExcelValue.by_value
  attach_function 'model_k188', [], ExcelValue.by_value
  attach_function 'model_l188', [], ExcelValue.by_value
  attach_function 'model_m188', [], ExcelValue.by_value
  attach_function 'model_n188', [], ExcelValue.by_value
  attach_function 'model_o188', [], ExcelValue.by_value
  attach_function 'model_p188', [], ExcelValue.by_value
  attach_function 'model_q188', [], ExcelValue.by_value
  attach_function 'model_r188', [], ExcelValue.by_value
  attach_function 'model_s188', [], ExcelValue.by_value
  attach_function 'model_t188', [], ExcelValue.by_value
  attach_function 'model_u188', [], ExcelValue.by_value
  attach_function 'model_v188', [], ExcelValue.by_value
  attach_function 'model_w188', [], ExcelValue.by_value
  attach_function 'model_x188', [], ExcelValue.by_value
  attach_function 'model_y188', [], ExcelValue.by_value
  attach_function 'model_z188', [], ExcelValue.by_value
  attach_function 'model_aa188', [], ExcelValue.by_value
  attach_function 'model_ab188', [], ExcelValue.by_value
  attach_function 'model_ac188', [], ExcelValue.by_value
  attach_function 'model_ad188', [], ExcelValue.by_value
  attach_function 'model_ae188', [], ExcelValue.by_value
  attach_function 'model_af188', [], ExcelValue.by_value
  attach_function 'model_ag188', [], ExcelValue.by_value
  attach_function 'model_ah188', [], ExcelValue.by_value
  attach_function 'model_ai188', [], ExcelValue.by_value
  attach_function 'model_aj188', [], ExcelValue.by_value
  attach_function 'model_ak188', [], ExcelValue.by_value
  attach_function 'model_al188', [], ExcelValue.by_value
  attach_function 'model_am188', [], ExcelValue.by_value
  attach_function 'model_an188', [], ExcelValue.by_value
  attach_function 'model_ao188', [], ExcelValue.by_value
  attach_function 'model_c190', [], ExcelValue.by_value
  attach_function 'model_d190', [], ExcelValue.by_value
  attach_function 'model_e190', [], ExcelValue.by_value
  attach_function 'model_f190', [], ExcelValue.by_value
  attach_function 'model_g190', [], ExcelValue.by_value
  attach_function 'model_h190', [], ExcelValue.by_value
  attach_function 'model_i190', [], ExcelValue.by_value
  attach_function 'model_j190', [], ExcelValue.by_value
  attach_function 'model_k190', [], ExcelValue.by_value
  attach_function 'model_l190', [], ExcelValue.by_value
  attach_function 'model_m190', [], ExcelValue.by_value
  attach_function 'model_n190', [], ExcelValue.by_value
  attach_function 'model_o190', [], ExcelValue.by_value
  attach_function 'model_p190', [], ExcelValue.by_value
  attach_function 'model_q190', [], ExcelValue.by_value
  attach_function 'model_r190', [], ExcelValue.by_value
  attach_function 'model_s190', [], ExcelValue.by_value
  attach_function 'model_t190', [], ExcelValue.by_value
  attach_function 'model_u190', [], ExcelValue.by_value
  attach_function 'model_v190', [], ExcelValue.by_value
  attach_function 'model_w190', [], ExcelValue.by_value
  attach_function 'model_x190', [], ExcelValue.by_value
  attach_function 'model_y190', [], ExcelValue.by_value
  attach_function 'model_z190', [], ExcelValue.by_value
  attach_function 'model_aa190', [], ExcelValue.by_value
  attach_function 'model_ab190', [], ExcelValue.by_value
  attach_function 'model_ac190', [], ExcelValue.by_value
  attach_function 'model_ad190', [], ExcelValue.by_value
  attach_function 'model_ae190', [], ExcelValue.by_value
  attach_function 'model_af190', [], ExcelValue.by_value
  attach_function 'model_ag190', [], ExcelValue.by_value
  attach_function 'model_ah190', [], ExcelValue.by_value
  attach_function 'model_ai190', [], ExcelValue.by_value
  attach_function 'model_aj190', [], ExcelValue.by_value
  attach_function 'model_ak190', [], ExcelValue.by_value
  attach_function 'model_al190', [], ExcelValue.by_value
  attach_function 'model_am190', [], ExcelValue.by_value
  attach_function 'model_an190', [], ExcelValue.by_value
  attach_function 'model_ao190', [], ExcelValue.by_value
  attach_function 'model_c189', [], ExcelValue.by_value
  attach_function 'model_d189', [], ExcelValue.by_value
  attach_function 'model_e189', [], ExcelValue.by_value
  attach_function 'model_f189', [], ExcelValue.by_value
  attach_function 'model_g189', [], ExcelValue.by_value
  attach_function 'model_h189', [], ExcelValue.by_value
  attach_function 'model_i189', [], ExcelValue.by_value
  attach_function 'model_j189', [], ExcelValue.by_value
  attach_function 'model_k189', [], ExcelValue.by_value
  attach_function 'model_l189', [], ExcelValue.by_value
  attach_function 'model_m189', [], ExcelValue.by_value
  attach_function 'model_n189', [], ExcelValue.by_value
  attach_function 'model_o189', [], ExcelValue.by_value
  attach_function 'model_p189', [], ExcelValue.by_value
  attach_function 'model_q189', [], ExcelValue.by_value
  attach_function 'model_r189', [], ExcelValue.by_value
  attach_function 'model_s189', [], ExcelValue.by_value
  attach_function 'model_t189', [], ExcelValue.by_value
  attach_function 'model_u189', [], ExcelValue.by_value
  attach_function 'model_v189', [], ExcelValue.by_value
  attach_function 'model_w189', [], ExcelValue.by_value
  attach_function 'model_x189', [], ExcelValue.by_value
  attach_function 'model_y189', [], ExcelValue.by_value
  attach_function 'model_z189', [], ExcelValue.by_value
  attach_function 'model_aa189', [], ExcelValue.by_value
  attach_function 'model_ab189', [], ExcelValue.by_value
  attach_function 'model_ac189', [], ExcelValue.by_value
  attach_function 'model_ad189', [], ExcelValue.by_value
  attach_function 'model_ae189', [], ExcelValue.by_value
  attach_function 'model_af189', [], ExcelValue.by_value
  attach_function 'model_ag189', [], ExcelValue.by_value
  attach_function 'model_ah189', [], ExcelValue.by_value
  attach_function 'model_ai189', [], ExcelValue.by_value
  attach_function 'model_aj189', [], ExcelValue.by_value
  attach_function 'model_ak189', [], ExcelValue.by_value
  attach_function 'model_al189', [], ExcelValue.by_value
  attach_function 'model_am189', [], ExcelValue.by_value
  attach_function 'model_an189', [], ExcelValue.by_value
  attach_function 'model_ao189', [], ExcelValue.by_value
  attach_function 'model_c179', [], ExcelValue.by_value
  attach_function 'model_d179', [], ExcelValue.by_value
  attach_function 'model_e179', [], ExcelValue.by_value
  attach_function 'model_f179', [], ExcelValue.by_value
  attach_function 'model_g179', [], ExcelValue.by_value
  attach_function 'model_h179', [], ExcelValue.by_value
  attach_function 'model_i179', [], ExcelValue.by_value
  attach_function 'model_j179', [], ExcelValue.by_value
  attach_function 'model_k179', [], ExcelValue.by_value
  attach_function 'model_l179', [], ExcelValue.by_value
  attach_function 'model_m179', [], ExcelValue.by_value
  attach_function 'model_n179', [], ExcelValue.by_value
  attach_function 'model_o179', [], ExcelValue.by_value
  attach_function 'model_p179', [], ExcelValue.by_value
  attach_function 'model_q179', [], ExcelValue.by_value
  attach_function 'model_r179', [], ExcelValue.by_value
  attach_function 'model_s179', [], ExcelValue.by_value
  attach_function 'model_t179', [], ExcelValue.by_value
  attach_function 'model_u179', [], ExcelValue.by_value
  attach_function 'model_v179', [], ExcelValue.by_value
  attach_function 'model_w179', [], ExcelValue.by_value
  attach_function 'model_x179', [], ExcelValue.by_value
  attach_function 'model_y179', [], ExcelValue.by_value
  attach_function 'model_z179', [], ExcelValue.by_value
  attach_function 'model_aa179', [], ExcelValue.by_value
  attach_function 'model_ab179', [], ExcelValue.by_value
  attach_function 'model_ac179', [], ExcelValue.by_value
  attach_function 'model_ad179', [], ExcelValue.by_value
  attach_function 'model_ae179', [], ExcelValue.by_value
  attach_function 'model_af179', [], ExcelValue.by_value
  attach_function 'model_ag179', [], ExcelValue.by_value
  attach_function 'model_ah179', [], ExcelValue.by_value
  attach_function 'model_ai179', [], ExcelValue.by_value
  attach_function 'model_aj179', [], ExcelValue.by_value
  attach_function 'model_ak179', [], ExcelValue.by_value
  attach_function 'model_al179', [], ExcelValue.by_value
  attach_function 'model_am179', [], ExcelValue.by_value
  attach_function 'model_an179', [], ExcelValue.by_value
  attach_function 'model_ao179', [], ExcelValue.by_value
  attach_function 'model_c181', [], ExcelValue.by_value
  attach_function 'model_d181', [], ExcelValue.by_value
  attach_function 'model_e181', [], ExcelValue.by_value
  attach_function 'model_f181', [], ExcelValue.by_value
  attach_function 'model_g181', [], ExcelValue.by_value
  attach_function 'model_h181', [], ExcelValue.by_value
  attach_function 'model_i181', [], ExcelValue.by_value
  attach_function 'model_j181', [], ExcelValue.by_value
  attach_function 'model_k181', [], ExcelValue.by_value
  attach_function 'model_l181', [], ExcelValue.by_value
  attach_function 'model_m181', [], ExcelValue.by_value
  attach_function 'model_n181', [], ExcelValue.by_value
  attach_function 'model_o181', [], ExcelValue.by_value
  attach_function 'model_p181', [], ExcelValue.by_value
  attach_function 'model_q181', [], ExcelValue.by_value
  attach_function 'model_r181', [], ExcelValue.by_value
  attach_function 'model_s181', [], ExcelValue.by_value
  attach_function 'model_t181', [], ExcelValue.by_value
  attach_function 'model_u181', [], ExcelValue.by_value
  attach_function 'model_v181', [], ExcelValue.by_value
  attach_function 'model_w181', [], ExcelValue.by_value
  attach_function 'model_x181', [], ExcelValue.by_value
  attach_function 'model_y181', [], ExcelValue.by_value
  attach_function 'model_z181', [], ExcelValue.by_value
  attach_function 'model_aa181', [], ExcelValue.by_value
  attach_function 'model_ab181', [], ExcelValue.by_value
  attach_function 'model_ac181', [], ExcelValue.by_value
  attach_function 'model_ad181', [], ExcelValue.by_value
  attach_function 'model_ae181', [], ExcelValue.by_value
  attach_function 'model_af181', [], ExcelValue.by_value
  attach_function 'model_ag181', [], ExcelValue.by_value
  attach_function 'model_ah181', [], ExcelValue.by_value
  attach_function 'model_ai181', [], ExcelValue.by_value
  attach_function 'model_aj181', [], ExcelValue.by_value
  attach_function 'model_ak181', [], ExcelValue.by_value
  attach_function 'model_al181', [], ExcelValue.by_value
  attach_function 'model_am181', [], ExcelValue.by_value
  attach_function 'model_an181', [], ExcelValue.by_value
  attach_function 'model_ao181', [], ExcelValue.by_value
  attach_function 'model_c178', [], ExcelValue.by_value
  attach_function 'model_d178', [], ExcelValue.by_value
  attach_function 'model_e178', [], ExcelValue.by_value
  attach_function 'model_f178', [], ExcelValue.by_value
  attach_function 'model_g178', [], ExcelValue.by_value
  attach_function 'model_h178', [], ExcelValue.by_value
  attach_function 'model_i178', [], ExcelValue.by_value
  attach_function 'model_j178', [], ExcelValue.by_value
  attach_function 'model_k178', [], ExcelValue.by_value
  attach_function 'model_l178', [], ExcelValue.by_value
  attach_function 'model_m178', [], ExcelValue.by_value
  attach_function 'model_n178', [], ExcelValue.by_value
  attach_function 'model_o178', [], ExcelValue.by_value
  attach_function 'model_p178', [], ExcelValue.by_value
  attach_function 'model_q178', [], ExcelValue.by_value
  attach_function 'model_r178', [], ExcelValue.by_value
  attach_function 'model_s178', [], ExcelValue.by_value
  attach_function 'model_t178', [], ExcelValue.by_value
  attach_function 'model_u178', [], ExcelValue.by_value
  attach_function 'model_v178', [], ExcelValue.by_value
  attach_function 'model_w178', [], ExcelValue.by_value
  attach_function 'model_x178', [], ExcelValue.by_value
  attach_function 'model_y178', [], ExcelValue.by_value
  attach_function 'model_z178', [], ExcelValue.by_value
  attach_function 'model_aa178', [], ExcelValue.by_value
  attach_function 'model_ab178', [], ExcelValue.by_value
  attach_function 'model_ac178', [], ExcelValue.by_value
  attach_function 'model_ad178', [], ExcelValue.by_value
  attach_function 'model_ae178', [], ExcelValue.by_value
  attach_function 'model_af178', [], ExcelValue.by_value
  attach_function 'model_ag178', [], ExcelValue.by_value
  attach_function 'model_ah178', [], ExcelValue.by_value
  attach_function 'model_ai178', [], ExcelValue.by_value
  attach_function 'model_aj178', [], ExcelValue.by_value
  attach_function 'model_ak178', [], ExcelValue.by_value
  attach_function 'model_al178', [], ExcelValue.by_value
  attach_function 'model_am178', [], ExcelValue.by_value
  attach_function 'model_an178', [], ExcelValue.by_value
  attach_function 'model_ao178', [], ExcelValue.by_value
  attach_function 'model_c180', [], ExcelValue.by_value
  attach_function 'model_d180', [], ExcelValue.by_value
  attach_function 'model_e180', [], ExcelValue.by_value
  attach_function 'model_f180', [], ExcelValue.by_value
  attach_function 'model_g180', [], ExcelValue.by_value
  attach_function 'model_h180', [], ExcelValue.by_value
  attach_function 'model_i180', [], ExcelValue.by_value
  attach_function 'model_j180', [], ExcelValue.by_value
  attach_function 'model_k180', [], ExcelValue.by_value
  attach_function 'model_l180', [], ExcelValue.by_value
  attach_function 'model_m180', [], ExcelValue.by_value
  attach_function 'model_n180', [], ExcelValue.by_value
  attach_function 'model_o180', [], ExcelValue.by_value
  attach_function 'model_p180', [], ExcelValue.by_value
  attach_function 'model_q180', [], ExcelValue.by_value
  attach_function 'model_r180', [], ExcelValue.by_value
  attach_function 'model_s180', [], ExcelValue.by_value
  attach_function 'model_t180', [], ExcelValue.by_value
  attach_function 'model_u180', [], ExcelValue.by_value
  attach_function 'model_v180', [], ExcelValue.by_value
  attach_function 'model_w180', [], ExcelValue.by_value
  attach_function 'model_x180', [], ExcelValue.by_value
  attach_function 'model_y180', [], ExcelValue.by_value
  attach_function 'model_z180', [], ExcelValue.by_value
  attach_function 'model_aa180', [], ExcelValue.by_value
  attach_function 'model_ab180', [], ExcelValue.by_value
  attach_function 'model_ac180', [], ExcelValue.by_value
  attach_function 'model_ad180', [], ExcelValue.by_value
  attach_function 'model_ae180', [], ExcelValue.by_value
  attach_function 'model_af180', [], ExcelValue.by_value
  attach_function 'model_ag180', [], ExcelValue.by_value
  attach_function 'model_ah180', [], ExcelValue.by_value
  attach_function 'model_ai180', [], ExcelValue.by_value
  attach_function 'model_aj180', [], ExcelValue.by_value
  attach_function 'model_ak180', [], ExcelValue.by_value
  attach_function 'model_al180', [], ExcelValue.by_value
  attach_function 'model_am180', [], ExcelValue.by_value
  attach_function 'model_an180', [], ExcelValue.by_value
  attach_function 'model_ao180', [], ExcelValue.by_value
  attach_function 'model_c114', [], ExcelValue.by_value
  attach_function 'model_c173', [], ExcelValue.by_value
  attach_function 'model_d173', [], ExcelValue.by_value
  attach_function 'model_e173', [], ExcelValue.by_value
  attach_function 'model_f173', [], ExcelValue.by_value
  attach_function 'model_g173', [], ExcelValue.by_value
  attach_function 'model_h173', [], ExcelValue.by_value
  attach_function 'model_i173', [], ExcelValue.by_value
  attach_function 'model_j173', [], ExcelValue.by_value
  attach_function 'model_k173', [], ExcelValue.by_value
  attach_function 'model_l173', [], ExcelValue.by_value
  attach_function 'model_m173', [], ExcelValue.by_value
  attach_function 'model_n173', [], ExcelValue.by_value
  attach_function 'model_o173', [], ExcelValue.by_value
  attach_function 'model_p173', [], ExcelValue.by_value
  attach_function 'model_q173', [], ExcelValue.by_value
  attach_function 'model_r173', [], ExcelValue.by_value
  attach_function 'model_s173', [], ExcelValue.by_value
  attach_function 'model_t173', [], ExcelValue.by_value
  attach_function 'model_u173', [], ExcelValue.by_value
  attach_function 'model_v173', [], ExcelValue.by_value
  attach_function 'model_w173', [], ExcelValue.by_value
  attach_function 'model_x173', [], ExcelValue.by_value
  attach_function 'model_y173', [], ExcelValue.by_value
  attach_function 'model_z173', [], ExcelValue.by_value
  attach_function 'model_aa173', [], ExcelValue.by_value
  attach_function 'model_ab173', [], ExcelValue.by_value
  attach_function 'model_ac173', [], ExcelValue.by_value
  attach_function 'model_ad173', [], ExcelValue.by_value
  attach_function 'model_ae173', [], ExcelValue.by_value
  attach_function 'model_af173', [], ExcelValue.by_value
  attach_function 'model_ag173', [], ExcelValue.by_value
  attach_function 'model_ah173', [], ExcelValue.by_value
  attach_function 'model_ai173', [], ExcelValue.by_value
  attach_function 'model_aj173', [], ExcelValue.by_value
  attach_function 'model_ak173', [], ExcelValue.by_value
  attach_function 'model_al173', [], ExcelValue.by_value
  attach_function 'model_am173', [], ExcelValue.by_value
  attach_function 'model_an173', [], ExcelValue.by_value
  attach_function 'model_ao173', [], ExcelValue.by_value
  attach_function 'model_c175', [], ExcelValue.by_value
  attach_function 'model_d175', [], ExcelValue.by_value
  attach_function 'model_e175', [], ExcelValue.by_value
  attach_function 'model_f175', [], ExcelValue.by_value
  attach_function 'model_g175', [], ExcelValue.by_value
  attach_function 'model_h175', [], ExcelValue.by_value
  attach_function 'model_i175', [], ExcelValue.by_value
  attach_function 'model_j175', [], ExcelValue.by_value
  attach_function 'model_k175', [], ExcelValue.by_value
  attach_function 'model_l175', [], ExcelValue.by_value
  attach_function 'model_m175', [], ExcelValue.by_value
  attach_function 'model_n175', [], ExcelValue.by_value
  attach_function 'model_o175', [], ExcelValue.by_value
  attach_function 'model_p175', [], ExcelValue.by_value
  attach_function 'model_q175', [], ExcelValue.by_value
  attach_function 'model_r175', [], ExcelValue.by_value
  attach_function 'model_s175', [], ExcelValue.by_value
  attach_function 'model_t175', [], ExcelValue.by_value
  attach_function 'model_u175', [], ExcelValue.by_value
  attach_function 'model_v175', [], ExcelValue.by_value
  attach_function 'model_w175', [], ExcelValue.by_value
  attach_function 'model_x175', [], ExcelValue.by_value
  attach_function 'model_y175', [], ExcelValue.by_value
  attach_function 'model_z175', [], ExcelValue.by_value
  attach_function 'model_aa175', [], ExcelValue.by_value
  attach_function 'model_ab175', [], ExcelValue.by_value
  attach_function 'model_ac175', [], ExcelValue.by_value
  attach_function 'model_ad175', [], ExcelValue.by_value
  attach_function 'model_ae175', [], ExcelValue.by_value
  attach_function 'model_af175', [], ExcelValue.by_value
  attach_function 'model_ag175', [], ExcelValue.by_value
  attach_function 'model_ah175', [], ExcelValue.by_value
  attach_function 'model_ai175', [], ExcelValue.by_value
  attach_function 'model_aj175', [], ExcelValue.by_value
  attach_function 'model_ak175', [], ExcelValue.by_value
  attach_function 'model_al175', [], ExcelValue.by_value
  attach_function 'model_am175', [], ExcelValue.by_value
  attach_function 'model_an175', [], ExcelValue.by_value
  attach_function 'model_ao175', [], ExcelValue.by_value
  attach_function 'model_c172', [], ExcelValue.by_value
  attach_function 'model_d172', [], ExcelValue.by_value
  attach_function 'model_e172', [], ExcelValue.by_value
  attach_function 'model_f172', [], ExcelValue.by_value
  attach_function 'model_g172', [], ExcelValue.by_value
  attach_function 'model_h172', [], ExcelValue.by_value
  attach_function 'model_i172', [], ExcelValue.by_value
  attach_function 'model_j172', [], ExcelValue.by_value
  attach_function 'model_k172', [], ExcelValue.by_value
  attach_function 'model_l172', [], ExcelValue.by_value
  attach_function 'model_m172', [], ExcelValue.by_value
  attach_function 'model_n172', [], ExcelValue.by_value
  attach_function 'model_o172', [], ExcelValue.by_value
  attach_function 'model_p172', [], ExcelValue.by_value
  attach_function 'model_q172', [], ExcelValue.by_value
  attach_function 'model_r172', [], ExcelValue.by_value
  attach_function 'model_s172', [], ExcelValue.by_value
  attach_function 'model_t172', [], ExcelValue.by_value
  attach_function 'model_u172', [], ExcelValue.by_value
  attach_function 'model_v172', [], ExcelValue.by_value
  attach_function 'model_w172', [], ExcelValue.by_value
  attach_function 'model_x172', [], ExcelValue.by_value
  attach_function 'model_y172', [], ExcelValue.by_value
  attach_function 'model_z172', [], ExcelValue.by_value
  attach_function 'model_aa172', [], ExcelValue.by_value
  attach_function 'model_ab172', [], ExcelValue.by_value
  attach_function 'model_ac172', [], ExcelValue.by_value
  attach_function 'model_ad172', [], ExcelValue.by_value
  attach_function 'model_ae172', [], ExcelValue.by_value
  attach_function 'model_af172', [], ExcelValue.by_value
  attach_function 'model_ag172', [], ExcelValue.by_value
  attach_function 'model_ah172', [], ExcelValue.by_value
  attach_function 'model_ai172', [], ExcelValue.by_value
  attach_function 'model_aj172', [], ExcelValue.by_value
  attach_function 'model_ak172', [], ExcelValue.by_value
  attach_function 'model_al172', [], ExcelValue.by_value
  attach_function 'model_am172', [], ExcelValue.by_value
  attach_function 'model_an172', [], ExcelValue.by_value
  attach_function 'model_ao172', [], ExcelValue.by_value
  attach_function 'model_c174', [], ExcelValue.by_value
  attach_function 'model_d174', [], ExcelValue.by_value
  attach_function 'model_e174', [], ExcelValue.by_value
  attach_function 'model_f174', [], ExcelValue.by_value
  attach_function 'model_g174', [], ExcelValue.by_value
  attach_function 'model_h174', [], ExcelValue.by_value
  attach_function 'model_i174', [], ExcelValue.by_value
  attach_function 'model_j174', [], ExcelValue.by_value
  attach_function 'model_k174', [], ExcelValue.by_value
  attach_function 'model_l174', [], ExcelValue.by_value
  attach_function 'model_m174', [], ExcelValue.by_value
  attach_function 'model_n174', [], ExcelValue.by_value
  attach_function 'model_o174', [], ExcelValue.by_value
  attach_function 'model_p174', [], ExcelValue.by_value
  attach_function 'model_q174', [], ExcelValue.by_value
  attach_function 'model_r174', [], ExcelValue.by_value
  attach_function 'model_s174', [], ExcelValue.by_value
  attach_function 'model_t174', [], ExcelValue.by_value
  attach_function 'model_u174', [], ExcelValue.by_value
  attach_function 'model_v174', [], ExcelValue.by_value
  attach_function 'model_w174', [], ExcelValue.by_value
  attach_function 'model_x174', [], ExcelValue.by_value
  attach_function 'model_y174', [], ExcelValue.by_value
  attach_function 'model_z174', [], ExcelValue.by_value
  attach_function 'model_aa174', [], ExcelValue.by_value
  attach_function 'model_ab174', [], ExcelValue.by_value
  attach_function 'model_ac174', [], ExcelValue.by_value
  attach_function 'model_ad174', [], ExcelValue.by_value
  attach_function 'model_ae174', [], ExcelValue.by_value
  attach_function 'model_af174', [], ExcelValue.by_value
  attach_function 'model_ag174', [], ExcelValue.by_value
  attach_function 'model_ah174', [], ExcelValue.by_value
  attach_function 'model_ai174', [], ExcelValue.by_value
  attach_function 'model_aj174', [], ExcelValue.by_value
  attach_function 'model_ak174', [], ExcelValue.by_value
  attach_function 'model_al174', [], ExcelValue.by_value
  attach_function 'model_am174', [], ExcelValue.by_value
  attach_function 'model_an174', [], ExcelValue.by_value
  attach_function 'model_ao174', [], ExcelValue.by_value
  attach_function 'model_c171', [], ExcelValue.by_value
  attach_function 'model_d171', [], ExcelValue.by_value
  attach_function 'model_e171', [], ExcelValue.by_value
  attach_function 'model_f171', [], ExcelValue.by_value
  attach_function 'model_g171', [], ExcelValue.by_value
  attach_function 'model_h171', [], ExcelValue.by_value
  attach_function 'model_i171', [], ExcelValue.by_value
  attach_function 'model_j171', [], ExcelValue.by_value
  attach_function 'model_k171', [], ExcelValue.by_value
  attach_function 'model_l171', [], ExcelValue.by_value
  attach_function 'model_m171', [], ExcelValue.by_value
  attach_function 'model_n171', [], ExcelValue.by_value
  attach_function 'model_o171', [], ExcelValue.by_value
  attach_function 'model_p171', [], ExcelValue.by_value
  attach_function 'model_q171', [], ExcelValue.by_value
  attach_function 'model_r171', [], ExcelValue.by_value
  attach_function 'model_s171', [], ExcelValue.by_value
  attach_function 'model_t171', [], ExcelValue.by_value
  attach_function 'model_u171', [], ExcelValue.by_value
  attach_function 'model_v171', [], ExcelValue.by_value
  attach_function 'model_w171', [], ExcelValue.by_value
  attach_function 'model_x171', [], ExcelValue.by_value
  attach_function 'model_y171', [], ExcelValue.by_value
  attach_function 'model_z171', [], ExcelValue.by_value
  attach_function 'model_aa171', [], ExcelValue.by_value
  attach_function 'model_ab171', [], ExcelValue.by_value
  attach_function 'model_ac171', [], ExcelValue.by_value
  attach_function 'model_ad171', [], ExcelValue.by_value
  attach_function 'model_ae171', [], ExcelValue.by_value
  attach_function 'model_af171', [], ExcelValue.by_value
  attach_function 'model_ag171', [], ExcelValue.by_value
  attach_function 'model_ah171', [], ExcelValue.by_value
  attach_function 'model_ai171', [], ExcelValue.by_value
  attach_function 'model_aj171', [], ExcelValue.by_value
  attach_function 'model_ak171', [], ExcelValue.by_value
  attach_function 'model_al171', [], ExcelValue.by_value
  attach_function 'model_am171', [], ExcelValue.by_value
  attach_function 'model_an171', [], ExcelValue.by_value
  attach_function 'model_ao171', [], ExcelValue.by_value
  attach_function 'model_c39', [], ExcelValue.by_value
  attach_function 'model_c38', [], ExcelValue.by_value
  attach_function 'model_c167', [], ExcelValue.by_value
  attach_function 'model_d167', [], ExcelValue.by_value
  attach_function 'model_e167', [], ExcelValue.by_value
  attach_function 'model_f167', [], ExcelValue.by_value
  attach_function 'model_g167', [], ExcelValue.by_value
  attach_function 'model_h167', [], ExcelValue.by_value
  attach_function 'model_i167', [], ExcelValue.by_value
  attach_function 'model_j167', [], ExcelValue.by_value
  attach_function 'model_k167', [], ExcelValue.by_value
  attach_function 'model_l167', [], ExcelValue.by_value
  attach_function 'model_m167', [], ExcelValue.by_value
  attach_function 'model_n167', [], ExcelValue.by_value
  attach_function 'model_o167', [], ExcelValue.by_value
  attach_function 'model_p167', [], ExcelValue.by_value
  attach_function 'model_q167', [], ExcelValue.by_value
  attach_function 'model_r167', [], ExcelValue.by_value
  attach_function 'model_s167', [], ExcelValue.by_value
  attach_function 'model_t167', [], ExcelValue.by_value
  attach_function 'model_u167', [], ExcelValue.by_value
  attach_function 'model_v167', [], ExcelValue.by_value
  attach_function 'model_w167', [], ExcelValue.by_value
  attach_function 'model_x167', [], ExcelValue.by_value
  attach_function 'model_y167', [], ExcelValue.by_value
  attach_function 'model_z167', [], ExcelValue.by_value
  attach_function 'model_aa167', [], ExcelValue.by_value
  attach_function 'model_ab167', [], ExcelValue.by_value
  attach_function 'model_ac167', [], ExcelValue.by_value
  attach_function 'model_ad167', [], ExcelValue.by_value
  attach_function 'model_ae167', [], ExcelValue.by_value
  attach_function 'model_af167', [], ExcelValue.by_value
  attach_function 'model_ag167', [], ExcelValue.by_value
  attach_function 'model_ah167', [], ExcelValue.by_value
  attach_function 'model_ai167', [], ExcelValue.by_value
  attach_function 'model_aj167', [], ExcelValue.by_value
  attach_function 'model_ak167', [], ExcelValue.by_value
  attach_function 'model_al167', [], ExcelValue.by_value
  attach_function 'model_am167', [], ExcelValue.by_value
  attach_function 'model_an167', [], ExcelValue.by_value
  attach_function 'model_ao167', [], ExcelValue.by_value
  attach_function 'model_c37', [], ExcelValue.by_value
  attach_function 'model_c168', [], ExcelValue.by_value
  attach_function 'model_d168', [], ExcelValue.by_value
  attach_function 'model_e168', [], ExcelValue.by_value
  attach_function 'model_f168', [], ExcelValue.by_value
  attach_function 'model_g168', [], ExcelValue.by_value
  attach_function 'model_h168', [], ExcelValue.by_value
  attach_function 'model_i168', [], ExcelValue.by_value
  attach_function 'model_j168', [], ExcelValue.by_value
  attach_function 'model_k168', [], ExcelValue.by_value
  attach_function 'model_l168', [], ExcelValue.by_value
  attach_function 'model_m168', [], ExcelValue.by_value
  attach_function 'model_n168', [], ExcelValue.by_value
  attach_function 'model_o168', [], ExcelValue.by_value
  attach_function 'model_p168', [], ExcelValue.by_value
  attach_function 'model_q168', [], ExcelValue.by_value
  attach_function 'model_r168', [], ExcelValue.by_value
  attach_function 'model_s168', [], ExcelValue.by_value
  attach_function 'model_t168', [], ExcelValue.by_value
  attach_function 'model_u168', [], ExcelValue.by_value
  attach_function 'model_v168', [], ExcelValue.by_value
  attach_function 'model_w168', [], ExcelValue.by_value
  attach_function 'model_x168', [], ExcelValue.by_value
  attach_function 'model_y168', [], ExcelValue.by_value
  attach_function 'model_z168', [], ExcelValue.by_value
  attach_function 'model_aa168', [], ExcelValue.by_value
  attach_function 'model_ab168', [], ExcelValue.by_value
  attach_function 'model_ac168', [], ExcelValue.by_value
  attach_function 'model_ad168', [], ExcelValue.by_value
  attach_function 'model_ae168', [], ExcelValue.by_value
  attach_function 'model_af168', [], ExcelValue.by_value
  attach_function 'model_ag168', [], ExcelValue.by_value
  attach_function 'model_ah168', [], ExcelValue.by_value
  attach_function 'model_ai168', [], ExcelValue.by_value
  attach_function 'model_aj168', [], ExcelValue.by_value
  attach_function 'model_ak168', [], ExcelValue.by_value
  attach_function 'model_al168', [], ExcelValue.by_value
  attach_function 'model_am168', [], ExcelValue.by_value
  attach_function 'model_an168', [], ExcelValue.by_value
  attach_function 'model_ao168', [], ExcelValue.by_value
  attach_function 'model_c30', [], ExcelValue.by_value
  attach_function 'model_c35', [], ExcelValue.by_value
  attach_function 'model_c193', [], ExcelValue.by_value
  attach_function 'model_d193', [], ExcelValue.by_value
  attach_function 'model_e193', [], ExcelValue.by_value
  attach_function 'model_f193', [], ExcelValue.by_value
  attach_function 'model_g193', [], ExcelValue.by_value
  attach_function 'model_h193', [], ExcelValue.by_value
  attach_function 'model_i193', [], ExcelValue.by_value
  attach_function 'model_j193', [], ExcelValue.by_value
  attach_function 'model_k193', [], ExcelValue.by_value
  attach_function 'model_l193', [], ExcelValue.by_value
  attach_function 'model_m193', [], ExcelValue.by_value
  attach_function 'model_n193', [], ExcelValue.by_value
  attach_function 'model_o193', [], ExcelValue.by_value
  attach_function 'model_p193', [], ExcelValue.by_value
  attach_function 'model_q193', [], ExcelValue.by_value
  attach_function 'model_r193', [], ExcelValue.by_value
  attach_function 'model_s193', [], ExcelValue.by_value
  attach_function 'model_t193', [], ExcelValue.by_value
  attach_function 'model_u193', [], ExcelValue.by_value
  attach_function 'model_v193', [], ExcelValue.by_value
  attach_function 'model_w193', [], ExcelValue.by_value
  attach_function 'model_x193', [], ExcelValue.by_value
  attach_function 'model_y193', [], ExcelValue.by_value
  attach_function 'model_z193', [], ExcelValue.by_value
  attach_function 'model_aa193', [], ExcelValue.by_value
  attach_function 'model_ab193', [], ExcelValue.by_value
  attach_function 'model_ac193', [], ExcelValue.by_value
  attach_function 'model_ad193', [], ExcelValue.by_value
  attach_function 'model_ae193', [], ExcelValue.by_value
  attach_function 'model_af193', [], ExcelValue.by_value
  attach_function 'model_ag193', [], ExcelValue.by_value
  attach_function 'model_ah193', [], ExcelValue.by_value
  attach_function 'model_ai193', [], ExcelValue.by_value
  attach_function 'model_aj193', [], ExcelValue.by_value
  attach_function 'model_ak193', [], ExcelValue.by_value
  attach_function 'model_al193', [], ExcelValue.by_value
  attach_function 'model_am193', [], ExcelValue.by_value
  attach_function 'model_an193', [], ExcelValue.by_value
  attach_function 'model_ao193', [], ExcelValue.by_value
  attach_function 'model_c196', [], ExcelValue.by_value
  attach_function 'model_d196', [], ExcelValue.by_value
  attach_function 'model_e196', [], ExcelValue.by_value
  attach_function 'model_f196', [], ExcelValue.by_value
  attach_function 'model_g196', [], ExcelValue.by_value
  attach_function 'model_h196', [], ExcelValue.by_value
  attach_function 'model_i196', [], ExcelValue.by_value
  attach_function 'model_j196', [], ExcelValue.by_value
  attach_function 'model_k196', [], ExcelValue.by_value
  attach_function 'model_l196', [], ExcelValue.by_value
  attach_function 'model_m196', [], ExcelValue.by_value
  attach_function 'model_n196', [], ExcelValue.by_value
  attach_function 'model_o196', [], ExcelValue.by_value
  attach_function 'model_p196', [], ExcelValue.by_value
  attach_function 'model_q196', [], ExcelValue.by_value
  attach_function 'model_r196', [], ExcelValue.by_value
  attach_function 'model_s196', [], ExcelValue.by_value
  attach_function 'model_t196', [], ExcelValue.by_value
  attach_function 'model_u196', [], ExcelValue.by_value
  attach_function 'model_v196', [], ExcelValue.by_value
  attach_function 'model_w196', [], ExcelValue.by_value
  attach_function 'model_x196', [], ExcelValue.by_value
  attach_function 'model_y196', [], ExcelValue.by_value
  attach_function 'model_z196', [], ExcelValue.by_value
  attach_function 'model_aa196', [], ExcelValue.by_value
  attach_function 'model_ab196', [], ExcelValue.by_value
  attach_function 'model_ac196', [], ExcelValue.by_value
  attach_function 'model_ad196', [], ExcelValue.by_value
  attach_function 'model_ae196', [], ExcelValue.by_value
  attach_function 'model_af196', [], ExcelValue.by_value
  attach_function 'model_ag196', [], ExcelValue.by_value
  attach_function 'model_ah196', [], ExcelValue.by_value
  attach_function 'model_ai196', [], ExcelValue.by_value
  attach_function 'model_aj196', [], ExcelValue.by_value
  attach_function 'model_ak196', [], ExcelValue.by_value
  attach_function 'model_al196', [], ExcelValue.by_value
  attach_function 'model_am196', [], ExcelValue.by_value
  attach_function 'model_an196', [], ExcelValue.by_value
  attach_function 'model_ao196', [], ExcelValue.by_value
  attach_function 'model_c195', [], ExcelValue.by_value
  attach_function 'model_d195', [], ExcelValue.by_value
  attach_function 'model_e195', [], ExcelValue.by_value
  attach_function 'model_f195', [], ExcelValue.by_value
  attach_function 'model_g195', [], ExcelValue.by_value
  attach_function 'model_h195', [], ExcelValue.by_value
  attach_function 'model_i195', [], ExcelValue.by_value
  attach_function 'model_j195', [], ExcelValue.by_value
  attach_function 'model_k195', [], ExcelValue.by_value
  attach_function 'model_l195', [], ExcelValue.by_value
  attach_function 'model_m195', [], ExcelValue.by_value
  attach_function 'model_n195', [], ExcelValue.by_value
  attach_function 'model_o195', [], ExcelValue.by_value
  attach_function 'model_p195', [], ExcelValue.by_value
  attach_function 'model_q195', [], ExcelValue.by_value
  attach_function 'model_r195', [], ExcelValue.by_value
  attach_function 'model_s195', [], ExcelValue.by_value
  attach_function 'model_t195', [], ExcelValue.by_value
  attach_function 'model_u195', [], ExcelValue.by_value
  attach_function 'model_v195', [], ExcelValue.by_value
  attach_function 'model_w195', [], ExcelValue.by_value
  attach_function 'model_x195', [], ExcelValue.by_value
  attach_function 'model_y195', [], ExcelValue.by_value
  attach_function 'model_z195', [], ExcelValue.by_value
  attach_function 'model_aa195', [], ExcelValue.by_value
  attach_function 'model_ab195', [], ExcelValue.by_value
  attach_function 'model_ac195', [], ExcelValue.by_value
  attach_function 'model_ad195', [], ExcelValue.by_value
  attach_function 'model_ae195', [], ExcelValue.by_value
  attach_function 'model_af195', [], ExcelValue.by_value
  attach_function 'model_ag195', [], ExcelValue.by_value
  attach_function 'model_ah195', [], ExcelValue.by_value
  attach_function 'model_ai195', [], ExcelValue.by_value
  attach_function 'model_aj195', [], ExcelValue.by_value
  attach_function 'model_ak195', [], ExcelValue.by_value
  attach_function 'model_al195', [], ExcelValue.by_value
  attach_function 'model_am195', [], ExcelValue.by_value
  attach_function 'model_an195', [], ExcelValue.by_value
  attach_function 'model_ao195', [], ExcelValue.by_value
  attach_function 'model_c194', [], ExcelValue.by_value
  attach_function 'model_d194', [], ExcelValue.by_value
  attach_function 'model_e194', [], ExcelValue.by_value
  attach_function 'model_f194', [], ExcelValue.by_value
  attach_function 'model_g194', [], ExcelValue.by_value
  attach_function 'model_h194', [], ExcelValue.by_value
  attach_function 'model_i194', [], ExcelValue.by_value
  attach_function 'model_j194', [], ExcelValue.by_value
  attach_function 'model_k194', [], ExcelValue.by_value
  attach_function 'model_l194', [], ExcelValue.by_value
  attach_function 'model_m194', [], ExcelValue.by_value
  attach_function 'model_n194', [], ExcelValue.by_value
  attach_function 'model_o194', [], ExcelValue.by_value
  attach_function 'model_p194', [], ExcelValue.by_value
  attach_function 'model_q194', [], ExcelValue.by_value
  attach_function 'model_r194', [], ExcelValue.by_value
  attach_function 'model_s194', [], ExcelValue.by_value
  attach_function 'model_t194', [], ExcelValue.by_value
  attach_function 'model_u194', [], ExcelValue.by_value
  attach_function 'model_v194', [], ExcelValue.by_value
  attach_function 'model_w194', [], ExcelValue.by_value
  attach_function 'model_x194', [], ExcelValue.by_value
  attach_function 'model_y194', [], ExcelValue.by_value
  attach_function 'model_z194', [], ExcelValue.by_value
  attach_function 'model_aa194', [], ExcelValue.by_value
  attach_function 'model_ab194', [], ExcelValue.by_value
  attach_function 'model_ac194', [], ExcelValue.by_value
  attach_function 'model_ad194', [], ExcelValue.by_value
  attach_function 'model_ae194', [], ExcelValue.by_value
  attach_function 'model_af194', [], ExcelValue.by_value
  attach_function 'model_ag194', [], ExcelValue.by_value
  attach_function 'model_ah194', [], ExcelValue.by_value
  attach_function 'model_ai194', [], ExcelValue.by_value
  attach_function 'model_aj194', [], ExcelValue.by_value
  attach_function 'model_ak194', [], ExcelValue.by_value
  attach_function 'model_al194', [], ExcelValue.by_value
  attach_function 'model_am194', [], ExcelValue.by_value
  attach_function 'model_an194', [], ExcelValue.by_value
  attach_function 'model_ao194', [], ExcelValue.by_value
  attach_function 'model_c197', [], ExcelValue.by_value
  attach_function 'model_d197', [], ExcelValue.by_value
  attach_function 'model_e197', [], ExcelValue.by_value
  attach_function 'model_f197', [], ExcelValue.by_value
  attach_function 'model_g197', [], ExcelValue.by_value
  attach_function 'model_h197', [], ExcelValue.by_value
  attach_function 'model_i197', [], ExcelValue.by_value
  attach_function 'model_j197', [], ExcelValue.by_value
  attach_function 'model_k197', [], ExcelValue.by_value
  attach_function 'model_l197', [], ExcelValue.by_value
  attach_function 'model_m197', [], ExcelValue.by_value
  attach_function 'model_n197', [], ExcelValue.by_value
  attach_function 'model_o197', [], ExcelValue.by_value
  attach_function 'model_p197', [], ExcelValue.by_value
  attach_function 'model_q197', [], ExcelValue.by_value
  attach_function 'model_r197', [], ExcelValue.by_value
  attach_function 'model_s197', [], ExcelValue.by_value
  attach_function 'model_t197', [], ExcelValue.by_value
  attach_function 'model_u197', [], ExcelValue.by_value
  attach_function 'model_v197', [], ExcelValue.by_value
  attach_function 'model_w197', [], ExcelValue.by_value
  attach_function 'model_x197', [], ExcelValue.by_value
  attach_function 'model_y197', [], ExcelValue.by_value
  attach_function 'model_z197', [], ExcelValue.by_value
  attach_function 'model_aa197', [], ExcelValue.by_value
  attach_function 'model_ab197', [], ExcelValue.by_value
  attach_function 'model_ac197', [], ExcelValue.by_value
  attach_function 'model_ad197', [], ExcelValue.by_value
  attach_function 'model_ae197', [], ExcelValue.by_value
  attach_function 'model_af197', [], ExcelValue.by_value
  attach_function 'model_ag197', [], ExcelValue.by_value
  attach_function 'model_ah197', [], ExcelValue.by_value
  attach_function 'model_ai197', [], ExcelValue.by_value
  attach_function 'model_aj197', [], ExcelValue.by_value
  attach_function 'model_ak197', [], ExcelValue.by_value
  attach_function 'model_al197', [], ExcelValue.by_value
  attach_function 'model_am197', [], ExcelValue.by_value
  attach_function 'model_an197', [], ExcelValue.by_value
  attach_function 'model_ao197', [], ExcelValue.by_value
  attach_function 'model_p20', [], ExcelValue.by_value
  attach_function 'model_c113', [], ExcelValue.by_value
  attach_function 'model_c23', [], ExcelValue.by_value
  attach_function 'model_c33', [], ExcelValue.by_value
  attach_function 'model_c51', [], ExcelValue.by_value
  # end of Model

  # start of Charts
  # end of Charts

  # start of List of named references
  # end of List of named references
  # Start of named references
  attach_function 'n_2012_onwards_electricity_demand_growth_rate', [], ExcelValue.by_value
  attach_function 'n_2020_fossil_fuel_emissions_factor', [], ExcelValue.by_value
  attach_function 'n_2020_non_renewable_low_carbon_generation_i_e_nuclear_ccs', [], ExcelValue.by_value
  attach_function 'n_2020_renewables_target', [], ExcelValue.by_value
  attach_function 'n_2020_renewables_target_gco2_kwh', [], ExcelValue.by_value
  attach_function 'n_2020_renewables_target_twh', [], ExcelValue.by_value
  attach_function 'n_2030_cost_of_carbon', [], ExcelValue.by_value
  attach_function 'n_2030_cost_of_fossil_fuel', [], ExcelValue.by_value
  attach_function 'n_2030_decarbonisation_level', [], ExcelValue.by_value
  attach_function 'n_2050_cost_of_carbon', [], ExcelValue.by_value
  attach_function 'n_2050_cost_of_fossil_fuel', [], ExcelValue.by_value
  attach_function 'n_2050_electricity_demand', [], ExcelValue.by_value
  attach_function 'n_2050_emissions_electricity', [], ExcelValue.by_value
  attach_function 'n_2050_emissions_industry', [], ExcelValue.by_value
  attach_function 'n_2050_emissions_total', [], ExcelValue.by_value
  attach_function 'n_2050_fossil_fuel_emissions_factor', [], ExcelValue.by_value
  attach_function 'n_2050_maximum_electricity_demand', [], ExcelValue.by_value
  attach_function 'n_2050_minimum_electricity_demand', [], ExcelValue.by_value
  attach_function 'annual_change_in_non_electricity_traded_emissions', [], ExcelValue.by_value
  attach_function 'annual_change_in_non_electricity_traded_emissions_after_radical_change', [], ExcelValue.by_value
  attach_function 'annual_reduction_in_cost_of_high_carbon_generation', [], ExcelValue.by_value
  attach_function 'annual_reduction_in_cost_of_intermittent_generation', [], ExcelValue.by_value
  attach_function 'annual_reduction_in_cost_of_other_low_carbon_generation', [], ExcelValue.by_value
  attach_function 'average_life_high_carbon', [], ExcelValue.by_value
  attach_function 'average_life_other_low_carbon', [], ExcelValue.by_value
  attach_function 'average_life_wind', [], ExcelValue.by_value
  attach_function 'baseload_demand', [], ExcelValue.by_value
  attach_function 'build_rate_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'build_rate_from_now_to_2020', [], ExcelValue.by_value
  attach_function 'build_rate_high_carbon', [], ExcelValue.by_value
  attach_function 'build_rate_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'build_rate_target_in_second_build', [], ExcelValue.by_value
  attach_function 'build_rate_total_low_carbon', [], ExcelValue.by_value
  attach_function 'capacity_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'capacity_high_carbon', [], ExcelValue.by_value
  attach_function 'capacity_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'capacity_total', [], ExcelValue.by_value
  attach_function 'capacity_total_low_carbon', [], ExcelValue.by_value
  attach_function 'cb2_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb2_scenario', [], ExcelValue.by_value
  attach_function 'cb2_traded_cap', [], ExcelValue.by_value
  attach_function 'cb3_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb3_scenario', [], ExcelValue.by_value
  attach_function 'cb3_traded_cap', [], ExcelValue.by_value
  attach_function 'cb4_current_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb4_current_scenario', [], ExcelValue.by_value
  attach_function 'cb4_current_traded_cap', [], ExcelValue.by_value
  attach_function 'cb4_revised_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb4_revised_scenario', [], ExcelValue.by_value
  attach_function 'cb4_revised_traded_cap', [], ExcelValue.by_value
  attach_function 'emissions_electicity', [], ExcelValue.by_value
  attach_function 'emissions_factor', [], ExcelValue.by_value
  attach_function 'emissions_non_electricity_traded', [], ExcelValue.by_value
  attach_function 'emissions_total_traded', [], ExcelValue.by_value
  attach_function 'emissions_uk_share_of_eu_ets_cap_alternative', [], ExcelValue.by_value
  attach_function 'emissions_uk_share_of_eu_ets_cap_current', [], ExcelValue.by_value
  attach_function 'energy_output_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'energy_output_high_carbon', [], ExcelValue.by_value
  attach_function 'energy_output_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'energy_output_total_low_carbon', [], ExcelValue.by_value
  attach_function 'gw_per_twh', [], ExcelValue.by_value
  attach_function 'load_factor_average_low_carbon', [], ExcelValue.by_value
  attach_function 'load_factor_demand', [], ExcelValue.by_value
  attach_function 'load_factor_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'load_factor_high_carbon', [], ExcelValue.by_value
  attach_function 'load_factor_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'maximum_industry_contraction', [], ExcelValue.by_value
  attach_function 'maximum_industry_expansion', [], ExcelValue.by_value
  attach_function 'mean_demand', [], ExcelValue.by_value
  attach_function 'minimum_build_rate', [], ExcelValue.by_value
  attach_function 'peak_demand', [], ExcelValue.by_value
  attach_function 'proportion_of_build_rate_to_2020_that_is_wind_rest_is_bio', [], ExcelValue.by_value
  attach_function 'proportion_of_second_build_that_is_wind', [], ExcelValue.by_value
  attach_function 'total_costs_capital', [], ExcelValue.by_value
  attach_function 'total_costs_carbon', [], ExcelValue.by_value
  attach_function 'total_costs_fuel', [], ExcelValue.by_value
  attach_function 'total_costs_operating', [], ExcelValue.by_value
  attach_function 'total_costs_total', [], ExcelValue.by_value
  attach_function 'total_system_cost', [], ExcelValue.by_value
  attach_function 'twh_per_gw', [], ExcelValue.by_value
  attach_function 'year_electricity_demand_starts_to_increase', [], ExcelValue.by_value
  attach_function 'year_second_wave_of_building_starts', [], ExcelValue.by_value
  attach_function 'year_start_to_see_radical_change_in_non_traded_emissions', [], ExcelValue.by_value
  attach_function 'set_n_2012_onwards_electricity_demand_growth_rate', [ExcelValue.by_value], :void
  attach_function 'set_n_2020_fossil_fuel_emissions_factor', [ExcelValue.by_value], :void
  attach_function 'set_n_2020_non_renewable_low_carbon_generation_i_e_nuclear_ccs', [ExcelValue.by_value], :void
  attach_function 'set_n_2030_cost_of_carbon', [ExcelValue.by_value], :void
  attach_function 'set_n_2030_cost_of_fossil_fuel', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_cost_of_carbon', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_cost_of_fossil_fuel', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_electricity_demand', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_fossil_fuel_emissions_factor', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_maximum_electricity_demand', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_minimum_electricity_demand', [ExcelValue.by_value], :void
  attach_function 'set_annual_change_in_non_electricity_traded_emissions', [ExcelValue.by_value], :void
  attach_function 'set_annual_change_in_non_electricity_traded_emissions_after_radical_change', [ExcelValue.by_value], :void
  attach_function 'set_annual_reduction_in_cost_of_high_carbon_generation', [ExcelValue.by_value], :void
  attach_function 'set_annual_reduction_in_cost_of_intermittent_generation', [ExcelValue.by_value], :void
  attach_function 'set_annual_reduction_in_cost_of_other_low_carbon_generation', [ExcelValue.by_value], :void
  attach_function 'set_average_life_high_carbon', [ExcelValue.by_value], :void
  attach_function 'set_average_life_other_low_carbon', [ExcelValue.by_value], :void
  attach_function 'set_average_life_wind', [ExcelValue.by_value], :void
  attach_function 'set_build_rate_from_now_to_2020', [ExcelValue.by_value], :void
  attach_function 'set_build_rate_target_in_second_build', [ExcelValue.by_value], :void
  attach_function 'set_cb2_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_cb3_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_cb4_current_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_cb4_revised_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_maximum_industry_contraction', [ExcelValue.by_value], :void
  attach_function 'set_maximum_industry_expansion', [ExcelValue.by_value], :void
  attach_function 'set_minimum_build_rate', [ExcelValue.by_value], :void
  attach_function 'set_proportion_of_build_rate_to_2020_that_is_wind_rest_is_bio', [ExcelValue.by_value], :void
  attach_function 'set_proportion_of_second_build_that_is_wind', [ExcelValue.by_value], :void
  attach_function 'set_year_electricity_demand_starts_to_increase', [ExcelValue.by_value], :void
  attach_function 'set_year_second_wave_of_building_starts', [ExcelValue.by_value], :void
  attach_function 'set_year_start_to_see_radical_change_in_non_traded_emissions', [ExcelValue.by_value], :void
  # End of named references
end
