require 'ffi'
require 'singleton'

class ModelShim

  # WARNING: this is not thread safe
  def initialize
    reset
  end

  def reset
    Model.reset
  end

  def method_missing(name, *arguments)
    if arguments.size == 0
      get(name)
    elsif arguments.size == 1
      set(name, arguments.first)
    else
      super
    end 
  end

  def get(name)
    return 0 unless Model.respond_to?(name)
    ruby_value_from_excel_value(Model.send(name))
  end

  def ruby_value_from_excel_value(excel_value)
    case excel_value[:type]
    when :ExcelNumber; excel_value[:number]
    when :ExcelString; excel_value[:string].read_string.force_encoding("utf-8")
    when :ExcelBoolean; excel_value[:number] == 1
    when :ExcelEmpty; nil
    when :ExcelRange
      r = excel_value[:rows]
      c = excel_value[:columns]
      p = excel_value[:array]
      s = Model::ExcelValue.size
      a = Array.new(r) { Array.new(c) }
      (0...r).each do |row|
        (0...c).each do |column|
          a[row][column] = ruby_value_from_excel_value(Model::ExcelValue.new(p + (((row*c)+column)*s)))
        end
      end 
      return a
    when :ExcelError; [:value,:name,:div0,:ref,:na][excel_value[:number]]
    else
      raise Exception.new("ExcelValue type #{excel_value[:type].inspect} not recognised")
    end
  end

  def set(name, ruby_value)
    name = name.to_s
    name = "set_#{name[0..-2]}" if name.end_with?('=')
    return false unless Model.respond_to?(name)
    Model.send(name, excel_value_from_ruby_value(ruby_value))
  end

  def excel_value_from_ruby_value(ruby_value, excel_value = Model::ExcelValue.new)
    case ruby_value
    when Numeric
      excel_value[:type] = :ExcelNumber
      excel_value[:number] = ruby_value
    when String
      excel_value[:type] = :ExcelString
      excel_value[:string] = FFI::MemoryPointer.from_string(ruby_value.encode('utf-8'))
    when TrueClass, FalseClass
      excel_value[:type] = :ExcelBoolean
      excel_value[:number] = ruby_value ? 1 : 0
    when nil
      excel_value[:type] = :ExcelEmpty
    when Array
      excel_value[:type] = :ExcelRange
      # Presumed to be a row unless specified otherwise
      if ruby_value.first.is_a?(Array)
        excel_value[:rows] = ruby_value.size
        excel_value[:columns] = ruby_value.first.size
      else
        excel_value[:rows] = 1
        excel_value[:columns] = ruby_value.size
      end
      ruby_values = ruby_value.flatten
      pointer = FFI::MemoryPointer.new(Model::ExcelValue, ruby_values.size)
      excel_value[:array] = pointer
      ruby_values.each.with_index do |v,i|
        excel_value_from_ruby_value(v, Model::ExcelValue.new(pointer[i]))
      end
    when Symbol
      excel_value[:type] = :ExcelError
      excel_value[:number] = [:value, :name, :div0, :ref, :na].index(ruby_value)
    else
      raise Exception.new("Ruby value #{ruby_value.inspect} not translatable into excel")
    end
    excel_value
  end

end
    

module Model
  extend FFI::Library
  ffi_lib  File.join(File.dirname(__FILE__),FFI.map_library_name('model'))
  ExcelType = enum :ExcelEmpty, :ExcelNumber, :ExcelString, :ExcelBoolean, :ExcelError, :ExcelRange
                
  class ExcelValue < FFI::Struct
    layout :type, ExcelType,
  	       :number, :double,
  	       :string, :pointer,
         	 :array, :pointer,
           :rows, :int,
           :columns, :int             
  end
  

  # use this function to reset all cell values
  attach_function 'reset', [], :void

  # start of Model
  attach_function 'set_model_c22', [ExcelValue.by_value], :void
  attach_function 'set_model_c46', [ExcelValue.by_value], :void
  attach_function 'set_model_c31', [ExcelValue.by_value], :void
  attach_function 'set_model_c24', [ExcelValue.by_value], :void
  attach_function 'set_model_c47', [ExcelValue.by_value], :void
  attach_function 'set_model_c26', [ExcelValue.by_value], :void
  attach_function 'set_model_c25', [ExcelValue.by_value], :void
  attach_function 'set_model_c48', [ExcelValue.by_value], :void
  attach_function 'set_model_c43', [ExcelValue.by_value], :void
  attach_function 'set_model_c42', [ExcelValue.by_value], :void
  attach_function 'set_model_c41', [ExcelValue.by_value], :void
  attach_function 'set_model_c29', [ExcelValue.by_value], :void
  attach_function 'set_model_c34', [ExcelValue.by_value], :void
  attach_function 'set_model_p31', [ExcelValue.by_value], :void
  attach_function 'set_model_p32', [ExcelValue.by_value], :void
  attach_function 'set_model_p33', [ExcelValue.by_value], :void
  attach_function 'set_model_p34', [ExcelValue.by_value], :void
  attach_function 'set_model_c39', [ExcelValue.by_value], :void
  attach_function 'set_model_c38', [ExcelValue.by_value], :void
  attach_function 'set_model_c37', [ExcelValue.by_value], :void
  attach_function 'set_model_c30', [ExcelValue.by_value], :void
  attach_function 'set_model_c35', [ExcelValue.by_value], :void
  attach_function 'set_model_c23', [ExcelValue.by_value], :void
  attach_function 'set_model_c33', [ExcelValue.by_value], :void
  attach_function 'model_c22', [], ExcelValue.by_value
  attach_function 'model_c46', [], ExcelValue.by_value
  attach_function 'model_c31', [], ExcelValue.by_value
  attach_function 'model_p24', [], ExcelValue.by_value
  attach_function 'model_p25', [], ExcelValue.by_value
  attach_function 'model_p23', [], ExcelValue.by_value
  attach_function 'model_p28', [], ExcelValue.by_value
  attach_function 'model_c24', [], ExcelValue.by_value
  attach_function 'model_p37', [], ExcelValue.by_value
  attach_function 'model_p38', [], ExcelValue.by_value
  attach_function 'model_p39', [], ExcelValue.by_value
  attach_function 'model_c47', [], ExcelValue.by_value
  attach_function 'model_c26', [], ExcelValue.by_value
  attach_function 'model_c25', [], ExcelValue.by_value
  attach_function 'model_c48', [], ExcelValue.by_value
  attach_function 'model_c43', [], ExcelValue.by_value
  attach_function 'model_c42', [], ExcelValue.by_value
  attach_function 'model_c41', [], ExcelValue.by_value
  attach_function 'model_c119', [], ExcelValue.by_value
  attach_function 'model_d119', [], ExcelValue.by_value
  attach_function 'model_e119', [], ExcelValue.by_value
  attach_function 'model_f119', [], ExcelValue.by_value
  attach_function 'model_g119', [], ExcelValue.by_value
  attach_function 'model_h119', [], ExcelValue.by_value
  attach_function 'model_i119', [], ExcelValue.by_value
  attach_function 'model_j119', [], ExcelValue.by_value
  attach_function 'model_k119', [], ExcelValue.by_value
  attach_function 'model_l119', [], ExcelValue.by_value
  attach_function 'model_m119', [], ExcelValue.by_value
  attach_function 'model_n119', [], ExcelValue.by_value
  attach_function 'model_o119', [], ExcelValue.by_value
  attach_function 'model_p119', [], ExcelValue.by_value
  attach_function 'model_q119', [], ExcelValue.by_value
  attach_function 'model_r119', [], ExcelValue.by_value
  attach_function 'model_s119', [], ExcelValue.by_value
  attach_function 'model_t119', [], ExcelValue.by_value
  attach_function 'model_u119', [], ExcelValue.by_value
  attach_function 'model_v119', [], ExcelValue.by_value
  attach_function 'model_w119', [], ExcelValue.by_value
  attach_function 'model_x119', [], ExcelValue.by_value
  attach_function 'model_y119', [], ExcelValue.by_value
  attach_function 'model_z119', [], ExcelValue.by_value
  attach_function 'model_aa119', [], ExcelValue.by_value
  attach_function 'model_ab119', [], ExcelValue.by_value
  attach_function 'model_ac119', [], ExcelValue.by_value
  attach_function 'model_ad119', [], ExcelValue.by_value
  attach_function 'model_ae119', [], ExcelValue.by_value
  attach_function 'model_af119', [], ExcelValue.by_value
  attach_function 'model_ag119', [], ExcelValue.by_value
  attach_function 'model_ah119', [], ExcelValue.by_value
  attach_function 'model_ai119', [], ExcelValue.by_value
  attach_function 'model_aj119', [], ExcelValue.by_value
  attach_function 'model_ak119', [], ExcelValue.by_value
  attach_function 'model_al119', [], ExcelValue.by_value
  attach_function 'model_am119', [], ExcelValue.by_value
  attach_function 'model_an119', [], ExcelValue.by_value
  attach_function 'model_ao119', [], ExcelValue.by_value
  attach_function 'model_c108', [], ExcelValue.by_value
  attach_function 'model_d108', [], ExcelValue.by_value
  attach_function 'model_e108', [], ExcelValue.by_value
  attach_function 'model_f108', [], ExcelValue.by_value
  attach_function 'model_g108', [], ExcelValue.by_value
  attach_function 'model_h108', [], ExcelValue.by_value
  attach_function 'model_i108', [], ExcelValue.by_value
  attach_function 'model_j108', [], ExcelValue.by_value
  attach_function 'model_k108', [], ExcelValue.by_value
  attach_function 'model_l108', [], ExcelValue.by_value
  attach_function 'model_m108', [], ExcelValue.by_value
  attach_function 'model_n108', [], ExcelValue.by_value
  attach_function 'model_o108', [], ExcelValue.by_value
  attach_function 'model_p108', [], ExcelValue.by_value
  attach_function 'model_q108', [], ExcelValue.by_value
  attach_function 'model_r108', [], ExcelValue.by_value
  attach_function 'model_s108', [], ExcelValue.by_value
  attach_function 'model_t108', [], ExcelValue.by_value
  attach_function 'model_u108', [], ExcelValue.by_value
  attach_function 'model_v108', [], ExcelValue.by_value
  attach_function 'model_w108', [], ExcelValue.by_value
  attach_function 'model_x108', [], ExcelValue.by_value
  attach_function 'model_y108', [], ExcelValue.by_value
  attach_function 'model_z108', [], ExcelValue.by_value
  attach_function 'model_aa108', [], ExcelValue.by_value
  attach_function 'model_ab108', [], ExcelValue.by_value
  attach_function 'model_ac108', [], ExcelValue.by_value
  attach_function 'model_ad108', [], ExcelValue.by_value
  attach_function 'model_ae108', [], ExcelValue.by_value
  attach_function 'model_af108', [], ExcelValue.by_value
  attach_function 'model_ag108', [], ExcelValue.by_value
  attach_function 'model_ah108', [], ExcelValue.by_value
  attach_function 'model_ai108', [], ExcelValue.by_value
  attach_function 'model_aj108', [], ExcelValue.by_value
  attach_function 'model_ak108', [], ExcelValue.by_value
  attach_function 'model_al108', [], ExcelValue.by_value
  attach_function 'model_am108', [], ExcelValue.by_value
  attach_function 'model_an108', [], ExcelValue.by_value
  attach_function 'model_ao108', [], ExcelValue.by_value
  attach_function 'model_c29', [], ExcelValue.by_value
  attach_function 'model_c110', [], ExcelValue.by_value
  attach_function 'model_d110', [], ExcelValue.by_value
  attach_function 'model_e110', [], ExcelValue.by_value
  attach_function 'model_f110', [], ExcelValue.by_value
  attach_function 'model_g110', [], ExcelValue.by_value
  attach_function 'model_h110', [], ExcelValue.by_value
  attach_function 'model_i110', [], ExcelValue.by_value
  attach_function 'model_j110', [], ExcelValue.by_value
  attach_function 'model_k110', [], ExcelValue.by_value
  attach_function 'model_l110', [], ExcelValue.by_value
  attach_function 'model_m110', [], ExcelValue.by_value
  attach_function 'model_n110', [], ExcelValue.by_value
  attach_function 'model_o110', [], ExcelValue.by_value
  attach_function 'model_p110', [], ExcelValue.by_value
  attach_function 'model_q110', [], ExcelValue.by_value
  attach_function 'model_r110', [], ExcelValue.by_value
  attach_function 'model_s110', [], ExcelValue.by_value
  attach_function 'model_t110', [], ExcelValue.by_value
  attach_function 'model_u110', [], ExcelValue.by_value
  attach_function 'model_v110', [], ExcelValue.by_value
  attach_function 'model_w110', [], ExcelValue.by_value
  attach_function 'model_x110', [], ExcelValue.by_value
  attach_function 'model_y110', [], ExcelValue.by_value
  attach_function 'model_z110', [], ExcelValue.by_value
  attach_function 'model_aa110', [], ExcelValue.by_value
  attach_function 'model_ab110', [], ExcelValue.by_value
  attach_function 'model_ac110', [], ExcelValue.by_value
  attach_function 'model_ad110', [], ExcelValue.by_value
  attach_function 'model_ae110', [], ExcelValue.by_value
  attach_function 'model_af110', [], ExcelValue.by_value
  attach_function 'model_ag110', [], ExcelValue.by_value
  attach_function 'model_ah110', [], ExcelValue.by_value
  attach_function 'model_ai110', [], ExcelValue.by_value
  attach_function 'model_aj110', [], ExcelValue.by_value
  attach_function 'model_ak110', [], ExcelValue.by_value
  attach_function 'model_al110', [], ExcelValue.by_value
  attach_function 'model_am110', [], ExcelValue.by_value
  attach_function 'model_an110', [], ExcelValue.by_value
  attach_function 'model_ao110', [], ExcelValue.by_value
  attach_function 'model_c107', [], ExcelValue.by_value
  attach_function 'model_d107', [], ExcelValue.by_value
  attach_function 'model_e107', [], ExcelValue.by_value
  attach_function 'model_f107', [], ExcelValue.by_value
  attach_function 'model_g107', [], ExcelValue.by_value
  attach_function 'model_h107', [], ExcelValue.by_value
  attach_function 'model_i107', [], ExcelValue.by_value
  attach_function 'model_j107', [], ExcelValue.by_value
  attach_function 'model_k107', [], ExcelValue.by_value
  attach_function 'model_l107', [], ExcelValue.by_value
  attach_function 'model_m107', [], ExcelValue.by_value
  attach_function 'model_n107', [], ExcelValue.by_value
  attach_function 'model_o107', [], ExcelValue.by_value
  attach_function 'model_p107', [], ExcelValue.by_value
  attach_function 'model_q107', [], ExcelValue.by_value
  attach_function 'model_r107', [], ExcelValue.by_value
  attach_function 'model_s107', [], ExcelValue.by_value
  attach_function 'model_t107', [], ExcelValue.by_value
  attach_function 'model_u107', [], ExcelValue.by_value
  attach_function 'model_v107', [], ExcelValue.by_value
  attach_function 'model_w107', [], ExcelValue.by_value
  attach_function 'model_x107', [], ExcelValue.by_value
  attach_function 'model_y107', [], ExcelValue.by_value
  attach_function 'model_z107', [], ExcelValue.by_value
  attach_function 'model_aa107', [], ExcelValue.by_value
  attach_function 'model_ab107', [], ExcelValue.by_value
  attach_function 'model_ac107', [], ExcelValue.by_value
  attach_function 'model_ad107', [], ExcelValue.by_value
  attach_function 'model_ae107', [], ExcelValue.by_value
  attach_function 'model_af107', [], ExcelValue.by_value
  attach_function 'model_ag107', [], ExcelValue.by_value
  attach_function 'model_ah107', [], ExcelValue.by_value
  attach_function 'model_ai107', [], ExcelValue.by_value
  attach_function 'model_aj107', [], ExcelValue.by_value
  attach_function 'model_ak107', [], ExcelValue.by_value
  attach_function 'model_al107', [], ExcelValue.by_value
  attach_function 'model_am107', [], ExcelValue.by_value
  attach_function 'model_an107', [], ExcelValue.by_value
  attach_function 'model_ao107', [], ExcelValue.by_value
  attach_function 'model_c34', [], ExcelValue.by_value
  attach_function 'model_c109', [], ExcelValue.by_value
  attach_function 'model_d109', [], ExcelValue.by_value
  attach_function 'model_e109', [], ExcelValue.by_value
  attach_function 'model_f109', [], ExcelValue.by_value
  attach_function 'model_g109', [], ExcelValue.by_value
  attach_function 'model_h109', [], ExcelValue.by_value
  attach_function 'model_i109', [], ExcelValue.by_value
  attach_function 'model_j109', [], ExcelValue.by_value
  attach_function 'model_k109', [], ExcelValue.by_value
  attach_function 'model_l109', [], ExcelValue.by_value
  attach_function 'model_m109', [], ExcelValue.by_value
  attach_function 'model_n109', [], ExcelValue.by_value
  attach_function 'model_o109', [], ExcelValue.by_value
  attach_function 'model_p109', [], ExcelValue.by_value
  attach_function 'model_q109', [], ExcelValue.by_value
  attach_function 'model_r109', [], ExcelValue.by_value
  attach_function 'model_s109', [], ExcelValue.by_value
  attach_function 'model_t109', [], ExcelValue.by_value
  attach_function 'model_u109', [], ExcelValue.by_value
  attach_function 'model_v109', [], ExcelValue.by_value
  attach_function 'model_w109', [], ExcelValue.by_value
  attach_function 'model_x109', [], ExcelValue.by_value
  attach_function 'model_y109', [], ExcelValue.by_value
  attach_function 'model_z109', [], ExcelValue.by_value
  attach_function 'model_aa109', [], ExcelValue.by_value
  attach_function 'model_ab109', [], ExcelValue.by_value
  attach_function 'model_ac109', [], ExcelValue.by_value
  attach_function 'model_ad109', [], ExcelValue.by_value
  attach_function 'model_ae109', [], ExcelValue.by_value
  attach_function 'model_af109', [], ExcelValue.by_value
  attach_function 'model_ag109', [], ExcelValue.by_value
  attach_function 'model_ah109', [], ExcelValue.by_value
  attach_function 'model_ai109', [], ExcelValue.by_value
  attach_function 'model_aj109', [], ExcelValue.by_value
  attach_function 'model_ak109', [], ExcelValue.by_value
  attach_function 'model_al109', [], ExcelValue.by_value
  attach_function 'model_am109', [], ExcelValue.by_value
  attach_function 'model_an109', [], ExcelValue.by_value
  attach_function 'model_ao109', [], ExcelValue.by_value
  attach_function 'model_c114', [], ExcelValue.by_value
  attach_function 'model_d114', [], ExcelValue.by_value
  attach_function 'model_e114', [], ExcelValue.by_value
  attach_function 'model_f114', [], ExcelValue.by_value
  attach_function 'model_g114', [], ExcelValue.by_value
  attach_function 'model_h114', [], ExcelValue.by_value
  attach_function 'model_i114', [], ExcelValue.by_value
  attach_function 'model_j114', [], ExcelValue.by_value
  attach_function 'model_k114', [], ExcelValue.by_value
  attach_function 'model_l114', [], ExcelValue.by_value
  attach_function 'model_m114', [], ExcelValue.by_value
  attach_function 'model_n114', [], ExcelValue.by_value
  attach_function 'model_o114', [], ExcelValue.by_value
  attach_function 'model_p114', [], ExcelValue.by_value
  attach_function 'model_q114', [], ExcelValue.by_value
  attach_function 'model_r114', [], ExcelValue.by_value
  attach_function 'model_s114', [], ExcelValue.by_value
  attach_function 'model_t114', [], ExcelValue.by_value
  attach_function 'model_u114', [], ExcelValue.by_value
  attach_function 'model_v114', [], ExcelValue.by_value
  attach_function 'model_w114', [], ExcelValue.by_value
  attach_function 'model_x114', [], ExcelValue.by_value
  attach_function 'model_y114', [], ExcelValue.by_value
  attach_function 'model_z114', [], ExcelValue.by_value
  attach_function 'model_aa114', [], ExcelValue.by_value
  attach_function 'model_ab114', [], ExcelValue.by_value
  attach_function 'model_ac114', [], ExcelValue.by_value
  attach_function 'model_ad114', [], ExcelValue.by_value
  attach_function 'model_ae114', [], ExcelValue.by_value
  attach_function 'model_af114', [], ExcelValue.by_value
  attach_function 'model_ag114', [], ExcelValue.by_value
  attach_function 'model_ah114', [], ExcelValue.by_value
  attach_function 'model_ai114', [], ExcelValue.by_value
  attach_function 'model_aj114', [], ExcelValue.by_value
  attach_function 'model_ak114', [], ExcelValue.by_value
  attach_function 'model_al114', [], ExcelValue.by_value
  attach_function 'model_am114', [], ExcelValue.by_value
  attach_function 'model_an114', [], ExcelValue.by_value
  attach_function 'model_ao114', [], ExcelValue.by_value
  attach_function 'model_c116', [], ExcelValue.by_value
  attach_function 'model_d116', [], ExcelValue.by_value
  attach_function 'model_e116', [], ExcelValue.by_value
  attach_function 'model_f116', [], ExcelValue.by_value
  attach_function 'model_g116', [], ExcelValue.by_value
  attach_function 'model_h116', [], ExcelValue.by_value
  attach_function 'model_i116', [], ExcelValue.by_value
  attach_function 'model_j116', [], ExcelValue.by_value
  attach_function 'model_k116', [], ExcelValue.by_value
  attach_function 'model_l116', [], ExcelValue.by_value
  attach_function 'model_m116', [], ExcelValue.by_value
  attach_function 'model_n116', [], ExcelValue.by_value
  attach_function 'model_o116', [], ExcelValue.by_value
  attach_function 'model_p116', [], ExcelValue.by_value
  attach_function 'model_q116', [], ExcelValue.by_value
  attach_function 'model_r116', [], ExcelValue.by_value
  attach_function 'model_s116', [], ExcelValue.by_value
  attach_function 'model_t116', [], ExcelValue.by_value
  attach_function 'model_u116', [], ExcelValue.by_value
  attach_function 'model_v116', [], ExcelValue.by_value
  attach_function 'model_w116', [], ExcelValue.by_value
  attach_function 'model_x116', [], ExcelValue.by_value
  attach_function 'model_y116', [], ExcelValue.by_value
  attach_function 'model_z116', [], ExcelValue.by_value
  attach_function 'model_aa116', [], ExcelValue.by_value
  attach_function 'model_ab116', [], ExcelValue.by_value
  attach_function 'model_ac116', [], ExcelValue.by_value
  attach_function 'model_ad116', [], ExcelValue.by_value
  attach_function 'model_ae116', [], ExcelValue.by_value
  attach_function 'model_af116', [], ExcelValue.by_value
  attach_function 'model_ag116', [], ExcelValue.by_value
  attach_function 'model_ah116', [], ExcelValue.by_value
  attach_function 'model_ai116', [], ExcelValue.by_value
  attach_function 'model_aj116', [], ExcelValue.by_value
  attach_function 'model_ak116', [], ExcelValue.by_value
  attach_function 'model_al116', [], ExcelValue.by_value
  attach_function 'model_am116', [], ExcelValue.by_value
  attach_function 'model_an116', [], ExcelValue.by_value
  attach_function 'model_ao116', [], ExcelValue.by_value
  attach_function 'model_c113', [], ExcelValue.by_value
  attach_function 'model_d113', [], ExcelValue.by_value
  attach_function 'model_e113', [], ExcelValue.by_value
  attach_function 'model_f113', [], ExcelValue.by_value
  attach_function 'model_g113', [], ExcelValue.by_value
  attach_function 'model_h113', [], ExcelValue.by_value
  attach_function 'model_i113', [], ExcelValue.by_value
  attach_function 'model_j113', [], ExcelValue.by_value
  attach_function 'model_k113', [], ExcelValue.by_value
  attach_function 'model_l113', [], ExcelValue.by_value
  attach_function 'model_m113', [], ExcelValue.by_value
  attach_function 'model_n113', [], ExcelValue.by_value
  attach_function 'model_o113', [], ExcelValue.by_value
  attach_function 'model_p113', [], ExcelValue.by_value
  attach_function 'model_q113', [], ExcelValue.by_value
  attach_function 'model_r113', [], ExcelValue.by_value
  attach_function 'model_s113', [], ExcelValue.by_value
  attach_function 'model_t113', [], ExcelValue.by_value
  attach_function 'model_u113', [], ExcelValue.by_value
  attach_function 'model_v113', [], ExcelValue.by_value
  attach_function 'model_w113', [], ExcelValue.by_value
  attach_function 'model_x113', [], ExcelValue.by_value
  attach_function 'model_y113', [], ExcelValue.by_value
  attach_function 'model_z113', [], ExcelValue.by_value
  attach_function 'model_aa113', [], ExcelValue.by_value
  attach_function 'model_ab113', [], ExcelValue.by_value
  attach_function 'model_ac113', [], ExcelValue.by_value
  attach_function 'model_ad113', [], ExcelValue.by_value
  attach_function 'model_ae113', [], ExcelValue.by_value
  attach_function 'model_af113', [], ExcelValue.by_value
  attach_function 'model_ag113', [], ExcelValue.by_value
  attach_function 'model_ah113', [], ExcelValue.by_value
  attach_function 'model_ai113', [], ExcelValue.by_value
  attach_function 'model_aj113', [], ExcelValue.by_value
  attach_function 'model_ak113', [], ExcelValue.by_value
  attach_function 'model_al113', [], ExcelValue.by_value
  attach_function 'model_am113', [], ExcelValue.by_value
  attach_function 'model_an113', [], ExcelValue.by_value
  attach_function 'model_ao113', [], ExcelValue.by_value
  attach_function 'model_c117', [], ExcelValue.by_value
  attach_function 'model_d117', [], ExcelValue.by_value
  attach_function 'model_e117', [], ExcelValue.by_value
  attach_function 'model_f117', [], ExcelValue.by_value
  attach_function 'model_g117', [], ExcelValue.by_value
  attach_function 'model_h117', [], ExcelValue.by_value
  attach_function 'model_i117', [], ExcelValue.by_value
  attach_function 'model_j117', [], ExcelValue.by_value
  attach_function 'model_k117', [], ExcelValue.by_value
  attach_function 'model_l117', [], ExcelValue.by_value
  attach_function 'model_m117', [], ExcelValue.by_value
  attach_function 'model_n117', [], ExcelValue.by_value
  attach_function 'model_o117', [], ExcelValue.by_value
  attach_function 'model_p117', [], ExcelValue.by_value
  attach_function 'model_q117', [], ExcelValue.by_value
  attach_function 'model_r117', [], ExcelValue.by_value
  attach_function 'model_s117', [], ExcelValue.by_value
  attach_function 'model_t117', [], ExcelValue.by_value
  attach_function 'model_u117', [], ExcelValue.by_value
  attach_function 'model_v117', [], ExcelValue.by_value
  attach_function 'model_w117', [], ExcelValue.by_value
  attach_function 'model_x117', [], ExcelValue.by_value
  attach_function 'model_y117', [], ExcelValue.by_value
  attach_function 'model_z117', [], ExcelValue.by_value
  attach_function 'model_aa117', [], ExcelValue.by_value
  attach_function 'model_ab117', [], ExcelValue.by_value
  attach_function 'model_ac117', [], ExcelValue.by_value
  attach_function 'model_ad117', [], ExcelValue.by_value
  attach_function 'model_ae117', [], ExcelValue.by_value
  attach_function 'model_af117', [], ExcelValue.by_value
  attach_function 'model_ag117', [], ExcelValue.by_value
  attach_function 'model_ah117', [], ExcelValue.by_value
  attach_function 'model_ai117', [], ExcelValue.by_value
  attach_function 'model_aj117', [], ExcelValue.by_value
  attach_function 'model_ak117', [], ExcelValue.by_value
  attach_function 'model_al117', [], ExcelValue.by_value
  attach_function 'model_am117', [], ExcelValue.by_value
  attach_function 'model_an117', [], ExcelValue.by_value
  attach_function 'model_ao117', [], ExcelValue.by_value
  attach_function 'model_c115', [], ExcelValue.by_value
  attach_function 'model_d115', [], ExcelValue.by_value
  attach_function 'model_e115', [], ExcelValue.by_value
  attach_function 'model_f115', [], ExcelValue.by_value
  attach_function 'model_g115', [], ExcelValue.by_value
  attach_function 'model_h115', [], ExcelValue.by_value
  attach_function 'model_i115', [], ExcelValue.by_value
  attach_function 'model_j115', [], ExcelValue.by_value
  attach_function 'model_k115', [], ExcelValue.by_value
  attach_function 'model_l115', [], ExcelValue.by_value
  attach_function 'model_m115', [], ExcelValue.by_value
  attach_function 'model_n115', [], ExcelValue.by_value
  attach_function 'model_o115', [], ExcelValue.by_value
  attach_function 'model_p115', [], ExcelValue.by_value
  attach_function 'model_q115', [], ExcelValue.by_value
  attach_function 'model_r115', [], ExcelValue.by_value
  attach_function 'model_s115', [], ExcelValue.by_value
  attach_function 'model_t115', [], ExcelValue.by_value
  attach_function 'model_u115', [], ExcelValue.by_value
  attach_function 'model_v115', [], ExcelValue.by_value
  attach_function 'model_w115', [], ExcelValue.by_value
  attach_function 'model_x115', [], ExcelValue.by_value
  attach_function 'model_y115', [], ExcelValue.by_value
  attach_function 'model_z115', [], ExcelValue.by_value
  attach_function 'model_aa115', [], ExcelValue.by_value
  attach_function 'model_ab115', [], ExcelValue.by_value
  attach_function 'model_ac115', [], ExcelValue.by_value
  attach_function 'model_ad115', [], ExcelValue.by_value
  attach_function 'model_ae115', [], ExcelValue.by_value
  attach_function 'model_af115', [], ExcelValue.by_value
  attach_function 'model_ag115', [], ExcelValue.by_value
  attach_function 'model_ah115', [], ExcelValue.by_value
  attach_function 'model_ai115', [], ExcelValue.by_value
  attach_function 'model_aj115', [], ExcelValue.by_value
  attach_function 'model_ak115', [], ExcelValue.by_value
  attach_function 'model_al115', [], ExcelValue.by_value
  attach_function 'model_am115', [], ExcelValue.by_value
  attach_function 'model_an115', [], ExcelValue.by_value
  attach_function 'model_ao115', [], ExcelValue.by_value
  attach_function 'model_r31', [], ExcelValue.by_value
  attach_function 'model_q31', [], ExcelValue.by_value
  attach_function 'model_p31', [], ExcelValue.by_value
  attach_function 'model_r32', [], ExcelValue.by_value
  attach_function 'model_q32', [], ExcelValue.by_value
  attach_function 'model_p32', [], ExcelValue.by_value
  attach_function 'model_r33', [], ExcelValue.by_value
  attach_function 'model_q33', [], ExcelValue.by_value
  attach_function 'model_p33', [], ExcelValue.by_value
  attach_function 'model_r34', [], ExcelValue.by_value
  attach_function 'model_q34', [], ExcelValue.by_value
  attach_function 'model_p34', [], ExcelValue.by_value
  attach_function 'model_c139', [], ExcelValue.by_value
  attach_function 'model_d139', [], ExcelValue.by_value
  attach_function 'model_e139', [], ExcelValue.by_value
  attach_function 'model_f139', [], ExcelValue.by_value
  attach_function 'model_g139', [], ExcelValue.by_value
  attach_function 'model_h139', [], ExcelValue.by_value
  attach_function 'model_i139', [], ExcelValue.by_value
  attach_function 'model_j139', [], ExcelValue.by_value
  attach_function 'model_k139', [], ExcelValue.by_value
  attach_function 'model_l139', [], ExcelValue.by_value
  attach_function 'model_m139', [], ExcelValue.by_value
  attach_function 'model_n139', [], ExcelValue.by_value
  attach_function 'model_o139', [], ExcelValue.by_value
  attach_function 'model_p139', [], ExcelValue.by_value
  attach_function 'model_q139', [], ExcelValue.by_value
  attach_function 'model_r139', [], ExcelValue.by_value
  attach_function 'model_s139', [], ExcelValue.by_value
  attach_function 'model_t139', [], ExcelValue.by_value
  attach_function 'model_u139', [], ExcelValue.by_value
  attach_function 'model_v139', [], ExcelValue.by_value
  attach_function 'model_w139', [], ExcelValue.by_value
  attach_function 'model_x139', [], ExcelValue.by_value
  attach_function 'model_y139', [], ExcelValue.by_value
  attach_function 'model_z139', [], ExcelValue.by_value
  attach_function 'model_aa139', [], ExcelValue.by_value
  attach_function 'model_ab139', [], ExcelValue.by_value
  attach_function 'model_ac139', [], ExcelValue.by_value
  attach_function 'model_ad139', [], ExcelValue.by_value
  attach_function 'model_ae139', [], ExcelValue.by_value
  attach_function 'model_af139', [], ExcelValue.by_value
  attach_function 'model_ag139', [], ExcelValue.by_value
  attach_function 'model_ah139', [], ExcelValue.by_value
  attach_function 'model_ai139', [], ExcelValue.by_value
  attach_function 'model_aj139', [], ExcelValue.by_value
  attach_function 'model_ak139', [], ExcelValue.by_value
  attach_function 'model_al139', [], ExcelValue.by_value
  attach_function 'model_am139', [], ExcelValue.by_value
  attach_function 'model_an139', [], ExcelValue.by_value
  attach_function 'model_ao139', [], ExcelValue.by_value
  attach_function 'model_c137', [], ExcelValue.by_value
  attach_function 'model_d137', [], ExcelValue.by_value
  attach_function 'model_e137', [], ExcelValue.by_value
  attach_function 'model_f137', [], ExcelValue.by_value
  attach_function 'model_g137', [], ExcelValue.by_value
  attach_function 'model_h137', [], ExcelValue.by_value
  attach_function 'model_i137', [], ExcelValue.by_value
  attach_function 'model_j137', [], ExcelValue.by_value
  attach_function 'model_k137', [], ExcelValue.by_value
  attach_function 'model_l137', [], ExcelValue.by_value
  attach_function 'model_m137', [], ExcelValue.by_value
  attach_function 'model_n137', [], ExcelValue.by_value
  attach_function 'model_o137', [], ExcelValue.by_value
  attach_function 'model_p137', [], ExcelValue.by_value
  attach_function 'model_q137', [], ExcelValue.by_value
  attach_function 'model_r137', [], ExcelValue.by_value
  attach_function 'model_s137', [], ExcelValue.by_value
  attach_function 'model_t137', [], ExcelValue.by_value
  attach_function 'model_u137', [], ExcelValue.by_value
  attach_function 'model_v137', [], ExcelValue.by_value
  attach_function 'model_w137', [], ExcelValue.by_value
  attach_function 'model_x137', [], ExcelValue.by_value
  attach_function 'model_y137', [], ExcelValue.by_value
  attach_function 'model_z137', [], ExcelValue.by_value
  attach_function 'model_aa137', [], ExcelValue.by_value
  attach_function 'model_ab137', [], ExcelValue.by_value
  attach_function 'model_ac137', [], ExcelValue.by_value
  attach_function 'model_ad137', [], ExcelValue.by_value
  attach_function 'model_ae137', [], ExcelValue.by_value
  attach_function 'model_af137', [], ExcelValue.by_value
  attach_function 'model_ag137', [], ExcelValue.by_value
  attach_function 'model_ah137', [], ExcelValue.by_value
  attach_function 'model_ai137', [], ExcelValue.by_value
  attach_function 'model_aj137', [], ExcelValue.by_value
  attach_function 'model_ak137', [], ExcelValue.by_value
  attach_function 'model_al137', [], ExcelValue.by_value
  attach_function 'model_am137', [], ExcelValue.by_value
  attach_function 'model_an137', [], ExcelValue.by_value
  attach_function 'model_ao137', [], ExcelValue.by_value
  attach_function 'model_c140', [], ExcelValue.by_value
  attach_function 'model_d140', [], ExcelValue.by_value
  attach_function 'model_e140', [], ExcelValue.by_value
  attach_function 'model_f140', [], ExcelValue.by_value
  attach_function 'model_g140', [], ExcelValue.by_value
  attach_function 'model_h140', [], ExcelValue.by_value
  attach_function 'model_i140', [], ExcelValue.by_value
  attach_function 'model_j140', [], ExcelValue.by_value
  attach_function 'model_k140', [], ExcelValue.by_value
  attach_function 'model_l140', [], ExcelValue.by_value
  attach_function 'model_m140', [], ExcelValue.by_value
  attach_function 'model_n140', [], ExcelValue.by_value
  attach_function 'model_o140', [], ExcelValue.by_value
  attach_function 'model_p140', [], ExcelValue.by_value
  attach_function 'model_q140', [], ExcelValue.by_value
  attach_function 'model_r140', [], ExcelValue.by_value
  attach_function 'model_s140', [], ExcelValue.by_value
  attach_function 'model_t140', [], ExcelValue.by_value
  attach_function 'model_u140', [], ExcelValue.by_value
  attach_function 'model_v140', [], ExcelValue.by_value
  attach_function 'model_w140', [], ExcelValue.by_value
  attach_function 'model_x140', [], ExcelValue.by_value
  attach_function 'model_y140', [], ExcelValue.by_value
  attach_function 'model_z140', [], ExcelValue.by_value
  attach_function 'model_aa140', [], ExcelValue.by_value
  attach_function 'model_ab140', [], ExcelValue.by_value
  attach_function 'model_ac140', [], ExcelValue.by_value
  attach_function 'model_ad140', [], ExcelValue.by_value
  attach_function 'model_ae140', [], ExcelValue.by_value
  attach_function 'model_af140', [], ExcelValue.by_value
  attach_function 'model_ag140', [], ExcelValue.by_value
  attach_function 'model_ah140', [], ExcelValue.by_value
  attach_function 'model_ai140', [], ExcelValue.by_value
  attach_function 'model_aj140', [], ExcelValue.by_value
  attach_function 'model_ak140', [], ExcelValue.by_value
  attach_function 'model_al140', [], ExcelValue.by_value
  attach_function 'model_am140', [], ExcelValue.by_value
  attach_function 'model_an140', [], ExcelValue.by_value
  attach_function 'model_ao140', [], ExcelValue.by_value
  attach_function 'model_c141', [], ExcelValue.by_value
  attach_function 'model_d141', [], ExcelValue.by_value
  attach_function 'model_e141', [], ExcelValue.by_value
  attach_function 'model_f141', [], ExcelValue.by_value
  attach_function 'model_g141', [], ExcelValue.by_value
  attach_function 'model_h141', [], ExcelValue.by_value
  attach_function 'model_i141', [], ExcelValue.by_value
  attach_function 'model_j141', [], ExcelValue.by_value
  attach_function 'model_k141', [], ExcelValue.by_value
  attach_function 'model_l141', [], ExcelValue.by_value
  attach_function 'model_m141', [], ExcelValue.by_value
  attach_function 'model_n141', [], ExcelValue.by_value
  attach_function 'model_o141', [], ExcelValue.by_value
  attach_function 'model_p141', [], ExcelValue.by_value
  attach_function 'model_q141', [], ExcelValue.by_value
  attach_function 'model_r141', [], ExcelValue.by_value
  attach_function 'model_s141', [], ExcelValue.by_value
  attach_function 'model_t141', [], ExcelValue.by_value
  attach_function 'model_u141', [], ExcelValue.by_value
  attach_function 'model_v141', [], ExcelValue.by_value
  attach_function 'model_w141', [], ExcelValue.by_value
  attach_function 'model_x141', [], ExcelValue.by_value
  attach_function 'model_y141', [], ExcelValue.by_value
  attach_function 'model_z141', [], ExcelValue.by_value
  attach_function 'model_aa141', [], ExcelValue.by_value
  attach_function 'model_ab141', [], ExcelValue.by_value
  attach_function 'model_ac141', [], ExcelValue.by_value
  attach_function 'model_ad141', [], ExcelValue.by_value
  attach_function 'model_ae141', [], ExcelValue.by_value
  attach_function 'model_af141', [], ExcelValue.by_value
  attach_function 'model_ag141', [], ExcelValue.by_value
  attach_function 'model_ah141', [], ExcelValue.by_value
  attach_function 'model_ai141', [], ExcelValue.by_value
  attach_function 'model_aj141', [], ExcelValue.by_value
  attach_function 'model_ak141', [], ExcelValue.by_value
  attach_function 'model_al141', [], ExcelValue.by_value
  attach_function 'model_am141', [], ExcelValue.by_value
  attach_function 'model_an141', [], ExcelValue.by_value
  attach_function 'model_ao141', [], ExcelValue.by_value
  attach_function 'model_c143', [], ExcelValue.by_value
  attach_function 'model_d143', [], ExcelValue.by_value
  attach_function 'model_e143', [], ExcelValue.by_value
  attach_function 'model_f143', [], ExcelValue.by_value
  attach_function 'model_g143', [], ExcelValue.by_value
  attach_function 'model_h143', [], ExcelValue.by_value
  attach_function 'model_i143', [], ExcelValue.by_value
  attach_function 'model_j143', [], ExcelValue.by_value
  attach_function 'model_k143', [], ExcelValue.by_value
  attach_function 'model_l143', [], ExcelValue.by_value
  attach_function 'model_m143', [], ExcelValue.by_value
  attach_function 'model_n143', [], ExcelValue.by_value
  attach_function 'model_o143', [], ExcelValue.by_value
  attach_function 'model_p143', [], ExcelValue.by_value
  attach_function 'model_q143', [], ExcelValue.by_value
  attach_function 'model_r143', [], ExcelValue.by_value
  attach_function 'model_s143', [], ExcelValue.by_value
  attach_function 'model_t143', [], ExcelValue.by_value
  attach_function 'model_u143', [], ExcelValue.by_value
  attach_function 'model_v143', [], ExcelValue.by_value
  attach_function 'model_w143', [], ExcelValue.by_value
  attach_function 'model_x143', [], ExcelValue.by_value
  attach_function 'model_y143', [], ExcelValue.by_value
  attach_function 'model_z143', [], ExcelValue.by_value
  attach_function 'model_aa143', [], ExcelValue.by_value
  attach_function 'model_ab143', [], ExcelValue.by_value
  attach_function 'model_ac143', [], ExcelValue.by_value
  attach_function 'model_ad143', [], ExcelValue.by_value
  attach_function 'model_ae143', [], ExcelValue.by_value
  attach_function 'model_af143', [], ExcelValue.by_value
  attach_function 'model_ag143', [], ExcelValue.by_value
  attach_function 'model_ah143', [], ExcelValue.by_value
  attach_function 'model_ai143', [], ExcelValue.by_value
  attach_function 'model_aj143', [], ExcelValue.by_value
  attach_function 'model_ak143', [], ExcelValue.by_value
  attach_function 'model_al143', [], ExcelValue.by_value
  attach_function 'model_am143', [], ExcelValue.by_value
  attach_function 'model_an143', [], ExcelValue.by_value
  attach_function 'model_ao143', [], ExcelValue.by_value
  attach_function 'model_c142', [], ExcelValue.by_value
  attach_function 'model_d142', [], ExcelValue.by_value
  attach_function 'model_e142', [], ExcelValue.by_value
  attach_function 'model_f142', [], ExcelValue.by_value
  attach_function 'model_g142', [], ExcelValue.by_value
  attach_function 'model_h142', [], ExcelValue.by_value
  attach_function 'model_i142', [], ExcelValue.by_value
  attach_function 'model_j142', [], ExcelValue.by_value
  attach_function 'model_k142', [], ExcelValue.by_value
  attach_function 'model_l142', [], ExcelValue.by_value
  attach_function 'model_m142', [], ExcelValue.by_value
  attach_function 'model_n142', [], ExcelValue.by_value
  attach_function 'model_o142', [], ExcelValue.by_value
  attach_function 'model_p142', [], ExcelValue.by_value
  attach_function 'model_q142', [], ExcelValue.by_value
  attach_function 'model_r142', [], ExcelValue.by_value
  attach_function 'model_s142', [], ExcelValue.by_value
  attach_function 'model_t142', [], ExcelValue.by_value
  attach_function 'model_u142', [], ExcelValue.by_value
  attach_function 'model_v142', [], ExcelValue.by_value
  attach_function 'model_w142', [], ExcelValue.by_value
  attach_function 'model_x142', [], ExcelValue.by_value
  attach_function 'model_y142', [], ExcelValue.by_value
  attach_function 'model_z142', [], ExcelValue.by_value
  attach_function 'model_aa142', [], ExcelValue.by_value
  attach_function 'model_ab142', [], ExcelValue.by_value
  attach_function 'model_ac142', [], ExcelValue.by_value
  attach_function 'model_ad142', [], ExcelValue.by_value
  attach_function 'model_ae142', [], ExcelValue.by_value
  attach_function 'model_af142', [], ExcelValue.by_value
  attach_function 'model_ag142', [], ExcelValue.by_value
  attach_function 'model_ah142', [], ExcelValue.by_value
  attach_function 'model_ai142', [], ExcelValue.by_value
  attach_function 'model_aj142', [], ExcelValue.by_value
  attach_function 'model_ak142', [], ExcelValue.by_value
  attach_function 'model_al142', [], ExcelValue.by_value
  attach_function 'model_am142', [], ExcelValue.by_value
  attach_function 'model_an142', [], ExcelValue.by_value
  attach_function 'model_ao142', [], ExcelValue.by_value
  attach_function 'model_c132', [], ExcelValue.by_value
  attach_function 'model_d132', [], ExcelValue.by_value
  attach_function 'model_e132', [], ExcelValue.by_value
  attach_function 'model_f132', [], ExcelValue.by_value
  attach_function 'model_g132', [], ExcelValue.by_value
  attach_function 'model_h132', [], ExcelValue.by_value
  attach_function 'model_i132', [], ExcelValue.by_value
  attach_function 'model_j132', [], ExcelValue.by_value
  attach_function 'model_k132', [], ExcelValue.by_value
  attach_function 'model_l132', [], ExcelValue.by_value
  attach_function 'model_m132', [], ExcelValue.by_value
  attach_function 'model_n132', [], ExcelValue.by_value
  attach_function 'model_o132', [], ExcelValue.by_value
  attach_function 'model_p132', [], ExcelValue.by_value
  attach_function 'model_q132', [], ExcelValue.by_value
  attach_function 'model_r132', [], ExcelValue.by_value
  attach_function 'model_s132', [], ExcelValue.by_value
  attach_function 'model_t132', [], ExcelValue.by_value
  attach_function 'model_u132', [], ExcelValue.by_value
  attach_function 'model_v132', [], ExcelValue.by_value
  attach_function 'model_w132', [], ExcelValue.by_value
  attach_function 'model_x132', [], ExcelValue.by_value
  attach_function 'model_y132', [], ExcelValue.by_value
  attach_function 'model_z132', [], ExcelValue.by_value
  attach_function 'model_aa132', [], ExcelValue.by_value
  attach_function 'model_ab132', [], ExcelValue.by_value
  attach_function 'model_ac132', [], ExcelValue.by_value
  attach_function 'model_ad132', [], ExcelValue.by_value
  attach_function 'model_ae132', [], ExcelValue.by_value
  attach_function 'model_af132', [], ExcelValue.by_value
  attach_function 'model_ag132', [], ExcelValue.by_value
  attach_function 'model_ah132', [], ExcelValue.by_value
  attach_function 'model_ai132', [], ExcelValue.by_value
  attach_function 'model_aj132', [], ExcelValue.by_value
  attach_function 'model_ak132', [], ExcelValue.by_value
  attach_function 'model_al132', [], ExcelValue.by_value
  attach_function 'model_am132', [], ExcelValue.by_value
  attach_function 'model_an132', [], ExcelValue.by_value
  attach_function 'model_ao132', [], ExcelValue.by_value
  attach_function 'model_c134', [], ExcelValue.by_value
  attach_function 'model_d134', [], ExcelValue.by_value
  attach_function 'model_e134', [], ExcelValue.by_value
  attach_function 'model_f134', [], ExcelValue.by_value
  attach_function 'model_g134', [], ExcelValue.by_value
  attach_function 'model_h134', [], ExcelValue.by_value
  attach_function 'model_i134', [], ExcelValue.by_value
  attach_function 'model_j134', [], ExcelValue.by_value
  attach_function 'model_k134', [], ExcelValue.by_value
  attach_function 'model_l134', [], ExcelValue.by_value
  attach_function 'model_m134', [], ExcelValue.by_value
  attach_function 'model_n134', [], ExcelValue.by_value
  attach_function 'model_o134', [], ExcelValue.by_value
  attach_function 'model_p134', [], ExcelValue.by_value
  attach_function 'model_q134', [], ExcelValue.by_value
  attach_function 'model_r134', [], ExcelValue.by_value
  attach_function 'model_s134', [], ExcelValue.by_value
  attach_function 'model_t134', [], ExcelValue.by_value
  attach_function 'model_u134', [], ExcelValue.by_value
  attach_function 'model_v134', [], ExcelValue.by_value
  attach_function 'model_w134', [], ExcelValue.by_value
  attach_function 'model_x134', [], ExcelValue.by_value
  attach_function 'model_y134', [], ExcelValue.by_value
  attach_function 'model_z134', [], ExcelValue.by_value
  attach_function 'model_aa134', [], ExcelValue.by_value
  attach_function 'model_ab134', [], ExcelValue.by_value
  attach_function 'model_ac134', [], ExcelValue.by_value
  attach_function 'model_ad134', [], ExcelValue.by_value
  attach_function 'model_ae134', [], ExcelValue.by_value
  attach_function 'model_af134', [], ExcelValue.by_value
  attach_function 'model_ag134', [], ExcelValue.by_value
  attach_function 'model_ah134', [], ExcelValue.by_value
  attach_function 'model_ai134', [], ExcelValue.by_value
  attach_function 'model_aj134', [], ExcelValue.by_value
  attach_function 'model_ak134', [], ExcelValue.by_value
  attach_function 'model_al134', [], ExcelValue.by_value
  attach_function 'model_am134', [], ExcelValue.by_value
  attach_function 'model_an134', [], ExcelValue.by_value
  attach_function 'model_ao134', [], ExcelValue.by_value
  attach_function 'model_c131', [], ExcelValue.by_value
  attach_function 'model_d131', [], ExcelValue.by_value
  attach_function 'model_e131', [], ExcelValue.by_value
  attach_function 'model_f131', [], ExcelValue.by_value
  attach_function 'model_g131', [], ExcelValue.by_value
  attach_function 'model_h131', [], ExcelValue.by_value
  attach_function 'model_i131', [], ExcelValue.by_value
  attach_function 'model_j131', [], ExcelValue.by_value
  attach_function 'model_k131', [], ExcelValue.by_value
  attach_function 'model_l131', [], ExcelValue.by_value
  attach_function 'model_m131', [], ExcelValue.by_value
  attach_function 'model_n131', [], ExcelValue.by_value
  attach_function 'model_o131', [], ExcelValue.by_value
  attach_function 'model_p131', [], ExcelValue.by_value
  attach_function 'model_q131', [], ExcelValue.by_value
  attach_function 'model_r131', [], ExcelValue.by_value
  attach_function 'model_s131', [], ExcelValue.by_value
  attach_function 'model_t131', [], ExcelValue.by_value
  attach_function 'model_u131', [], ExcelValue.by_value
  attach_function 'model_v131', [], ExcelValue.by_value
  attach_function 'model_w131', [], ExcelValue.by_value
  attach_function 'model_x131', [], ExcelValue.by_value
  attach_function 'model_y131', [], ExcelValue.by_value
  attach_function 'model_z131', [], ExcelValue.by_value
  attach_function 'model_aa131', [], ExcelValue.by_value
  attach_function 'model_ab131', [], ExcelValue.by_value
  attach_function 'model_ac131', [], ExcelValue.by_value
  attach_function 'model_ad131', [], ExcelValue.by_value
  attach_function 'model_ae131', [], ExcelValue.by_value
  attach_function 'model_af131', [], ExcelValue.by_value
  attach_function 'model_ag131', [], ExcelValue.by_value
  attach_function 'model_ah131', [], ExcelValue.by_value
  attach_function 'model_ai131', [], ExcelValue.by_value
  attach_function 'model_aj131', [], ExcelValue.by_value
  attach_function 'model_ak131', [], ExcelValue.by_value
  attach_function 'model_al131', [], ExcelValue.by_value
  attach_function 'model_am131', [], ExcelValue.by_value
  attach_function 'model_an131', [], ExcelValue.by_value
  attach_function 'model_ao131', [], ExcelValue.by_value
  attach_function 'model_c133', [], ExcelValue.by_value
  attach_function 'model_d133', [], ExcelValue.by_value
  attach_function 'model_e133', [], ExcelValue.by_value
  attach_function 'model_f133', [], ExcelValue.by_value
  attach_function 'model_g133', [], ExcelValue.by_value
  attach_function 'model_h133', [], ExcelValue.by_value
  attach_function 'model_i133', [], ExcelValue.by_value
  attach_function 'model_j133', [], ExcelValue.by_value
  attach_function 'model_k133', [], ExcelValue.by_value
  attach_function 'model_l133', [], ExcelValue.by_value
  attach_function 'model_m133', [], ExcelValue.by_value
  attach_function 'model_n133', [], ExcelValue.by_value
  attach_function 'model_o133', [], ExcelValue.by_value
  attach_function 'model_p133', [], ExcelValue.by_value
  attach_function 'model_q133', [], ExcelValue.by_value
  attach_function 'model_r133', [], ExcelValue.by_value
  attach_function 'model_s133', [], ExcelValue.by_value
  attach_function 'model_t133', [], ExcelValue.by_value
  attach_function 'model_u133', [], ExcelValue.by_value
  attach_function 'model_v133', [], ExcelValue.by_value
  attach_function 'model_w133', [], ExcelValue.by_value
  attach_function 'model_x133', [], ExcelValue.by_value
  attach_function 'model_y133', [], ExcelValue.by_value
  attach_function 'model_z133', [], ExcelValue.by_value
  attach_function 'model_aa133', [], ExcelValue.by_value
  attach_function 'model_ab133', [], ExcelValue.by_value
  attach_function 'model_ac133', [], ExcelValue.by_value
  attach_function 'model_ad133', [], ExcelValue.by_value
  attach_function 'model_ae133', [], ExcelValue.by_value
  attach_function 'model_af133', [], ExcelValue.by_value
  attach_function 'model_ag133', [], ExcelValue.by_value
  attach_function 'model_ah133', [], ExcelValue.by_value
  attach_function 'model_ai133', [], ExcelValue.by_value
  attach_function 'model_aj133', [], ExcelValue.by_value
  attach_function 'model_ak133', [], ExcelValue.by_value
  attach_function 'model_al133', [], ExcelValue.by_value
  attach_function 'model_am133', [], ExcelValue.by_value
  attach_function 'model_an133', [], ExcelValue.by_value
  attach_function 'model_ao133', [], ExcelValue.by_value
  attach_function 'model_c77', [], ExcelValue.by_value
  attach_function 'model_c126', [], ExcelValue.by_value
  attach_function 'model_d126', [], ExcelValue.by_value
  attach_function 'model_e126', [], ExcelValue.by_value
  attach_function 'model_f126', [], ExcelValue.by_value
  attach_function 'model_g126', [], ExcelValue.by_value
  attach_function 'model_h126', [], ExcelValue.by_value
  attach_function 'model_i126', [], ExcelValue.by_value
  attach_function 'model_j126', [], ExcelValue.by_value
  attach_function 'model_k126', [], ExcelValue.by_value
  attach_function 'model_l126', [], ExcelValue.by_value
  attach_function 'model_m126', [], ExcelValue.by_value
  attach_function 'model_n126', [], ExcelValue.by_value
  attach_function 'model_o126', [], ExcelValue.by_value
  attach_function 'model_p126', [], ExcelValue.by_value
  attach_function 'model_q126', [], ExcelValue.by_value
  attach_function 'model_r126', [], ExcelValue.by_value
  attach_function 'model_s126', [], ExcelValue.by_value
  attach_function 'model_t126', [], ExcelValue.by_value
  attach_function 'model_u126', [], ExcelValue.by_value
  attach_function 'model_v126', [], ExcelValue.by_value
  attach_function 'model_w126', [], ExcelValue.by_value
  attach_function 'model_x126', [], ExcelValue.by_value
  attach_function 'model_y126', [], ExcelValue.by_value
  attach_function 'model_z126', [], ExcelValue.by_value
  attach_function 'model_aa126', [], ExcelValue.by_value
  attach_function 'model_ab126', [], ExcelValue.by_value
  attach_function 'model_ac126', [], ExcelValue.by_value
  attach_function 'model_ad126', [], ExcelValue.by_value
  attach_function 'model_ae126', [], ExcelValue.by_value
  attach_function 'model_af126', [], ExcelValue.by_value
  attach_function 'model_ag126', [], ExcelValue.by_value
  attach_function 'model_ah126', [], ExcelValue.by_value
  attach_function 'model_ai126', [], ExcelValue.by_value
  attach_function 'model_aj126', [], ExcelValue.by_value
  attach_function 'model_ak126', [], ExcelValue.by_value
  attach_function 'model_al126', [], ExcelValue.by_value
  attach_function 'model_am126', [], ExcelValue.by_value
  attach_function 'model_an126', [], ExcelValue.by_value
  attach_function 'model_ao126', [], ExcelValue.by_value
  attach_function 'model_c128', [], ExcelValue.by_value
  attach_function 'model_d128', [], ExcelValue.by_value
  attach_function 'model_e128', [], ExcelValue.by_value
  attach_function 'model_f128', [], ExcelValue.by_value
  attach_function 'model_g128', [], ExcelValue.by_value
  attach_function 'model_h128', [], ExcelValue.by_value
  attach_function 'model_i128', [], ExcelValue.by_value
  attach_function 'model_j128', [], ExcelValue.by_value
  attach_function 'model_k128', [], ExcelValue.by_value
  attach_function 'model_l128', [], ExcelValue.by_value
  attach_function 'model_m128', [], ExcelValue.by_value
  attach_function 'model_n128', [], ExcelValue.by_value
  attach_function 'model_o128', [], ExcelValue.by_value
  attach_function 'model_p128', [], ExcelValue.by_value
  attach_function 'model_q128', [], ExcelValue.by_value
  attach_function 'model_r128', [], ExcelValue.by_value
  attach_function 'model_s128', [], ExcelValue.by_value
  attach_function 'model_t128', [], ExcelValue.by_value
  attach_function 'model_u128', [], ExcelValue.by_value
  attach_function 'model_v128', [], ExcelValue.by_value
  attach_function 'model_w128', [], ExcelValue.by_value
  attach_function 'model_x128', [], ExcelValue.by_value
  attach_function 'model_y128', [], ExcelValue.by_value
  attach_function 'model_z128', [], ExcelValue.by_value
  attach_function 'model_aa128', [], ExcelValue.by_value
  attach_function 'model_ab128', [], ExcelValue.by_value
  attach_function 'model_ac128', [], ExcelValue.by_value
  attach_function 'model_ad128', [], ExcelValue.by_value
  attach_function 'model_ae128', [], ExcelValue.by_value
  attach_function 'model_af128', [], ExcelValue.by_value
  attach_function 'model_ag128', [], ExcelValue.by_value
  attach_function 'model_ah128', [], ExcelValue.by_value
  attach_function 'model_ai128', [], ExcelValue.by_value
  attach_function 'model_aj128', [], ExcelValue.by_value
  attach_function 'model_ak128', [], ExcelValue.by_value
  attach_function 'model_al128', [], ExcelValue.by_value
  attach_function 'model_am128', [], ExcelValue.by_value
  attach_function 'model_an128', [], ExcelValue.by_value
  attach_function 'model_ao128', [], ExcelValue.by_value
  attach_function 'model_c125', [], ExcelValue.by_value
  attach_function 'model_d125', [], ExcelValue.by_value
  attach_function 'model_e125', [], ExcelValue.by_value
  attach_function 'model_f125', [], ExcelValue.by_value
  attach_function 'model_g125', [], ExcelValue.by_value
  attach_function 'model_h125', [], ExcelValue.by_value
  attach_function 'model_i125', [], ExcelValue.by_value
  attach_function 'model_j125', [], ExcelValue.by_value
  attach_function 'model_k125', [], ExcelValue.by_value
  attach_function 'model_l125', [], ExcelValue.by_value
  attach_function 'model_m125', [], ExcelValue.by_value
  attach_function 'model_n125', [], ExcelValue.by_value
  attach_function 'model_o125', [], ExcelValue.by_value
  attach_function 'model_p125', [], ExcelValue.by_value
  attach_function 'model_q125', [], ExcelValue.by_value
  attach_function 'model_r125', [], ExcelValue.by_value
  attach_function 'model_s125', [], ExcelValue.by_value
  attach_function 'model_t125', [], ExcelValue.by_value
  attach_function 'model_u125', [], ExcelValue.by_value
  attach_function 'model_v125', [], ExcelValue.by_value
  attach_function 'model_w125', [], ExcelValue.by_value
  attach_function 'model_x125', [], ExcelValue.by_value
  attach_function 'model_y125', [], ExcelValue.by_value
  attach_function 'model_z125', [], ExcelValue.by_value
  attach_function 'model_aa125', [], ExcelValue.by_value
  attach_function 'model_ab125', [], ExcelValue.by_value
  attach_function 'model_ac125', [], ExcelValue.by_value
  attach_function 'model_ad125', [], ExcelValue.by_value
  attach_function 'model_ae125', [], ExcelValue.by_value
  attach_function 'model_af125', [], ExcelValue.by_value
  attach_function 'model_ag125', [], ExcelValue.by_value
  attach_function 'model_ah125', [], ExcelValue.by_value
  attach_function 'model_ai125', [], ExcelValue.by_value
  attach_function 'model_aj125', [], ExcelValue.by_value
  attach_function 'model_ak125', [], ExcelValue.by_value
  attach_function 'model_al125', [], ExcelValue.by_value
  attach_function 'model_am125', [], ExcelValue.by_value
  attach_function 'model_an125', [], ExcelValue.by_value
  attach_function 'model_ao125', [], ExcelValue.by_value
  attach_function 'model_c127', [], ExcelValue.by_value
  attach_function 'model_d127', [], ExcelValue.by_value
  attach_function 'model_e127', [], ExcelValue.by_value
  attach_function 'model_f127', [], ExcelValue.by_value
  attach_function 'model_g127', [], ExcelValue.by_value
  attach_function 'model_h127', [], ExcelValue.by_value
  attach_function 'model_i127', [], ExcelValue.by_value
  attach_function 'model_j127', [], ExcelValue.by_value
  attach_function 'model_k127', [], ExcelValue.by_value
  attach_function 'model_l127', [], ExcelValue.by_value
  attach_function 'model_m127', [], ExcelValue.by_value
  attach_function 'model_n127', [], ExcelValue.by_value
  attach_function 'model_o127', [], ExcelValue.by_value
  attach_function 'model_p127', [], ExcelValue.by_value
  attach_function 'model_q127', [], ExcelValue.by_value
  attach_function 'model_r127', [], ExcelValue.by_value
  attach_function 'model_s127', [], ExcelValue.by_value
  attach_function 'model_t127', [], ExcelValue.by_value
  attach_function 'model_u127', [], ExcelValue.by_value
  attach_function 'model_v127', [], ExcelValue.by_value
  attach_function 'model_w127', [], ExcelValue.by_value
  attach_function 'model_x127', [], ExcelValue.by_value
  attach_function 'model_y127', [], ExcelValue.by_value
  attach_function 'model_z127', [], ExcelValue.by_value
  attach_function 'model_aa127', [], ExcelValue.by_value
  attach_function 'model_ab127', [], ExcelValue.by_value
  attach_function 'model_ac127', [], ExcelValue.by_value
  attach_function 'model_ad127', [], ExcelValue.by_value
  attach_function 'model_ae127', [], ExcelValue.by_value
  attach_function 'model_af127', [], ExcelValue.by_value
  attach_function 'model_ag127', [], ExcelValue.by_value
  attach_function 'model_ah127', [], ExcelValue.by_value
  attach_function 'model_ai127', [], ExcelValue.by_value
  attach_function 'model_aj127', [], ExcelValue.by_value
  attach_function 'model_ak127', [], ExcelValue.by_value
  attach_function 'model_al127', [], ExcelValue.by_value
  attach_function 'model_am127', [], ExcelValue.by_value
  attach_function 'model_an127', [], ExcelValue.by_value
  attach_function 'model_ao127', [], ExcelValue.by_value
  attach_function 'model_c124', [], ExcelValue.by_value
  attach_function 'model_d124', [], ExcelValue.by_value
  attach_function 'model_e124', [], ExcelValue.by_value
  attach_function 'model_f124', [], ExcelValue.by_value
  attach_function 'model_g124', [], ExcelValue.by_value
  attach_function 'model_h124', [], ExcelValue.by_value
  attach_function 'model_i124', [], ExcelValue.by_value
  attach_function 'model_j124', [], ExcelValue.by_value
  attach_function 'model_k124', [], ExcelValue.by_value
  attach_function 'model_l124', [], ExcelValue.by_value
  attach_function 'model_m124', [], ExcelValue.by_value
  attach_function 'model_n124', [], ExcelValue.by_value
  attach_function 'model_o124', [], ExcelValue.by_value
  attach_function 'model_p124', [], ExcelValue.by_value
  attach_function 'model_q124', [], ExcelValue.by_value
  attach_function 'model_r124', [], ExcelValue.by_value
  attach_function 'model_s124', [], ExcelValue.by_value
  attach_function 'model_t124', [], ExcelValue.by_value
  attach_function 'model_u124', [], ExcelValue.by_value
  attach_function 'model_v124', [], ExcelValue.by_value
  attach_function 'model_w124', [], ExcelValue.by_value
  attach_function 'model_x124', [], ExcelValue.by_value
  attach_function 'model_y124', [], ExcelValue.by_value
  attach_function 'model_z124', [], ExcelValue.by_value
  attach_function 'model_aa124', [], ExcelValue.by_value
  attach_function 'model_ab124', [], ExcelValue.by_value
  attach_function 'model_ac124', [], ExcelValue.by_value
  attach_function 'model_ad124', [], ExcelValue.by_value
  attach_function 'model_ae124', [], ExcelValue.by_value
  attach_function 'model_af124', [], ExcelValue.by_value
  attach_function 'model_ag124', [], ExcelValue.by_value
  attach_function 'model_ah124', [], ExcelValue.by_value
  attach_function 'model_ai124', [], ExcelValue.by_value
  attach_function 'model_aj124', [], ExcelValue.by_value
  attach_function 'model_ak124', [], ExcelValue.by_value
  attach_function 'model_al124', [], ExcelValue.by_value
  attach_function 'model_am124', [], ExcelValue.by_value
  attach_function 'model_an124', [], ExcelValue.by_value
  attach_function 'model_ao124', [], ExcelValue.by_value
  attach_function 'model_c39', [], ExcelValue.by_value
  attach_function 'model_c38', [], ExcelValue.by_value
  attach_function 'model_c120', [], ExcelValue.by_value
  attach_function 'model_d120', [], ExcelValue.by_value
  attach_function 'model_e120', [], ExcelValue.by_value
  attach_function 'model_f120', [], ExcelValue.by_value
  attach_function 'model_g120', [], ExcelValue.by_value
  attach_function 'model_h120', [], ExcelValue.by_value
  attach_function 'model_i120', [], ExcelValue.by_value
  attach_function 'model_j120', [], ExcelValue.by_value
  attach_function 'model_k120', [], ExcelValue.by_value
  attach_function 'model_l120', [], ExcelValue.by_value
  attach_function 'model_m120', [], ExcelValue.by_value
  attach_function 'model_n120', [], ExcelValue.by_value
  attach_function 'model_o120', [], ExcelValue.by_value
  attach_function 'model_p120', [], ExcelValue.by_value
  attach_function 'model_q120', [], ExcelValue.by_value
  attach_function 'model_r120', [], ExcelValue.by_value
  attach_function 'model_s120', [], ExcelValue.by_value
  attach_function 'model_t120', [], ExcelValue.by_value
  attach_function 'model_u120', [], ExcelValue.by_value
  attach_function 'model_v120', [], ExcelValue.by_value
  attach_function 'model_w120', [], ExcelValue.by_value
  attach_function 'model_x120', [], ExcelValue.by_value
  attach_function 'model_y120', [], ExcelValue.by_value
  attach_function 'model_z120', [], ExcelValue.by_value
  attach_function 'model_aa120', [], ExcelValue.by_value
  attach_function 'model_ab120', [], ExcelValue.by_value
  attach_function 'model_ac120', [], ExcelValue.by_value
  attach_function 'model_ad120', [], ExcelValue.by_value
  attach_function 'model_ae120', [], ExcelValue.by_value
  attach_function 'model_af120', [], ExcelValue.by_value
  attach_function 'model_ag120', [], ExcelValue.by_value
  attach_function 'model_ah120', [], ExcelValue.by_value
  attach_function 'model_ai120', [], ExcelValue.by_value
  attach_function 'model_aj120', [], ExcelValue.by_value
  attach_function 'model_ak120', [], ExcelValue.by_value
  attach_function 'model_al120', [], ExcelValue.by_value
  attach_function 'model_am120', [], ExcelValue.by_value
  attach_function 'model_an120', [], ExcelValue.by_value
  attach_function 'model_ao120', [], ExcelValue.by_value
  attach_function 'model_c37', [], ExcelValue.by_value
  attach_function 'model_c121', [], ExcelValue.by_value
  attach_function 'model_d121', [], ExcelValue.by_value
  attach_function 'model_e121', [], ExcelValue.by_value
  attach_function 'model_f121', [], ExcelValue.by_value
  attach_function 'model_g121', [], ExcelValue.by_value
  attach_function 'model_h121', [], ExcelValue.by_value
  attach_function 'model_i121', [], ExcelValue.by_value
  attach_function 'model_j121', [], ExcelValue.by_value
  attach_function 'model_k121', [], ExcelValue.by_value
  attach_function 'model_l121', [], ExcelValue.by_value
  attach_function 'model_m121', [], ExcelValue.by_value
  attach_function 'model_n121', [], ExcelValue.by_value
  attach_function 'model_o121', [], ExcelValue.by_value
  attach_function 'model_p121', [], ExcelValue.by_value
  attach_function 'model_q121', [], ExcelValue.by_value
  attach_function 'model_r121', [], ExcelValue.by_value
  attach_function 'model_s121', [], ExcelValue.by_value
  attach_function 'model_t121', [], ExcelValue.by_value
  attach_function 'model_u121', [], ExcelValue.by_value
  attach_function 'model_v121', [], ExcelValue.by_value
  attach_function 'model_w121', [], ExcelValue.by_value
  attach_function 'model_x121', [], ExcelValue.by_value
  attach_function 'model_y121', [], ExcelValue.by_value
  attach_function 'model_z121', [], ExcelValue.by_value
  attach_function 'model_aa121', [], ExcelValue.by_value
  attach_function 'model_ab121', [], ExcelValue.by_value
  attach_function 'model_ac121', [], ExcelValue.by_value
  attach_function 'model_ad121', [], ExcelValue.by_value
  attach_function 'model_ae121', [], ExcelValue.by_value
  attach_function 'model_af121', [], ExcelValue.by_value
  attach_function 'model_ag121', [], ExcelValue.by_value
  attach_function 'model_ah121', [], ExcelValue.by_value
  attach_function 'model_ai121', [], ExcelValue.by_value
  attach_function 'model_aj121', [], ExcelValue.by_value
  attach_function 'model_ak121', [], ExcelValue.by_value
  attach_function 'model_al121', [], ExcelValue.by_value
  attach_function 'model_am121', [], ExcelValue.by_value
  attach_function 'model_an121', [], ExcelValue.by_value
  attach_function 'model_ao121', [], ExcelValue.by_value
  attach_function 'model_c30', [], ExcelValue.by_value
  attach_function 'model_c35', [], ExcelValue.by_value
  attach_function 'model_c76', [], ExcelValue.by_value
  attach_function 'model_c23', [], ExcelValue.by_value
  attach_function 'model_c33', [], ExcelValue.by_value
  # end of Model

  # start of Charts
  # end of Charts
  # Start of named references
  attach_function 'n_2012_onwards_electricity_demand_growth_rate', [], ExcelValue.by_value
  attach_function 'n_2020_fossil_fuel_emissions_factor', [], ExcelValue.by_value
  attach_function 'n_2020_non_renewable_low_carbon_generation_i_e_nuclear_ccs', [], ExcelValue.by_value
  attach_function 'n_2020_renewables_target', [], ExcelValue.by_value
  attach_function 'n_2020_renewables_target_gco2_kwh', [], ExcelValue.by_value
  attach_function 'n_2020_renewables_target_twh', [], ExcelValue.by_value
  attach_function 'n_2030_decarbonisation_level', [], ExcelValue.by_value
  attach_function 'n_2050_electricity_demand', [], ExcelValue.by_value
  attach_function 'n_2050_emissions_electricity', [], ExcelValue.by_value
  attach_function 'n_2050_emissions_industry', [], ExcelValue.by_value
  attach_function 'n_2050_emissions_total', [], ExcelValue.by_value
  attach_function 'n_2050_fossil_fuel_emissions_factor', [], ExcelValue.by_value
  attach_function 'n_2050_maximum_electricity_demand', [], ExcelValue.by_value
  attach_function 'n_2050_minimum_electricity_demand', [], ExcelValue.by_value
  attach_function 'annual_change_in_non_electricity_traded_emissions', [], ExcelValue.by_value
  attach_function 'average_life_high_carbon', [], ExcelValue.by_value
  attach_function 'average_life_other_low_carbon', [], ExcelValue.by_value
  attach_function 'average_life_wind', [], ExcelValue.by_value
  attach_function 'baseload_demand', [], ExcelValue.by_value
  attach_function 'build_rate_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'build_rate_from_now_to_2020', [], ExcelValue.by_value
  attach_function 'build_rate_high_carbon', [], ExcelValue.by_value
  attach_function 'build_rate_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'build_rate_target_in_second_build', [], ExcelValue.by_value
  attach_function 'build_rate_total_low_carbon', [], ExcelValue.by_value
  attach_function 'capacity_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'capacity_high_carbon', [], ExcelValue.by_value
  attach_function 'capacity_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'capacity_total', [], ExcelValue.by_value
  attach_function 'capacity_total_low_carbon', [], ExcelValue.by_value
  attach_function 'cb2_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb2_scenario', [], ExcelValue.by_value
  attach_function 'cb2_traded_cap', [], ExcelValue.by_value
  attach_function 'cb3_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb3_scenario', [], ExcelValue.by_value
  attach_function 'cb3_traded_cap', [], ExcelValue.by_value
  attach_function 'cb4_current_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb4_current_scenario', [], ExcelValue.by_value
  attach_function 'cb4_current_traded_cap', [], ExcelValue.by_value
  attach_function 'cb4_revised_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb4_revised_scenario', [], ExcelValue.by_value
  attach_function 'cb4_revised_traded_cap', [], ExcelValue.by_value
  attach_function 'emissions_electicity', [], ExcelValue.by_value
  attach_function 'emissions_factor', [], ExcelValue.by_value
  attach_function 'emissions_non_electricity_traded', [], ExcelValue.by_value
  attach_function 'emissions_total_traded', [], ExcelValue.by_value
  attach_function 'emissions_uk_share_of_eu_ets_cap_alternative', [], ExcelValue.by_value
  attach_function 'emissions_uk_share_of_eu_ets_cap_current', [], ExcelValue.by_value
  attach_function 'energy_output_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'energy_output_high_carbon', [], ExcelValue.by_value
  attach_function 'energy_output_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'energy_output_total_low_carbon', [], ExcelValue.by_value
  attach_function 'gw_per_twh', [], ExcelValue.by_value
  attach_function 'load_factor_average_low_carbon', [], ExcelValue.by_value
  attach_function 'load_factor_demand', [], ExcelValue.by_value
  attach_function 'load_factor_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'load_factor_high_carbon', [], ExcelValue.by_value
  attach_function 'load_factor_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'maximum_industry_contraction', [], ExcelValue.by_value
  attach_function 'maximum_industry_expansion', [], ExcelValue.by_value
  attach_function 'mean_demand', [], ExcelValue.by_value
  attach_function 'minimum_build_rate', [], ExcelValue.by_value
  attach_function 'peak_demand', [], ExcelValue.by_value
  attach_function 'proportion_of_build_rate_to_2020_that_is_wind_rest_is_bio', [], ExcelValue.by_value
  attach_function 'proportion_of_second_build_that_is_wind', [], ExcelValue.by_value
  attach_function 'twh_per_gw', [], ExcelValue.by_value
  attach_function 'year_electricity_demand_starts_to_increase', [], ExcelValue.by_value
  attach_function 'year_second_wave_of_building_starts', [], ExcelValue.by_value
  attach_function 'set_n_2012_onwards_electricity_demand_growth_rate', [ExcelValue.by_value], :void
  attach_function 'set_n_2020_fossil_fuel_emissions_factor', [ExcelValue.by_value], :void
  attach_function 'set_n_2020_non_renewable_low_carbon_generation_i_e_nuclear_ccs', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_electricity_demand', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_fossil_fuel_emissions_factor', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_maximum_electricity_demand', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_minimum_electricity_demand', [ExcelValue.by_value], :void
  attach_function 'set_annual_change_in_non_electricity_traded_emissions', [ExcelValue.by_value], :void
  attach_function 'set_average_life_high_carbon', [ExcelValue.by_value], :void
  attach_function 'set_average_life_other_low_carbon', [ExcelValue.by_value], :void
  attach_function 'set_average_life_wind', [ExcelValue.by_value], :void
  attach_function 'set_build_rate_from_now_to_2020', [ExcelValue.by_value], :void
  attach_function 'set_build_rate_target_in_second_build', [ExcelValue.by_value], :void
  attach_function 'set_cb2_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_cb3_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_cb4_current_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_cb4_revised_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_maximum_industry_contraction', [ExcelValue.by_value], :void
  attach_function 'set_maximum_industry_expansion', [ExcelValue.by_value], :void
  attach_function 'set_minimum_build_rate', [ExcelValue.by_value], :void
  attach_function 'set_proportion_of_build_rate_to_2020_that_is_wind_rest_is_bio', [ExcelValue.by_value], :void
  attach_function 'set_proportion_of_second_build_that_is_wind', [ExcelValue.by_value], :void
  attach_function 'set_year_electricity_demand_starts_to_increase', [ExcelValue.by_value], :void
  attach_function 'set_year_second_wave_of_building_starts', [ExcelValue.by_value], :void
  # End of named references
end
