require 'ffi'
require 'singleton'

class ModelShim

  # WARNING: this is not thread safe
  def initialize
    reset
  end

  def reset
    Model.reset
  end

  def method_missing(name, *arguments)
    if arguments.size == 0
      get(name)
    elsif arguments.size == 1
      set(name, arguments.first)
    else
      super
    end 
  end

  def get(name)
    return 0 unless Model.respond_to?(name)
    ruby_value_from_excel_value(Model.send(name))
  end

  def ruby_value_from_excel_value(excel_value)
    case excel_value[:type]
    when :ExcelNumber; excel_value[:number]
    when :ExcelString; excel_value[:string].read_string.force_encoding("utf-8")
    when :ExcelBoolean; excel_value[:number] == 1
    when :ExcelEmpty; nil
    when :ExcelRange
      r = excel_value[:rows]
      c = excel_value[:columns]
      p = excel_value[:array]
      s = Model::ExcelValue.size
      a = Array.new(r) { Array.new(c) }
      (0...r).each do |row|
        (0...c).each do |column|
          a[row][column] = ruby_value_from_excel_value(Model::ExcelValue.new(p + (((row*c)+column)*s)))
        end
      end 
      return a
    when :ExcelError; [:value,:name,:div0,:ref,:na][excel_value[:number]]
    else
      raise Exception.new("ExcelValue type #{excel_value[:type].inspect} not recognised")
    end
  end

  def set(name, ruby_value)
    name = name.to_s
    name = "set_#{name[0..-2]}" if name.end_with?('=')
    return false unless Model.respond_to?(name)
    Model.send(name, excel_value_from_ruby_value(ruby_value))
  end

  def excel_value_from_ruby_value(ruby_value, excel_value = Model::ExcelValue.new)
    case ruby_value
    when Numeric
      excel_value[:type] = :ExcelNumber
      excel_value[:number] = ruby_value
    when String
      excel_value[:type] = :ExcelString
      excel_value[:string] = FFI::MemoryPointer.from_string(ruby_value.encode('utf-8'))
    when TrueClass, FalseClass
      excel_value[:type] = :ExcelBoolean
      excel_value[:number] = ruby_value ? 1 : 0
    when nil
      excel_value[:type] = :ExcelEmpty
    when Array
      excel_value[:type] = :ExcelRange
      # Presumed to be a row unless specified otherwise
      if ruby_value.first.is_a?(Array)
        excel_value[:rows] = ruby_value.size
        excel_value[:columns] = ruby_value.first.size
      else
        excel_value[:rows] = 1
        excel_value[:columns] = ruby_value.size
      end
      ruby_values = ruby_value.flatten
      pointer = FFI::MemoryPointer.new(Model::ExcelValue, ruby_values.size)
      excel_value[:array] = pointer
      ruby_values.each.with_index do |v,i|
        excel_value_from_ruby_value(v, Model::ExcelValue.new(pointer[i]))
      end
    when Symbol
      excel_value[:type] = :ExcelError
      excel_value[:number] = [:value, :name, :div0, :ref, :na].index(ruby_value)
    else
      raise Exception.new("Ruby value #{ruby_value.inspect} not translatable into excel")
    end
    excel_value
  end

end
    

module Model
  extend FFI::Library
  ffi_lib  File.join(File.dirname(__FILE__),FFI.map_library_name('model'))
  ExcelType = enum :ExcelEmpty, :ExcelNumber, :ExcelString, :ExcelBoolean, :ExcelError, :ExcelRange
                
  class ExcelValue < FFI::Struct
    layout :type, ExcelType,
  	       :number, :double,
  	       :string, :pointer,
         	 :array, :pointer,
           :rows, :int,
           :columns, :int             
  end
  

  # use this function to reset all cell values
  attach_function 'reset', [], :void

  # start of Model
  attach_function 'set_model_c15', [ExcelValue.by_value], :void
  attach_function 'set_model_c16', [ExcelValue.by_value], :void
  attach_function 'set_model_c17', [ExcelValue.by_value], :void
  attach_function 'set_model_c18', [ExcelValue.by_value], :void
  attach_function 'set_model_c19', [ExcelValue.by_value], :void
  attach_function 'set_model_c20', [ExcelValue.by_value], :void
  attach_function 'set_model_c21', [ExcelValue.by_value], :void
  attach_function 'set_model_c22', [ExcelValue.by_value], :void
  attach_function 'set_model_c23', [ExcelValue.by_value], :void
  attach_function 'set_model_c24', [ExcelValue.by_value], :void
  attach_function 'set_model_c25', [ExcelValue.by_value], :void
  attach_function 'set_model_c26', [ExcelValue.by_value], :void
  attach_function 'set_model_c27', [ExcelValue.by_value], :void
  attach_function 'set_model_c28', [ExcelValue.by_value], :void
  attach_function 'set_model_c29', [ExcelValue.by_value], :void
  attach_function 'set_model_c30', [ExcelValue.by_value], :void
  attach_function 'set_model_c31', [ExcelValue.by_value], :void
  attach_function 'set_model_c34', [ExcelValue.by_value], :void
  attach_function 'set_model_c35', [ExcelValue.by_value], :void
  attach_function 'set_model_c36', [ExcelValue.by_value], :void
  attach_function 'set_model_c37', [ExcelValue.by_value], :void
  attach_function 'set_model_c38', [ExcelValue.by_value], :void
  attach_function 'set_model_c39', [ExcelValue.by_value], :void
  attach_function 'set_model_c40', [ExcelValue.by_value], :void
  attach_function 'set_model_c57', [ExcelValue.by_value], :void
  attach_function 'set_model_b65', [ExcelValue.by_value], :void
  attach_function 'set_model_b66', [ExcelValue.by_value], :void
  attach_function 'set_model_c82', [ExcelValue.by_value], :void
  attach_function 'set_model_d82', [ExcelValue.by_value], :void
  attach_function 'set_model_e82', [ExcelValue.by_value], :void
  attach_function 'set_model_f82', [ExcelValue.by_value], :void
  attach_function 'set_model_g82', [ExcelValue.by_value], :void
  attach_function 'set_model_h82', [ExcelValue.by_value], :void
  attach_function 'set_model_i82', [ExcelValue.by_value], :void
  attach_function 'set_model_j82', [ExcelValue.by_value], :void
  attach_function 'set_model_k82', [ExcelValue.by_value], :void
  attach_function 'set_model_l82', [ExcelValue.by_value], :void
  attach_function 'set_model_m82', [ExcelValue.by_value], :void
  attach_function 'set_model_n82', [ExcelValue.by_value], :void
  attach_function 'set_model_o82', [ExcelValue.by_value], :void
  attach_function 'set_model_p82', [ExcelValue.by_value], :void
  attach_function 'set_model_q82', [ExcelValue.by_value], :void
  attach_function 'set_model_r82', [ExcelValue.by_value], :void
  attach_function 'set_model_s82', [ExcelValue.by_value], :void
  attach_function 'set_model_t82', [ExcelValue.by_value], :void
  attach_function 'set_model_u82', [ExcelValue.by_value], :void
  attach_function 'set_model_v82', [ExcelValue.by_value], :void
  attach_function 'set_model_w82', [ExcelValue.by_value], :void
  attach_function 'set_model_x82', [ExcelValue.by_value], :void
  attach_function 'set_model_y82', [ExcelValue.by_value], :void
  attach_function 'set_model_z82', [ExcelValue.by_value], :void
  attach_function 'set_model_aa82', [ExcelValue.by_value], :void
  attach_function 'set_model_ab82', [ExcelValue.by_value], :void
  attach_function 'set_model_ac82', [ExcelValue.by_value], :void
  attach_function 'set_model_ad82', [ExcelValue.by_value], :void
  attach_function 'set_model_ae82', [ExcelValue.by_value], :void
  attach_function 'set_model_af82', [ExcelValue.by_value], :void
  attach_function 'set_model_ag82', [ExcelValue.by_value], :void
  attach_function 'set_model_ah82', [ExcelValue.by_value], :void
  attach_function 'set_model_ai82', [ExcelValue.by_value], :void
  attach_function 'set_model_aj82', [ExcelValue.by_value], :void
  attach_function 'set_model_ak82', [ExcelValue.by_value], :void
  attach_function 'set_model_al82', [ExcelValue.by_value], :void
  attach_function 'set_model_am82', [ExcelValue.by_value], :void
  attach_function 'set_model_an82', [ExcelValue.by_value], :void
  attach_function 'set_model_ao82', [ExcelValue.by_value], :void
  attach_function 'set_model_c84', [ExcelValue.by_value], :void
  attach_function 'set_model_d84', [ExcelValue.by_value], :void
  attach_function 'set_model_e84', [ExcelValue.by_value], :void
  attach_function 'set_model_f84', [ExcelValue.by_value], :void
  attach_function 'set_model_g84', [ExcelValue.by_value], :void
  attach_function 'set_model_h84', [ExcelValue.by_value], :void
  attach_function 'set_model_i84', [ExcelValue.by_value], :void
  attach_function 'set_model_j84', [ExcelValue.by_value], :void
  attach_function 'set_model_k84', [ExcelValue.by_value], :void
  attach_function 'set_model_l84', [ExcelValue.by_value], :void
  attach_function 'set_model_m84', [ExcelValue.by_value], :void
  attach_function 'set_model_n84', [ExcelValue.by_value], :void
  attach_function 'set_model_o84', [ExcelValue.by_value], :void
  attach_function 'set_model_p84', [ExcelValue.by_value], :void
  attach_function 'set_model_q84', [ExcelValue.by_value], :void
  attach_function 'set_model_r84', [ExcelValue.by_value], :void
  attach_function 'set_model_s84', [ExcelValue.by_value], :void
  attach_function 'set_model_t84', [ExcelValue.by_value], :void
  attach_function 'set_model_u84', [ExcelValue.by_value], :void
  attach_function 'set_model_v84', [ExcelValue.by_value], :void
  attach_function 'set_model_w84', [ExcelValue.by_value], :void
  attach_function 'set_model_x84', [ExcelValue.by_value], :void
  attach_function 'set_model_y84', [ExcelValue.by_value], :void
  attach_function 'set_model_z84', [ExcelValue.by_value], :void
  attach_function 'set_model_aa84', [ExcelValue.by_value], :void
  attach_function 'set_model_ab84', [ExcelValue.by_value], :void
  attach_function 'set_model_ac84', [ExcelValue.by_value], :void
  attach_function 'set_model_ad84', [ExcelValue.by_value], :void
  attach_function 'set_model_ae84', [ExcelValue.by_value], :void
  attach_function 'set_model_af84', [ExcelValue.by_value], :void
  attach_function 'set_model_ag84', [ExcelValue.by_value], :void
  attach_function 'set_model_ah84', [ExcelValue.by_value], :void
  attach_function 'set_model_ai84', [ExcelValue.by_value], :void
  attach_function 'set_model_aj84', [ExcelValue.by_value], :void
  attach_function 'set_model_ak84', [ExcelValue.by_value], :void
  attach_function 'set_model_al84', [ExcelValue.by_value], :void
  attach_function 'set_model_am84', [ExcelValue.by_value], :void
  attach_function 'set_model_an84', [ExcelValue.by_value], :void
  attach_function 'set_model_ao84', [ExcelValue.by_value], :void
  attach_function 'set_model_b88', [ExcelValue.by_value], :void
  attach_function 'set_model_b89', [ExcelValue.by_value], :void
  attach_function 'set_model_b90', [ExcelValue.by_value], :void
  attach_function 'set_model_b91', [ExcelValue.by_value], :void
  attach_function 'set_model_d93', [ExcelValue.by_value], :void
  attach_function 'set_model_e93', [ExcelValue.by_value], :void
  attach_function 'set_model_f93', [ExcelValue.by_value], :void
  attach_function 'set_model_g93', [ExcelValue.by_value], :void
  attach_function 'set_model_h93', [ExcelValue.by_value], :void
  attach_function 'set_model_i93', [ExcelValue.by_value], :void
  attach_function 'set_model_j93', [ExcelValue.by_value], :void
  attach_function 'set_model_k93', [ExcelValue.by_value], :void
  attach_function 'set_model_l93', [ExcelValue.by_value], :void
  attach_function 'set_model_m93', [ExcelValue.by_value], :void
  attach_function 'set_model_n93', [ExcelValue.by_value], :void
  attach_function 'set_model_o93', [ExcelValue.by_value], :void
  attach_function 'set_model_p93', [ExcelValue.by_value], :void
  attach_function 'set_model_q93', [ExcelValue.by_value], :void
  attach_function 'set_model_r93', [ExcelValue.by_value], :void
  attach_function 'set_model_s93', [ExcelValue.by_value], :void
  attach_function 'set_model_t93', [ExcelValue.by_value], :void
  attach_function 'set_model_u93', [ExcelValue.by_value], :void
  attach_function 'set_model_v93', [ExcelValue.by_value], :void
  attach_function 'set_model_w93', [ExcelValue.by_value], :void
  attach_function 'set_model_x93', [ExcelValue.by_value], :void
  attach_function 'set_model_y93', [ExcelValue.by_value], :void
  attach_function 'set_model_z93', [ExcelValue.by_value], :void
  attach_function 'set_model_aa93', [ExcelValue.by_value], :void
  attach_function 'set_model_ab93', [ExcelValue.by_value], :void
  attach_function 'set_model_ac93', [ExcelValue.by_value], :void
  attach_function 'set_model_ad93', [ExcelValue.by_value], :void
  attach_function 'set_model_ae93', [ExcelValue.by_value], :void
  attach_function 'set_model_af93', [ExcelValue.by_value], :void
  attach_function 'set_model_ag93', [ExcelValue.by_value], :void
  attach_function 'set_model_ah93', [ExcelValue.by_value], :void
  attach_function 'set_model_ai93', [ExcelValue.by_value], :void
  attach_function 'set_model_aj93', [ExcelValue.by_value], :void
  attach_function 'set_model_ak93', [ExcelValue.by_value], :void
  attach_function 'set_model_al93', [ExcelValue.by_value], :void
  attach_function 'set_model_am93', [ExcelValue.by_value], :void
  attach_function 'set_model_an93', [ExcelValue.by_value], :void
  attach_function 'set_model_ao93', [ExcelValue.by_value], :void
  attach_function 'set_model_c96', [ExcelValue.by_value], :void
  attach_function 'set_model_d96', [ExcelValue.by_value], :void
  attach_function 'set_model_e96', [ExcelValue.by_value], :void
  attach_function 'set_model_f96', [ExcelValue.by_value], :void
  attach_function 'set_model_g96', [ExcelValue.by_value], :void
  attach_function 'set_model_h96', [ExcelValue.by_value], :void
  attach_function 'set_model_i96', [ExcelValue.by_value], :void
  attach_function 'set_model_j96', [ExcelValue.by_value], :void
  attach_function 'set_model_k96', [ExcelValue.by_value], :void
  attach_function 'set_model_l96', [ExcelValue.by_value], :void
  attach_function 'set_model_m96', [ExcelValue.by_value], :void
  attach_function 'set_model_n96', [ExcelValue.by_value], :void
  attach_function 'set_model_o96', [ExcelValue.by_value], :void
  attach_function 'set_model_p96', [ExcelValue.by_value], :void
  attach_function 'set_model_q96', [ExcelValue.by_value], :void
  attach_function 'set_model_r96', [ExcelValue.by_value], :void
  attach_function 'set_model_s96', [ExcelValue.by_value], :void
  attach_function 'set_model_t96', [ExcelValue.by_value], :void
  attach_function 'set_model_u96', [ExcelValue.by_value], :void
  attach_function 'set_model_v96', [ExcelValue.by_value], :void
  attach_function 'set_model_w96', [ExcelValue.by_value], :void
  attach_function 'set_model_x96', [ExcelValue.by_value], :void
  attach_function 'set_model_y96', [ExcelValue.by_value], :void
  attach_function 'set_model_z96', [ExcelValue.by_value], :void
  attach_function 'set_model_aa96', [ExcelValue.by_value], :void
  attach_function 'set_model_ab96', [ExcelValue.by_value], :void
  attach_function 'set_model_ac96', [ExcelValue.by_value], :void
  attach_function 'set_model_ad96', [ExcelValue.by_value], :void
  attach_function 'set_model_ae96', [ExcelValue.by_value], :void
  attach_function 'set_model_af96', [ExcelValue.by_value], :void
  attach_function 'set_model_ag96', [ExcelValue.by_value], :void
  attach_function 'set_model_ah96', [ExcelValue.by_value], :void
  attach_function 'set_model_ai96', [ExcelValue.by_value], :void
  attach_function 'set_model_aj96', [ExcelValue.by_value], :void
  attach_function 'set_model_ak96', [ExcelValue.by_value], :void
  attach_function 'set_model_al96', [ExcelValue.by_value], :void
  attach_function 'set_model_am96', [ExcelValue.by_value], :void
  attach_function 'set_model_an96', [ExcelValue.by_value], :void
  attach_function 'set_model_ao96', [ExcelValue.by_value], :void
  attach_function 'set_model_b99', [ExcelValue.by_value], :void
  attach_function 'set_model_b100', [ExcelValue.by_value], :void
  attach_function 'set_model_b101', [ExcelValue.by_value], :void
  attach_function 'set_model_b102', [ExcelValue.by_value], :void
  attach_function 'set_model_c107', [ExcelValue.by_value], :void
  attach_function 'set_model_d107', [ExcelValue.by_value], :void
  attach_function 'set_model_e107', [ExcelValue.by_value], :void
  attach_function 'set_model_f107', [ExcelValue.by_value], :void
  attach_function 'set_model_g107', [ExcelValue.by_value], :void
  attach_function 'set_model_h107', [ExcelValue.by_value], :void
  attach_function 'set_model_i107', [ExcelValue.by_value], :void
  attach_function 'set_model_j107', [ExcelValue.by_value], :void
  attach_function 'set_model_k107', [ExcelValue.by_value], :void
  attach_function 'set_model_l107', [ExcelValue.by_value], :void
  attach_function 'set_model_m107', [ExcelValue.by_value], :void
  attach_function 'set_model_n107', [ExcelValue.by_value], :void
  attach_function 'set_model_o107', [ExcelValue.by_value], :void
  attach_function 'set_model_p107', [ExcelValue.by_value], :void
  attach_function 'set_model_q107', [ExcelValue.by_value], :void
  attach_function 'set_model_r107', [ExcelValue.by_value], :void
  attach_function 'set_model_s107', [ExcelValue.by_value], :void
  attach_function 'set_model_t107', [ExcelValue.by_value], :void
  attach_function 'set_model_u107', [ExcelValue.by_value], :void
  attach_function 'set_model_v107', [ExcelValue.by_value], :void
  attach_function 'set_model_w107', [ExcelValue.by_value], :void
  attach_function 'set_model_x107', [ExcelValue.by_value], :void
  attach_function 'set_model_y107', [ExcelValue.by_value], :void
  attach_function 'set_model_z107', [ExcelValue.by_value], :void
  attach_function 'set_model_aa107', [ExcelValue.by_value], :void
  attach_function 'set_model_ab107', [ExcelValue.by_value], :void
  attach_function 'set_model_ac107', [ExcelValue.by_value], :void
  attach_function 'set_model_ad107', [ExcelValue.by_value], :void
  attach_function 'set_model_ae107', [ExcelValue.by_value], :void
  attach_function 'set_model_af107', [ExcelValue.by_value], :void
  attach_function 'set_model_ag107', [ExcelValue.by_value], :void
  attach_function 'set_model_ah107', [ExcelValue.by_value], :void
  attach_function 'set_model_ai107', [ExcelValue.by_value], :void
  attach_function 'set_model_aj107', [ExcelValue.by_value], :void
  attach_function 'set_model_ak107', [ExcelValue.by_value], :void
  attach_function 'set_model_al107', [ExcelValue.by_value], :void
  attach_function 'set_model_am107', [ExcelValue.by_value], :void
  attach_function 'set_model_an107', [ExcelValue.by_value], :void
  attach_function 'set_model_ao107', [ExcelValue.by_value], :void
  attach_function 'set_model_c115', [ExcelValue.by_value], :void
  attach_function 'set_model_d115', [ExcelValue.by_value], :void
  attach_function 'set_model_e115', [ExcelValue.by_value], :void
  attach_function 'set_model_f115', [ExcelValue.by_value], :void
  attach_function 'set_model_g115', [ExcelValue.by_value], :void
  attach_function 'set_model_h115', [ExcelValue.by_value], :void
  attach_function 'set_model_i115', [ExcelValue.by_value], :void
  attach_function 'set_model_j115', [ExcelValue.by_value], :void
  attach_function 'set_model_k115', [ExcelValue.by_value], :void
  attach_function 'set_model_l115', [ExcelValue.by_value], :void
  attach_function 'set_model_m115', [ExcelValue.by_value], :void
  attach_function 'set_model_n115', [ExcelValue.by_value], :void
  attach_function 'set_model_o115', [ExcelValue.by_value], :void
  attach_function 'set_model_p115', [ExcelValue.by_value], :void
  attach_function 'set_model_q115', [ExcelValue.by_value], :void
  attach_function 'set_model_r115', [ExcelValue.by_value], :void
  attach_function 'set_model_s115', [ExcelValue.by_value], :void
  attach_function 'set_model_t115', [ExcelValue.by_value], :void
  attach_function 'set_model_u115', [ExcelValue.by_value], :void
  attach_function 'set_model_v115', [ExcelValue.by_value], :void
  attach_function 'set_model_w115', [ExcelValue.by_value], :void
  attach_function 'set_model_x115', [ExcelValue.by_value], :void
  attach_function 'set_model_y115', [ExcelValue.by_value], :void
  attach_function 'set_model_z115', [ExcelValue.by_value], :void
  attach_function 'set_model_aa115', [ExcelValue.by_value], :void
  attach_function 'set_model_ab115', [ExcelValue.by_value], :void
  attach_function 'set_model_ac115', [ExcelValue.by_value], :void
  attach_function 'set_model_ad115', [ExcelValue.by_value], :void
  attach_function 'set_model_ae115', [ExcelValue.by_value], :void
  attach_function 'set_model_af115', [ExcelValue.by_value], :void
  attach_function 'set_model_ag115', [ExcelValue.by_value], :void
  attach_function 'set_model_ah115', [ExcelValue.by_value], :void
  attach_function 'set_model_ai115', [ExcelValue.by_value], :void
  attach_function 'set_model_aj115', [ExcelValue.by_value], :void
  attach_function 'set_model_ak115', [ExcelValue.by_value], :void
  attach_function 'set_model_al115', [ExcelValue.by_value], :void
  attach_function 'set_model_am115', [ExcelValue.by_value], :void
  attach_function 'set_model_an115', [ExcelValue.by_value], :void
  attach_function 'set_model_ao115', [ExcelValue.by_value], :void
  attach_function 'set_model_c120', [ExcelValue.by_value], :void
  attach_function 'model_c31', [], ExcelValue.by_value
  attach_function 'model_c24', [], ExcelValue.by_value
  attach_function 'model_c26', [], ExcelValue.by_value
  attach_function 'model_c63', [], ExcelValue.by_value
  attach_function 'model_d63', [], ExcelValue.by_value
  attach_function 'model_e63', [], ExcelValue.by_value
  attach_function 'model_f63', [], ExcelValue.by_value
  attach_function 'model_g63', [], ExcelValue.by_value
  attach_function 'model_h63', [], ExcelValue.by_value
  attach_function 'model_i63', [], ExcelValue.by_value
  attach_function 'model_j63', [], ExcelValue.by_value
  attach_function 'model_k63', [], ExcelValue.by_value
  attach_function 'model_l63', [], ExcelValue.by_value
  attach_function 'model_m63', [], ExcelValue.by_value
  attach_function 'model_n63', [], ExcelValue.by_value
  attach_function 'model_o63', [], ExcelValue.by_value
  attach_function 'model_p63', [], ExcelValue.by_value
  attach_function 'model_q63', [], ExcelValue.by_value
  attach_function 'model_r63', [], ExcelValue.by_value
  attach_function 'model_s63', [], ExcelValue.by_value
  attach_function 'model_t63', [], ExcelValue.by_value
  attach_function 'model_u63', [], ExcelValue.by_value
  attach_function 'model_v63', [], ExcelValue.by_value
  attach_function 'model_w63', [], ExcelValue.by_value
  attach_function 'model_x63', [], ExcelValue.by_value
  attach_function 'model_y63', [], ExcelValue.by_value
  attach_function 'model_z63', [], ExcelValue.by_value
  attach_function 'model_aa63', [], ExcelValue.by_value
  attach_function 'model_ab63', [], ExcelValue.by_value
  attach_function 'model_ac63', [], ExcelValue.by_value
  attach_function 'model_ad63', [], ExcelValue.by_value
  attach_function 'model_ae63', [], ExcelValue.by_value
  attach_function 'model_af63', [], ExcelValue.by_value
  attach_function 'model_ag63', [], ExcelValue.by_value
  attach_function 'model_ah63', [], ExcelValue.by_value
  attach_function 'model_ai63', [], ExcelValue.by_value
  attach_function 'model_aj63', [], ExcelValue.by_value
  attach_function 'model_ak63', [], ExcelValue.by_value
  attach_function 'model_al63', [], ExcelValue.by_value
  attach_function 'model_am63', [], ExcelValue.by_value
  attach_function 'model_an63', [], ExcelValue.by_value
  attach_function 'model_ao63', [], ExcelValue.by_value
  attach_function 'model_c16', [], ExcelValue.by_value
  attach_function 'model_c34', [], ExcelValue.by_value
  attach_function 'model_c15', [], ExcelValue.by_value
  attach_function 'model_k20', [], ExcelValue.by_value
  attach_function 'model_k15', [], ExcelValue.by_value
  attach_function 'model_c17', [], ExcelValue.by_value
  attach_function 'model_c119', [], ExcelValue.by_value
  attach_function 'model_d119', [], ExcelValue.by_value
  attach_function 'model_e119', [], ExcelValue.by_value
  attach_function 'model_f119', [], ExcelValue.by_value
  attach_function 'model_g119', [], ExcelValue.by_value
  attach_function 'model_h119', [], ExcelValue.by_value
  attach_function 'model_i119', [], ExcelValue.by_value
  attach_function 'model_j119', [], ExcelValue.by_value
  attach_function 'model_k119', [], ExcelValue.by_value
  attach_function 'model_l119', [], ExcelValue.by_value
  attach_function 'model_m119', [], ExcelValue.by_value
  attach_function 'model_n119', [], ExcelValue.by_value
  attach_function 'model_o119', [], ExcelValue.by_value
  attach_function 'model_p119', [], ExcelValue.by_value
  attach_function 'model_q119', [], ExcelValue.by_value
  attach_function 'model_r119', [], ExcelValue.by_value
  attach_function 'model_s119', [], ExcelValue.by_value
  attach_function 'model_t119', [], ExcelValue.by_value
  attach_function 'model_u119', [], ExcelValue.by_value
  attach_function 'model_v119', [], ExcelValue.by_value
  attach_function 'model_w119', [], ExcelValue.by_value
  attach_function 'model_x119', [], ExcelValue.by_value
  attach_function 'model_y119', [], ExcelValue.by_value
  attach_function 'model_z119', [], ExcelValue.by_value
  attach_function 'model_aa119', [], ExcelValue.by_value
  attach_function 'model_ab119', [], ExcelValue.by_value
  attach_function 'model_ac119', [], ExcelValue.by_value
  attach_function 'model_ad119', [], ExcelValue.by_value
  attach_function 'model_ae119', [], ExcelValue.by_value
  attach_function 'model_af119', [], ExcelValue.by_value
  attach_function 'model_ag119', [], ExcelValue.by_value
  attach_function 'model_ah119', [], ExcelValue.by_value
  attach_function 'model_ai119', [], ExcelValue.by_value
  attach_function 'model_aj119', [], ExcelValue.by_value
  attach_function 'model_ak119', [], ExcelValue.by_value
  attach_function 'model_al119', [], ExcelValue.by_value
  attach_function 'model_am119', [], ExcelValue.by_value
  attach_function 'model_an119', [], ExcelValue.by_value
  attach_function 'model_ao119', [], ExcelValue.by_value
  attach_function 'model_c117', [], ExcelValue.by_value
  attach_function 'model_d117', [], ExcelValue.by_value
  attach_function 'model_e117', [], ExcelValue.by_value
  attach_function 'model_f117', [], ExcelValue.by_value
  attach_function 'model_g117', [], ExcelValue.by_value
  attach_function 'model_h117', [], ExcelValue.by_value
  attach_function 'model_i117', [], ExcelValue.by_value
  attach_function 'model_j117', [], ExcelValue.by_value
  attach_function 'model_k117', [], ExcelValue.by_value
  attach_function 'model_l117', [], ExcelValue.by_value
  attach_function 'model_m117', [], ExcelValue.by_value
  attach_function 'model_n117', [], ExcelValue.by_value
  attach_function 'model_o117', [], ExcelValue.by_value
  attach_function 'model_p117', [], ExcelValue.by_value
  attach_function 'model_q117', [], ExcelValue.by_value
  attach_function 'model_r117', [], ExcelValue.by_value
  attach_function 'model_s117', [], ExcelValue.by_value
  attach_function 'model_t117', [], ExcelValue.by_value
  attach_function 'model_u117', [], ExcelValue.by_value
  attach_function 'model_v117', [], ExcelValue.by_value
  attach_function 'model_w117', [], ExcelValue.by_value
  attach_function 'model_x117', [], ExcelValue.by_value
  attach_function 'model_y117', [], ExcelValue.by_value
  attach_function 'model_z117', [], ExcelValue.by_value
  attach_function 'model_aa117', [], ExcelValue.by_value
  attach_function 'model_ab117', [], ExcelValue.by_value
  attach_function 'model_ac117', [], ExcelValue.by_value
  attach_function 'model_ad117', [], ExcelValue.by_value
  attach_function 'model_ae117', [], ExcelValue.by_value
  attach_function 'model_af117', [], ExcelValue.by_value
  attach_function 'model_ag117', [], ExcelValue.by_value
  attach_function 'model_ah117', [], ExcelValue.by_value
  attach_function 'model_ai117', [], ExcelValue.by_value
  attach_function 'model_aj117', [], ExcelValue.by_value
  attach_function 'model_ak117', [], ExcelValue.by_value
  attach_function 'model_al117', [], ExcelValue.by_value
  attach_function 'model_am117', [], ExcelValue.by_value
  attach_function 'model_an117', [], ExcelValue.by_value
  attach_function 'model_ao117', [], ExcelValue.by_value
  attach_function 'model_k17', [], ExcelValue.by_value
  attach_function 'model_k18', [], ExcelValue.by_value
  attach_function 'model_k19', [], ExcelValue.by_value
  attach_function 'model_c111', [], ExcelValue.by_value
  attach_function 'model_d111', [], ExcelValue.by_value
  attach_function 'model_e111', [], ExcelValue.by_value
  attach_function 'model_f111', [], ExcelValue.by_value
  attach_function 'model_g111', [], ExcelValue.by_value
  attach_function 'model_h111', [], ExcelValue.by_value
  attach_function 'model_i111', [], ExcelValue.by_value
  attach_function 'model_j111', [], ExcelValue.by_value
  attach_function 'model_k111', [], ExcelValue.by_value
  attach_function 'model_l111', [], ExcelValue.by_value
  attach_function 'model_m111', [], ExcelValue.by_value
  attach_function 'model_n111', [], ExcelValue.by_value
  attach_function 'model_o111', [], ExcelValue.by_value
  attach_function 'model_p111', [], ExcelValue.by_value
  attach_function 'model_q111', [], ExcelValue.by_value
  attach_function 'model_r111', [], ExcelValue.by_value
  attach_function 'model_s111', [], ExcelValue.by_value
  attach_function 'model_t111', [], ExcelValue.by_value
  attach_function 'model_u111', [], ExcelValue.by_value
  attach_function 'model_v111', [], ExcelValue.by_value
  attach_function 'model_w111', [], ExcelValue.by_value
  attach_function 'model_x111', [], ExcelValue.by_value
  attach_function 'model_y111', [], ExcelValue.by_value
  attach_function 'model_z111', [], ExcelValue.by_value
  attach_function 'model_aa111', [], ExcelValue.by_value
  attach_function 'model_ab111', [], ExcelValue.by_value
  attach_function 'model_ac111', [], ExcelValue.by_value
  attach_function 'model_ad111', [], ExcelValue.by_value
  attach_function 'model_ae111', [], ExcelValue.by_value
  attach_function 'model_af111', [], ExcelValue.by_value
  attach_function 'model_ag111', [], ExcelValue.by_value
  attach_function 'model_ah111', [], ExcelValue.by_value
  attach_function 'model_ai111', [], ExcelValue.by_value
  attach_function 'model_aj111', [], ExcelValue.by_value
  attach_function 'model_ak111', [], ExcelValue.by_value
  attach_function 'model_al111', [], ExcelValue.by_value
  attach_function 'model_am111', [], ExcelValue.by_value
  attach_function 'model_an111', [], ExcelValue.by_value
  attach_function 'model_ao111', [], ExcelValue.by_value
  attach_function 'model_c116', [], ExcelValue.by_value
  attach_function 'model_d116', [], ExcelValue.by_value
  attach_function 'model_e116', [], ExcelValue.by_value
  attach_function 'model_f116', [], ExcelValue.by_value
  attach_function 'model_g116', [], ExcelValue.by_value
  attach_function 'model_h116', [], ExcelValue.by_value
  attach_function 'model_i116', [], ExcelValue.by_value
  attach_function 'model_j116', [], ExcelValue.by_value
  attach_function 'model_k116', [], ExcelValue.by_value
  attach_function 'model_l116', [], ExcelValue.by_value
  attach_function 'model_m116', [], ExcelValue.by_value
  attach_function 'model_n116', [], ExcelValue.by_value
  attach_function 'model_o116', [], ExcelValue.by_value
  attach_function 'model_p116', [], ExcelValue.by_value
  attach_function 'model_q116', [], ExcelValue.by_value
  attach_function 'model_r116', [], ExcelValue.by_value
  attach_function 'model_s116', [], ExcelValue.by_value
  attach_function 'model_t116', [], ExcelValue.by_value
  attach_function 'model_u116', [], ExcelValue.by_value
  attach_function 'model_v116', [], ExcelValue.by_value
  attach_function 'model_w116', [], ExcelValue.by_value
  attach_function 'model_x116', [], ExcelValue.by_value
  attach_function 'model_y116', [], ExcelValue.by_value
  attach_function 'model_z116', [], ExcelValue.by_value
  attach_function 'model_aa116', [], ExcelValue.by_value
  attach_function 'model_ab116', [], ExcelValue.by_value
  attach_function 'model_ac116', [], ExcelValue.by_value
  attach_function 'model_ad116', [], ExcelValue.by_value
  attach_function 'model_ae116', [], ExcelValue.by_value
  attach_function 'model_af116', [], ExcelValue.by_value
  attach_function 'model_ag116', [], ExcelValue.by_value
  attach_function 'model_ah116', [], ExcelValue.by_value
  attach_function 'model_ai116', [], ExcelValue.by_value
  attach_function 'model_aj116', [], ExcelValue.by_value
  attach_function 'model_ak116', [], ExcelValue.by_value
  attach_function 'model_al116', [], ExcelValue.by_value
  attach_function 'model_am116', [], ExcelValue.by_value
  attach_function 'model_an116', [], ExcelValue.by_value
  attach_function 'model_ao116', [], ExcelValue.by_value
  attach_function 'model_c38', [], ExcelValue.by_value
  attach_function 'model_c27', [], ExcelValue.by_value
  attach_function 'model_c28', [], ExcelValue.by_value
  attach_function 'model_c74', [], ExcelValue.by_value
  attach_function 'model_d74', [], ExcelValue.by_value
  attach_function 'model_e74', [], ExcelValue.by_value
  attach_function 'model_f74', [], ExcelValue.by_value
  attach_function 'model_g74', [], ExcelValue.by_value
  attach_function 'model_h74', [], ExcelValue.by_value
  attach_function 'model_i74', [], ExcelValue.by_value
  attach_function 'model_j74', [], ExcelValue.by_value
  attach_function 'model_k74', [], ExcelValue.by_value
  attach_function 'model_l74', [], ExcelValue.by_value
  attach_function 'model_m74', [], ExcelValue.by_value
  attach_function 'model_n74', [], ExcelValue.by_value
  attach_function 'model_o74', [], ExcelValue.by_value
  attach_function 'model_p74', [], ExcelValue.by_value
  attach_function 'model_q74', [], ExcelValue.by_value
  attach_function 'model_r74', [], ExcelValue.by_value
  attach_function 'model_s74', [], ExcelValue.by_value
  attach_function 'model_t74', [], ExcelValue.by_value
  attach_function 'model_u74', [], ExcelValue.by_value
  attach_function 'model_v74', [], ExcelValue.by_value
  attach_function 'model_w74', [], ExcelValue.by_value
  attach_function 'model_x74', [], ExcelValue.by_value
  attach_function 'model_y74', [], ExcelValue.by_value
  attach_function 'model_z74', [], ExcelValue.by_value
  attach_function 'model_aa74', [], ExcelValue.by_value
  attach_function 'model_ab74', [], ExcelValue.by_value
  attach_function 'model_ac74', [], ExcelValue.by_value
  attach_function 'model_ad74', [], ExcelValue.by_value
  attach_function 'model_ae74', [], ExcelValue.by_value
  attach_function 'model_af74', [], ExcelValue.by_value
  attach_function 'model_ag74', [], ExcelValue.by_value
  attach_function 'model_ah74', [], ExcelValue.by_value
  attach_function 'model_ai74', [], ExcelValue.by_value
  attach_function 'model_aj74', [], ExcelValue.by_value
  attach_function 'model_ak74', [], ExcelValue.by_value
  attach_function 'model_al74', [], ExcelValue.by_value
  attach_function 'model_am74', [], ExcelValue.by_value
  attach_function 'model_an74', [], ExcelValue.by_value
  attach_function 'model_ao74', [], ExcelValue.by_value
  attach_function 'model_c108', [], ExcelValue.by_value
  attach_function 'model_d108', [], ExcelValue.by_value
  attach_function 'model_e108', [], ExcelValue.by_value
  attach_function 'model_f108', [], ExcelValue.by_value
  attach_function 'model_g108', [], ExcelValue.by_value
  attach_function 'model_h108', [], ExcelValue.by_value
  attach_function 'model_i108', [], ExcelValue.by_value
  attach_function 'model_j108', [], ExcelValue.by_value
  attach_function 'model_k108', [], ExcelValue.by_value
  attach_function 'model_l108', [], ExcelValue.by_value
  attach_function 'model_m108', [], ExcelValue.by_value
  attach_function 'model_n108', [], ExcelValue.by_value
  attach_function 'model_o108', [], ExcelValue.by_value
  attach_function 'model_p108', [], ExcelValue.by_value
  attach_function 'model_q108', [], ExcelValue.by_value
  attach_function 'model_r108', [], ExcelValue.by_value
  attach_function 'model_s108', [], ExcelValue.by_value
  attach_function 'model_t108', [], ExcelValue.by_value
  attach_function 'model_u108', [], ExcelValue.by_value
  attach_function 'model_v108', [], ExcelValue.by_value
  attach_function 'model_w108', [], ExcelValue.by_value
  attach_function 'model_x108', [], ExcelValue.by_value
  attach_function 'model_y108', [], ExcelValue.by_value
  attach_function 'model_z108', [], ExcelValue.by_value
  attach_function 'model_aa108', [], ExcelValue.by_value
  attach_function 'model_ab108', [], ExcelValue.by_value
  attach_function 'model_ac108', [], ExcelValue.by_value
  attach_function 'model_ad108', [], ExcelValue.by_value
  attach_function 'model_ae108', [], ExcelValue.by_value
  attach_function 'model_af108', [], ExcelValue.by_value
  attach_function 'model_ag108', [], ExcelValue.by_value
  attach_function 'model_ah108', [], ExcelValue.by_value
  attach_function 'model_ai108', [], ExcelValue.by_value
  attach_function 'model_aj108', [], ExcelValue.by_value
  attach_function 'model_ak108', [], ExcelValue.by_value
  attach_function 'model_al108', [], ExcelValue.by_value
  attach_function 'model_am108', [], ExcelValue.by_value
  attach_function 'model_an108', [], ExcelValue.by_value
  attach_function 'model_ao108', [], ExcelValue.by_value
  attach_function 'model_c110', [], ExcelValue.by_value
  attach_function 'model_d110', [], ExcelValue.by_value
  attach_function 'model_e110', [], ExcelValue.by_value
  attach_function 'model_f110', [], ExcelValue.by_value
  attach_function 'model_g110', [], ExcelValue.by_value
  attach_function 'model_h110', [], ExcelValue.by_value
  attach_function 'model_i110', [], ExcelValue.by_value
  attach_function 'model_j110', [], ExcelValue.by_value
  attach_function 'model_k110', [], ExcelValue.by_value
  attach_function 'model_l110', [], ExcelValue.by_value
  attach_function 'model_m110', [], ExcelValue.by_value
  attach_function 'model_n110', [], ExcelValue.by_value
  attach_function 'model_o110', [], ExcelValue.by_value
  attach_function 'model_p110', [], ExcelValue.by_value
  attach_function 'model_q110', [], ExcelValue.by_value
  attach_function 'model_r110', [], ExcelValue.by_value
  attach_function 'model_s110', [], ExcelValue.by_value
  attach_function 'model_t110', [], ExcelValue.by_value
  attach_function 'model_u110', [], ExcelValue.by_value
  attach_function 'model_v110', [], ExcelValue.by_value
  attach_function 'model_w110', [], ExcelValue.by_value
  attach_function 'model_x110', [], ExcelValue.by_value
  attach_function 'model_y110', [], ExcelValue.by_value
  attach_function 'model_z110', [], ExcelValue.by_value
  attach_function 'model_aa110', [], ExcelValue.by_value
  attach_function 'model_ab110', [], ExcelValue.by_value
  attach_function 'model_ac110', [], ExcelValue.by_value
  attach_function 'model_ad110', [], ExcelValue.by_value
  attach_function 'model_ae110', [], ExcelValue.by_value
  attach_function 'model_af110', [], ExcelValue.by_value
  attach_function 'model_ag110', [], ExcelValue.by_value
  attach_function 'model_ah110', [], ExcelValue.by_value
  attach_function 'model_ai110', [], ExcelValue.by_value
  attach_function 'model_aj110', [], ExcelValue.by_value
  attach_function 'model_ak110', [], ExcelValue.by_value
  attach_function 'model_al110', [], ExcelValue.by_value
  attach_function 'model_am110', [], ExcelValue.by_value
  attach_function 'model_an110', [], ExcelValue.by_value
  attach_function 'model_ao110', [], ExcelValue.by_value
  attach_function 'model_c61', [], ExcelValue.by_value
  attach_function 'model_d61', [], ExcelValue.by_value
  attach_function 'model_e61', [], ExcelValue.by_value
  attach_function 'model_f61', [], ExcelValue.by_value
  attach_function 'model_g61', [], ExcelValue.by_value
  attach_function 'model_h61', [], ExcelValue.by_value
  attach_function 'model_i61', [], ExcelValue.by_value
  attach_function 'model_j61', [], ExcelValue.by_value
  attach_function 'model_k61', [], ExcelValue.by_value
  attach_function 'model_l61', [], ExcelValue.by_value
  attach_function 'model_m61', [], ExcelValue.by_value
  attach_function 'model_n61', [], ExcelValue.by_value
  attach_function 'model_o61', [], ExcelValue.by_value
  attach_function 'model_p61', [], ExcelValue.by_value
  attach_function 'model_q61', [], ExcelValue.by_value
  attach_function 'model_r61', [], ExcelValue.by_value
  attach_function 'model_s61', [], ExcelValue.by_value
  attach_function 'model_t61', [], ExcelValue.by_value
  attach_function 'model_u61', [], ExcelValue.by_value
  attach_function 'model_v61', [], ExcelValue.by_value
  attach_function 'model_w61', [], ExcelValue.by_value
  attach_function 'model_x61', [], ExcelValue.by_value
  attach_function 'model_y61', [], ExcelValue.by_value
  attach_function 'model_z61', [], ExcelValue.by_value
  attach_function 'model_aa61', [], ExcelValue.by_value
  attach_function 'model_ab61', [], ExcelValue.by_value
  attach_function 'model_ac61', [], ExcelValue.by_value
  attach_function 'model_ad61', [], ExcelValue.by_value
  attach_function 'model_ae61', [], ExcelValue.by_value
  attach_function 'model_af61', [], ExcelValue.by_value
  attach_function 'model_ag61', [], ExcelValue.by_value
  attach_function 'model_ah61', [], ExcelValue.by_value
  attach_function 'model_ai61', [], ExcelValue.by_value
  attach_function 'model_aj61', [], ExcelValue.by_value
  attach_function 'model_ak61', [], ExcelValue.by_value
  attach_function 'model_al61', [], ExcelValue.by_value
  attach_function 'model_am61', [], ExcelValue.by_value
  attach_function 'model_an61', [], ExcelValue.by_value
  attach_function 'model_ao61', [], ExcelValue.by_value
  attach_function 'model_c97', [], ExcelValue.by_value
  attach_function 'model_d97', [], ExcelValue.by_value
  attach_function 'model_e97', [], ExcelValue.by_value
  attach_function 'model_f97', [], ExcelValue.by_value
  attach_function 'model_g97', [], ExcelValue.by_value
  attach_function 'model_h97', [], ExcelValue.by_value
  attach_function 'model_i97', [], ExcelValue.by_value
  attach_function 'model_j97', [], ExcelValue.by_value
  attach_function 'model_k97', [], ExcelValue.by_value
  attach_function 'model_l97', [], ExcelValue.by_value
  attach_function 'model_m97', [], ExcelValue.by_value
  attach_function 'model_n97', [], ExcelValue.by_value
  attach_function 'model_o97', [], ExcelValue.by_value
  attach_function 'model_p97', [], ExcelValue.by_value
  attach_function 'model_q97', [], ExcelValue.by_value
  attach_function 'model_r97', [], ExcelValue.by_value
  attach_function 'model_s97', [], ExcelValue.by_value
  attach_function 'model_t97', [], ExcelValue.by_value
  attach_function 'model_u97', [], ExcelValue.by_value
  attach_function 'model_v97', [], ExcelValue.by_value
  attach_function 'model_w97', [], ExcelValue.by_value
  attach_function 'model_x97', [], ExcelValue.by_value
  attach_function 'model_y97', [], ExcelValue.by_value
  attach_function 'model_z97', [], ExcelValue.by_value
  attach_function 'model_aa97', [], ExcelValue.by_value
  attach_function 'model_ab97', [], ExcelValue.by_value
  attach_function 'model_ac97', [], ExcelValue.by_value
  attach_function 'model_ad97', [], ExcelValue.by_value
  attach_function 'model_ae97', [], ExcelValue.by_value
  attach_function 'model_af97', [], ExcelValue.by_value
  attach_function 'model_ag97', [], ExcelValue.by_value
  attach_function 'model_ah97', [], ExcelValue.by_value
  attach_function 'model_ai97', [], ExcelValue.by_value
  attach_function 'model_aj97', [], ExcelValue.by_value
  attach_function 'model_ak97', [], ExcelValue.by_value
  attach_function 'model_al97', [], ExcelValue.by_value
  attach_function 'model_am97', [], ExcelValue.by_value
  attach_function 'model_an97', [], ExcelValue.by_value
  attach_function 'model_ao97', [], ExcelValue.by_value
  attach_function 'model_c23', [], ExcelValue.by_value
  attach_function 'model_c20', [], ExcelValue.by_value
  attach_function 'model_c22', [], ExcelValue.by_value
  attach_function 'model_c40', [], ExcelValue.by_value
  attach_function 'model_c30', [], ExcelValue.by_value
  attach_function 'model_c81', [], ExcelValue.by_value
  attach_function 'model_d81', [], ExcelValue.by_value
  attach_function 'model_e81', [], ExcelValue.by_value
  attach_function 'model_f81', [], ExcelValue.by_value
  attach_function 'model_g81', [], ExcelValue.by_value
  attach_function 'model_h81', [], ExcelValue.by_value
  attach_function 'model_i81', [], ExcelValue.by_value
  attach_function 'model_j81', [], ExcelValue.by_value
  attach_function 'model_k81', [], ExcelValue.by_value
  attach_function 'model_l81', [], ExcelValue.by_value
  attach_function 'model_m81', [], ExcelValue.by_value
  attach_function 'model_n81', [], ExcelValue.by_value
  attach_function 'model_o81', [], ExcelValue.by_value
  attach_function 'model_p81', [], ExcelValue.by_value
  attach_function 'model_q81', [], ExcelValue.by_value
  attach_function 'model_r81', [], ExcelValue.by_value
  attach_function 'model_s81', [], ExcelValue.by_value
  attach_function 'model_t81', [], ExcelValue.by_value
  attach_function 'model_u81', [], ExcelValue.by_value
  attach_function 'model_v81', [], ExcelValue.by_value
  attach_function 'model_w81', [], ExcelValue.by_value
  attach_function 'model_x81', [], ExcelValue.by_value
  attach_function 'model_y81', [], ExcelValue.by_value
  attach_function 'model_z81', [], ExcelValue.by_value
  attach_function 'model_aa81', [], ExcelValue.by_value
  attach_function 'model_ab81', [], ExcelValue.by_value
  attach_function 'model_ac81', [], ExcelValue.by_value
  attach_function 'model_ad81', [], ExcelValue.by_value
  attach_function 'model_ae81', [], ExcelValue.by_value
  attach_function 'model_af81', [], ExcelValue.by_value
  attach_function 'model_ag81', [], ExcelValue.by_value
  attach_function 'model_ah81', [], ExcelValue.by_value
  attach_function 'model_ai81', [], ExcelValue.by_value
  attach_function 'model_aj81', [], ExcelValue.by_value
  attach_function 'model_ak81', [], ExcelValue.by_value
  attach_function 'model_al81', [], ExcelValue.by_value
  attach_function 'model_am81', [], ExcelValue.by_value
  attach_function 'model_an81', [], ExcelValue.by_value
  attach_function 'model_ao81', [], ExcelValue.by_value
  attach_function 'model_c21', [], ExcelValue.by_value
  attach_function 'model_c39', [], ExcelValue.by_value
  attach_function 'model_c29', [], ExcelValue.by_value
  attach_function 'model_c60', [], ExcelValue.by_value
  attach_function 'model_d60', [], ExcelValue.by_value
  attach_function 'model_e60', [], ExcelValue.by_value
  attach_function 'model_f60', [], ExcelValue.by_value
  attach_function 'model_g60', [], ExcelValue.by_value
  attach_function 'model_h60', [], ExcelValue.by_value
  attach_function 'model_i60', [], ExcelValue.by_value
  attach_function 'model_j60', [], ExcelValue.by_value
  attach_function 'model_k60', [], ExcelValue.by_value
  attach_function 'model_l60', [], ExcelValue.by_value
  attach_function 'model_m60', [], ExcelValue.by_value
  attach_function 'model_n60', [], ExcelValue.by_value
  attach_function 'model_o60', [], ExcelValue.by_value
  attach_function 'model_p60', [], ExcelValue.by_value
  attach_function 'model_q60', [], ExcelValue.by_value
  attach_function 'model_r60', [], ExcelValue.by_value
  attach_function 'model_s60', [], ExcelValue.by_value
  attach_function 'model_t60', [], ExcelValue.by_value
  attach_function 'model_u60', [], ExcelValue.by_value
  attach_function 'model_v60', [], ExcelValue.by_value
  attach_function 'model_w60', [], ExcelValue.by_value
  attach_function 'model_x60', [], ExcelValue.by_value
  attach_function 'model_y60', [], ExcelValue.by_value
  attach_function 'model_z60', [], ExcelValue.by_value
  attach_function 'model_aa60', [], ExcelValue.by_value
  attach_function 'model_ab60', [], ExcelValue.by_value
  attach_function 'model_ac60', [], ExcelValue.by_value
  attach_function 'model_ad60', [], ExcelValue.by_value
  attach_function 'model_ae60', [], ExcelValue.by_value
  attach_function 'model_af60', [], ExcelValue.by_value
  attach_function 'model_ag60', [], ExcelValue.by_value
  attach_function 'model_ah60', [], ExcelValue.by_value
  attach_function 'model_ai60', [], ExcelValue.by_value
  attach_function 'model_aj60', [], ExcelValue.by_value
  attach_function 'model_ak60', [], ExcelValue.by_value
  attach_function 'model_al60', [], ExcelValue.by_value
  attach_function 'model_am60', [], ExcelValue.by_value
  attach_function 'model_an60', [], ExcelValue.by_value
  attach_function 'model_ao60', [], ExcelValue.by_value
  attach_function 'model_c120', [], ExcelValue.by_value
  attach_function 'model_d120', [], ExcelValue.by_value
  attach_function 'model_e120', [], ExcelValue.by_value
  attach_function 'model_f120', [], ExcelValue.by_value
  attach_function 'model_g120', [], ExcelValue.by_value
  attach_function 'model_h120', [], ExcelValue.by_value
  attach_function 'model_i120', [], ExcelValue.by_value
  attach_function 'model_j120', [], ExcelValue.by_value
  attach_function 'model_k120', [], ExcelValue.by_value
  attach_function 'model_l120', [], ExcelValue.by_value
  attach_function 'model_m120', [], ExcelValue.by_value
  attach_function 'model_n120', [], ExcelValue.by_value
  attach_function 'model_o120', [], ExcelValue.by_value
  attach_function 'model_p120', [], ExcelValue.by_value
  attach_function 'model_q120', [], ExcelValue.by_value
  attach_function 'model_r120', [], ExcelValue.by_value
  attach_function 'model_s120', [], ExcelValue.by_value
  attach_function 'model_t120', [], ExcelValue.by_value
  attach_function 'model_u120', [], ExcelValue.by_value
  attach_function 'model_v120', [], ExcelValue.by_value
  attach_function 'model_w120', [], ExcelValue.by_value
  attach_function 'model_x120', [], ExcelValue.by_value
  attach_function 'model_y120', [], ExcelValue.by_value
  attach_function 'model_z120', [], ExcelValue.by_value
  attach_function 'model_aa120', [], ExcelValue.by_value
  attach_function 'model_ab120', [], ExcelValue.by_value
  attach_function 'model_ac120', [], ExcelValue.by_value
  attach_function 'model_ad120', [], ExcelValue.by_value
  attach_function 'model_ae120', [], ExcelValue.by_value
  attach_function 'model_af120', [], ExcelValue.by_value
  attach_function 'model_ag120', [], ExcelValue.by_value
  attach_function 'model_ah120', [], ExcelValue.by_value
  attach_function 'model_ai120', [], ExcelValue.by_value
  attach_function 'model_aj120', [], ExcelValue.by_value
  attach_function 'model_ak120', [], ExcelValue.by_value
  attach_function 'model_al120', [], ExcelValue.by_value
  attach_function 'model_am120', [], ExcelValue.by_value
  attach_function 'model_an120', [], ExcelValue.by_value
  attach_function 'model_ao120', [], ExcelValue.by_value
  attach_function 'model_c25', [], ExcelValue.by_value
  attach_function 'model_c37', [], ExcelValue.by_value
  attach_function 'model_c18', [], ExcelValue.by_value
  attach_function 'model_c36', [], ExcelValue.by_value
  attach_function 'model_c73', [], ExcelValue.by_value
  attach_function 'model_d73', [], ExcelValue.by_value
  attach_function 'model_e73', [], ExcelValue.by_value
  attach_function 'model_f73', [], ExcelValue.by_value
  attach_function 'model_g73', [], ExcelValue.by_value
  attach_function 'model_h73', [], ExcelValue.by_value
  attach_function 'model_i73', [], ExcelValue.by_value
  attach_function 'model_j73', [], ExcelValue.by_value
  attach_function 'model_k73', [], ExcelValue.by_value
  attach_function 'model_l73', [], ExcelValue.by_value
  attach_function 'model_m73', [], ExcelValue.by_value
  attach_function 'model_n73', [], ExcelValue.by_value
  attach_function 'model_o73', [], ExcelValue.by_value
  attach_function 'model_p73', [], ExcelValue.by_value
  attach_function 'model_q73', [], ExcelValue.by_value
  attach_function 'model_r73', [], ExcelValue.by_value
  attach_function 'model_s73', [], ExcelValue.by_value
  attach_function 'model_t73', [], ExcelValue.by_value
  attach_function 'model_u73', [], ExcelValue.by_value
  attach_function 'model_v73', [], ExcelValue.by_value
  attach_function 'model_w73', [], ExcelValue.by_value
  attach_function 'model_x73', [], ExcelValue.by_value
  attach_function 'model_y73', [], ExcelValue.by_value
  attach_function 'model_z73', [], ExcelValue.by_value
  attach_function 'model_aa73', [], ExcelValue.by_value
  attach_function 'model_ab73', [], ExcelValue.by_value
  attach_function 'model_ac73', [], ExcelValue.by_value
  attach_function 'model_ad73', [], ExcelValue.by_value
  attach_function 'model_ae73', [], ExcelValue.by_value
  attach_function 'model_af73', [], ExcelValue.by_value
  attach_function 'model_ag73', [], ExcelValue.by_value
  attach_function 'model_ah73', [], ExcelValue.by_value
  attach_function 'model_ai73', [], ExcelValue.by_value
  attach_function 'model_aj73', [], ExcelValue.by_value
  attach_function 'model_ak73', [], ExcelValue.by_value
  attach_function 'model_al73', [], ExcelValue.by_value
  attach_function 'model_am73', [], ExcelValue.by_value
  attach_function 'model_an73', [], ExcelValue.by_value
  attach_function 'model_ao73', [], ExcelValue.by_value
  attach_function 'model_c121', [], ExcelValue.by_value
  attach_function 'model_d121', [], ExcelValue.by_value
  attach_function 'model_e121', [], ExcelValue.by_value
  attach_function 'model_f121', [], ExcelValue.by_value
  attach_function 'model_g121', [], ExcelValue.by_value
  attach_function 'model_h121', [], ExcelValue.by_value
  attach_function 'model_i121', [], ExcelValue.by_value
  attach_function 'model_j121', [], ExcelValue.by_value
  attach_function 'model_k121', [], ExcelValue.by_value
  attach_function 'model_l121', [], ExcelValue.by_value
  attach_function 'model_m121', [], ExcelValue.by_value
  attach_function 'model_n121', [], ExcelValue.by_value
  attach_function 'model_o121', [], ExcelValue.by_value
  attach_function 'model_p121', [], ExcelValue.by_value
  attach_function 'model_q121', [], ExcelValue.by_value
  attach_function 'model_r121', [], ExcelValue.by_value
  attach_function 'model_s121', [], ExcelValue.by_value
  attach_function 'model_t121', [], ExcelValue.by_value
  attach_function 'model_u121', [], ExcelValue.by_value
  attach_function 'model_v121', [], ExcelValue.by_value
  attach_function 'model_w121', [], ExcelValue.by_value
  attach_function 'model_x121', [], ExcelValue.by_value
  attach_function 'model_y121', [], ExcelValue.by_value
  attach_function 'model_z121', [], ExcelValue.by_value
  attach_function 'model_aa121', [], ExcelValue.by_value
  attach_function 'model_ab121', [], ExcelValue.by_value
  attach_function 'model_ac121', [], ExcelValue.by_value
  attach_function 'model_ad121', [], ExcelValue.by_value
  attach_function 'model_ae121', [], ExcelValue.by_value
  attach_function 'model_af121', [], ExcelValue.by_value
  attach_function 'model_ag121', [], ExcelValue.by_value
  attach_function 'model_ah121', [], ExcelValue.by_value
  attach_function 'model_ai121', [], ExcelValue.by_value
  attach_function 'model_aj121', [], ExcelValue.by_value
  attach_function 'model_ak121', [], ExcelValue.by_value
  attach_function 'model_al121', [], ExcelValue.by_value
  attach_function 'model_am121', [], ExcelValue.by_value
  attach_function 'model_an121', [], ExcelValue.by_value
  attach_function 'model_ao121', [], ExcelValue.by_value
  attach_function 'model_c123', [], ExcelValue.by_value
  attach_function 'model_d123', [], ExcelValue.by_value
  attach_function 'model_e123', [], ExcelValue.by_value
  attach_function 'model_f123', [], ExcelValue.by_value
  attach_function 'model_g123', [], ExcelValue.by_value
  attach_function 'model_h123', [], ExcelValue.by_value
  attach_function 'model_i123', [], ExcelValue.by_value
  attach_function 'model_j123', [], ExcelValue.by_value
  attach_function 'model_k123', [], ExcelValue.by_value
  attach_function 'model_l123', [], ExcelValue.by_value
  attach_function 'model_m123', [], ExcelValue.by_value
  attach_function 'model_n123', [], ExcelValue.by_value
  attach_function 'model_o123', [], ExcelValue.by_value
  attach_function 'model_p123', [], ExcelValue.by_value
  attach_function 'model_q123', [], ExcelValue.by_value
  attach_function 'model_r123', [], ExcelValue.by_value
  attach_function 'model_s123', [], ExcelValue.by_value
  attach_function 'model_t123', [], ExcelValue.by_value
  attach_function 'model_u123', [], ExcelValue.by_value
  attach_function 'model_v123', [], ExcelValue.by_value
  attach_function 'model_w123', [], ExcelValue.by_value
  attach_function 'model_x123', [], ExcelValue.by_value
  attach_function 'model_y123', [], ExcelValue.by_value
  attach_function 'model_z123', [], ExcelValue.by_value
  attach_function 'model_aa123', [], ExcelValue.by_value
  attach_function 'model_ab123', [], ExcelValue.by_value
  attach_function 'model_ac123', [], ExcelValue.by_value
  attach_function 'model_ad123', [], ExcelValue.by_value
  attach_function 'model_ae123', [], ExcelValue.by_value
  attach_function 'model_af123', [], ExcelValue.by_value
  attach_function 'model_ag123', [], ExcelValue.by_value
  attach_function 'model_ah123', [], ExcelValue.by_value
  attach_function 'model_ai123', [], ExcelValue.by_value
  attach_function 'model_aj123', [], ExcelValue.by_value
  attach_function 'model_ak123', [], ExcelValue.by_value
  attach_function 'model_al123', [], ExcelValue.by_value
  attach_function 'model_am123', [], ExcelValue.by_value
  attach_function 'model_an123', [], ExcelValue.by_value
  attach_function 'model_ao123', [], ExcelValue.by_value
  attach_function 'model_c122', [], ExcelValue.by_value
  attach_function 'model_d122', [], ExcelValue.by_value
  attach_function 'model_e122', [], ExcelValue.by_value
  attach_function 'model_f122', [], ExcelValue.by_value
  attach_function 'model_g122', [], ExcelValue.by_value
  attach_function 'model_h122', [], ExcelValue.by_value
  attach_function 'model_i122', [], ExcelValue.by_value
  attach_function 'model_j122', [], ExcelValue.by_value
  attach_function 'model_k122', [], ExcelValue.by_value
  attach_function 'model_l122', [], ExcelValue.by_value
  attach_function 'model_m122', [], ExcelValue.by_value
  attach_function 'model_n122', [], ExcelValue.by_value
  attach_function 'model_o122', [], ExcelValue.by_value
  attach_function 'model_p122', [], ExcelValue.by_value
  attach_function 'model_q122', [], ExcelValue.by_value
  attach_function 'model_r122', [], ExcelValue.by_value
  attach_function 'model_s122', [], ExcelValue.by_value
  attach_function 'model_t122', [], ExcelValue.by_value
  attach_function 'model_u122', [], ExcelValue.by_value
  attach_function 'model_v122', [], ExcelValue.by_value
  attach_function 'model_w122', [], ExcelValue.by_value
  attach_function 'model_x122', [], ExcelValue.by_value
  attach_function 'model_y122', [], ExcelValue.by_value
  attach_function 'model_z122', [], ExcelValue.by_value
  attach_function 'model_aa122', [], ExcelValue.by_value
  attach_function 'model_ab122', [], ExcelValue.by_value
  attach_function 'model_ac122', [], ExcelValue.by_value
  attach_function 'model_ad122', [], ExcelValue.by_value
  attach_function 'model_ae122', [], ExcelValue.by_value
  attach_function 'model_af122', [], ExcelValue.by_value
  attach_function 'model_ag122', [], ExcelValue.by_value
  attach_function 'model_ah122', [], ExcelValue.by_value
  attach_function 'model_ai122', [], ExcelValue.by_value
  attach_function 'model_aj122', [], ExcelValue.by_value
  attach_function 'model_ak122', [], ExcelValue.by_value
  attach_function 'model_al122', [], ExcelValue.by_value
  attach_function 'model_am122', [], ExcelValue.by_value
  attach_function 'model_an122', [], ExcelValue.by_value
  attach_function 'model_ao122', [], ExcelValue.by_value
  attach_function 'model_c19', [], ExcelValue.by_value
  attach_function 'model_c58', [], ExcelValue.by_value
  attach_function 'model_d58', [], ExcelValue.by_value
  attach_function 'model_e58', [], ExcelValue.by_value
  attach_function 'model_f58', [], ExcelValue.by_value
  attach_function 'model_g58', [], ExcelValue.by_value
  attach_function 'model_h58', [], ExcelValue.by_value
  attach_function 'model_i58', [], ExcelValue.by_value
  attach_function 'model_j58', [], ExcelValue.by_value
  attach_function 'model_k58', [], ExcelValue.by_value
  attach_function 'model_l58', [], ExcelValue.by_value
  attach_function 'model_m58', [], ExcelValue.by_value
  attach_function 'model_n58', [], ExcelValue.by_value
  attach_function 'model_o58', [], ExcelValue.by_value
  attach_function 'model_p58', [], ExcelValue.by_value
  attach_function 'model_q58', [], ExcelValue.by_value
  attach_function 'model_r58', [], ExcelValue.by_value
  attach_function 'model_s58', [], ExcelValue.by_value
  attach_function 'model_t58', [], ExcelValue.by_value
  attach_function 'model_u58', [], ExcelValue.by_value
  attach_function 'model_v58', [], ExcelValue.by_value
  attach_function 'model_w58', [], ExcelValue.by_value
  attach_function 'model_x58', [], ExcelValue.by_value
  attach_function 'model_y58', [], ExcelValue.by_value
  attach_function 'model_z58', [], ExcelValue.by_value
  attach_function 'model_aa58', [], ExcelValue.by_value
  attach_function 'model_ab58', [], ExcelValue.by_value
  attach_function 'model_ac58', [], ExcelValue.by_value
  attach_function 'model_ad58', [], ExcelValue.by_value
  attach_function 'model_ae58', [], ExcelValue.by_value
  attach_function 'model_af58', [], ExcelValue.by_value
  attach_function 'model_ag58', [], ExcelValue.by_value
  attach_function 'model_ah58', [], ExcelValue.by_value
  attach_function 'model_ai58', [], ExcelValue.by_value
  attach_function 'model_aj58', [], ExcelValue.by_value
  attach_function 'model_ak58', [], ExcelValue.by_value
  attach_function 'model_al58', [], ExcelValue.by_value
  attach_function 'model_am58', [], ExcelValue.by_value
  attach_function 'model_an58', [], ExcelValue.by_value
  attach_function 'model_ao58', [], ExcelValue.by_value
  attach_function 'model_c59', [], ExcelValue.by_value
  attach_function 'model_d59', [], ExcelValue.by_value
  attach_function 'model_e59', [], ExcelValue.by_value
  attach_function 'model_f59', [], ExcelValue.by_value
  attach_function 'model_g59', [], ExcelValue.by_value
  attach_function 'model_h59', [], ExcelValue.by_value
  attach_function 'model_i59', [], ExcelValue.by_value
  attach_function 'model_j59', [], ExcelValue.by_value
  attach_function 'model_k59', [], ExcelValue.by_value
  attach_function 'model_l59', [], ExcelValue.by_value
  attach_function 'model_m59', [], ExcelValue.by_value
  attach_function 'model_n59', [], ExcelValue.by_value
  attach_function 'model_o59', [], ExcelValue.by_value
  attach_function 'model_p59', [], ExcelValue.by_value
  attach_function 'model_q59', [], ExcelValue.by_value
  attach_function 'model_r59', [], ExcelValue.by_value
  attach_function 'model_s59', [], ExcelValue.by_value
  attach_function 'model_t59', [], ExcelValue.by_value
  attach_function 'model_u59', [], ExcelValue.by_value
  attach_function 'model_v59', [], ExcelValue.by_value
  attach_function 'model_w59', [], ExcelValue.by_value
  attach_function 'model_x59', [], ExcelValue.by_value
  attach_function 'model_y59', [], ExcelValue.by_value
  attach_function 'model_z59', [], ExcelValue.by_value
  attach_function 'model_aa59', [], ExcelValue.by_value
  attach_function 'model_ab59', [], ExcelValue.by_value
  attach_function 'model_ac59', [], ExcelValue.by_value
  attach_function 'model_ad59', [], ExcelValue.by_value
  attach_function 'model_ae59', [], ExcelValue.by_value
  attach_function 'model_af59', [], ExcelValue.by_value
  attach_function 'model_ag59', [], ExcelValue.by_value
  attach_function 'model_ah59', [], ExcelValue.by_value
  attach_function 'model_ai59', [], ExcelValue.by_value
  attach_function 'model_aj59', [], ExcelValue.by_value
  attach_function 'model_ak59', [], ExcelValue.by_value
  attach_function 'model_al59', [], ExcelValue.by_value
  attach_function 'model_am59', [], ExcelValue.by_value
  attach_function 'model_an59', [], ExcelValue.by_value
  attach_function 'model_ao59', [], ExcelValue.by_value
  # end of Model
  # Start of named references
  attach_function 'annual_change_in_non_electricity_traded_emissions', [], ExcelValue.by_value
  attach_function 'average_life_of_low_carbon_generation', [], ExcelValue.by_value
  attach_function 'ccs_by_2020', [], ExcelValue.by_value
  attach_function 'demand', [], ExcelValue.by_value
  attach_function 'electricity_demand_growth_rate', [], ExcelValue.by_value
  attach_function 'electricity_demand_in_2012', [], ExcelValue.by_value
  attach_function 'electricity_demand_in_2050', [], ExcelValue.by_value
  attach_function 'electricity_emissions_absolute_2050', [], ExcelValue.by_value
  attach_function 'electricity_emissions_during_cb4', [], ExcelValue.by_value
  attach_function 'electrification_start_year', [], ExcelValue.by_value
  attach_function 'emissions', [], ExcelValue.by_value
  attach_function 'emissions_factor', [], ExcelValue.by_value
  attach_function 'emissions_factor_2020', [], ExcelValue.by_value
  attach_function 'emissions_factor_2030', [], ExcelValue.by_value
  attach_function 'emissions_factor_2050', [], ExcelValue.by_value
  attach_function 'high_carbon', [], ExcelValue.by_value
  attach_function 'high_carbon_ef', [], ExcelValue.by_value
  attach_function 'high_carbon_emissions_factor_2012', [], ExcelValue.by_value
  attach_function 'high_carbon_emissions_factor_2020', [], ExcelValue.by_value
  attach_function 'high_carbon_emissions_factor_2050', [], ExcelValue.by_value
  attach_function 'high_carbon_generation', [], ExcelValue.by_value
  attach_function 'high_carbon_generation_capacity', [], ExcelValue.by_value
  attach_function 'high_carbon_load_factor', [], ExcelValue.by_value
  attach_function 'low_carbon_generation', [], ExcelValue.by_value
  attach_function 'low_carbon_generation_capacity', [], ExcelValue.by_value
  attach_function 'low_carbon_load_factor', [], ExcelValue.by_value
  attach_function 'maximum_low_c', [], ExcelValue.by_value
  attach_function 'maximum_low_carbon_build_rate', [], ExcelValue.by_value
  attach_function 'maximum_low_carbon_build_rate_contraction', [], ExcelValue.by_value
  attach_function 'maximum_low_carbon_build_rate_expansion', [], ExcelValue.by_value
  attach_function 'maxmean2012', [], ExcelValue.by_value
  attach_function 'maxmean2050', [], ExcelValue.by_value
  attach_function 'mean_load_factor', [], ExcelValue.by_value
  attach_function 'minimum_low_carbon_build_rate', [], ExcelValue.by_value
  attach_function 'minmean2012', [], ExcelValue.by_value
  attach_function 'minmean2050', [], ExcelValue.by_value
  attach_function 'net_increase_in_zero_carbon', [], ExcelValue.by_value
  attach_function 'non_electricity_traded_sector_emissions', [], ExcelValue.by_value
  attach_function 'nuclear_change_2012_2020', [], ExcelValue.by_value
  attach_function 'nuclear_in_2012', [], ExcelValue.by_value
  attach_function 'renewable_electricity_in_2020', [], ExcelValue.by_value
  attach_function 'renewables_in_2012', [], ExcelValue.by_value
  attach_function 'required_high_carbon_construction', [], ExcelValue.by_value
  attach_function 'traded_emissions', [], ExcelValue.by_value
  attach_function 'uk_share_of_eu_ets_cap_alternative', [], ExcelValue.by_value
  attach_function 'uk_share_of_eu_ets_cap_current', [], ExcelValue.by_value
  attach_function 'year_second_wave_of_building_starts', [], ExcelValue.by_value
  attach_function 'zero_carbon', [], ExcelValue.by_value
  attach_function 'zero_carbon_built', [], ExcelValue.by_value
  attach_function 'zero_carbon_decomissioned', [], ExcelValue.by_value
  attach_function 'set_annual_change_in_non_electricity_traded_emissions', [ExcelValue.by_value], :void
  attach_function 'set_average_life_of_low_carbon_generation', [ExcelValue.by_value], :void
  attach_function 'set_ccs_by_2020', [ExcelValue.by_value], :void
  attach_function 'set_electricity_demand_growth_rate', [ExcelValue.by_value], :void
  attach_function 'set_electricity_demand_in_2012', [ExcelValue.by_value], :void
  attach_function 'set_electricity_demand_in_2050', [ExcelValue.by_value], :void
  attach_function 'set_electrification_start_year', [ExcelValue.by_value], :void
  attach_function 'set_high_carbon_emissions_factor_2012', [ExcelValue.by_value], :void
  attach_function 'set_high_carbon_emissions_factor_2020', [ExcelValue.by_value], :void
  attach_function 'set_high_carbon_emissions_factor_2050', [ExcelValue.by_value], :void
  attach_function 'set_maximum_low_c', [ExcelValue.by_value], :void
  attach_function 'set_maximum_low_carbon_build_rate', [ExcelValue.by_value], :void
  attach_function 'set_maximum_low_carbon_build_rate_contraction', [ExcelValue.by_value], :void
  attach_function 'set_maximum_low_carbon_build_rate_expansion', [ExcelValue.by_value], :void
  attach_function 'set_maxmean2012', [ExcelValue.by_value], :void
  attach_function 'set_maxmean2050', [ExcelValue.by_value], :void
  attach_function 'set_minimum_low_carbon_build_rate', [ExcelValue.by_value], :void
  attach_function 'set_minmean2012', [ExcelValue.by_value], :void
  attach_function 'set_minmean2050', [ExcelValue.by_value], :void
  attach_function 'set_nuclear_change_2012_2020', [ExcelValue.by_value], :void
  attach_function 'set_nuclear_in_2012', [ExcelValue.by_value], :void
  attach_function 'set_renewable_electricity_in_2020', [ExcelValue.by_value], :void
  attach_function 'set_renewables_in_2012', [ExcelValue.by_value], :void
  attach_function 'set_year_second_wave_of_building_starts', [ExcelValue.by_value], :void
  # End of named references
end
