require 'ffi'
require 'singleton'

class ModelShim

  # WARNING: this is not thread safe
  def initialize
    reset
  end

  def reset
    Model.reset
  end

  def method_missing(name, *arguments)
    if arguments.size == 0
      get(name)
    elsif arguments.size == 1
      set(name, arguments.first)
    else
      super
    end 
  end

  def get(name)
    return 0 unless Model.respond_to?(name)
    ruby_value_from_excel_value(Model.send(name))
  end

  def ruby_value_from_excel_value(excel_value)
    case excel_value[:type]
    when :ExcelNumber; excel_value[:number]
    when :ExcelString; excel_value[:string].read_string.force_encoding("utf-8")
    when :ExcelBoolean; excel_value[:number] == 1
    when :ExcelEmpty; nil
    when :ExcelRange
      r = excel_value[:rows]
      c = excel_value[:columns]
      p = excel_value[:array]
      s = Model::ExcelValue.size
      a = Array.new(r) { Array.new(c) }
      (0...r).each do |row|
        (0...c).each do |column|
          a[row][column] = ruby_value_from_excel_value(Model::ExcelValue.new(p + (((row*c)+column)*s)))
        end
      end 
      return a
    when :ExcelError; [:value,:name,:div0,:ref,:na][excel_value[:number]]
    else
      raise Exception.new("ExcelValue type #{excel_value[:type].inspect} not recognised")
    end
  end

  def set(name, ruby_value)
    name = name.to_s
    name = "set_#{name[0..-2]}" if name.end_with?('=')
    return false unless Model.respond_to?(name)
    Model.send(name, excel_value_from_ruby_value(ruby_value))
  end

  def excel_value_from_ruby_value(ruby_value, excel_value = Model::ExcelValue.new)
    case ruby_value
    when Numeric
      excel_value[:type] = :ExcelNumber
      excel_value[:number] = ruby_value
    when String
      excel_value[:type] = :ExcelString
      excel_value[:string] = FFI::MemoryPointer.from_string(ruby_value.encode('utf-8'))
    when TrueClass, FalseClass
      excel_value[:type] = :ExcelBoolean
      excel_value[:number] = ruby_value ? 1 : 0
    when nil
      excel_value[:type] = :ExcelEmpty
    when Array
      excel_value[:type] = :ExcelRange
      # Presumed to be a row unless specified otherwise
      if ruby_value.first.is_a?(Array)
        excel_value[:rows] = ruby_value.size
        excel_value[:columns] = ruby_value.first.size
      else
        excel_value[:rows] = 1
        excel_value[:columns] = ruby_value.size
      end
      ruby_values = ruby_value.flatten
      pointer = FFI::MemoryPointer.new(Model::ExcelValue, ruby_values.size)
      excel_value[:array] = pointer
      ruby_values.each.with_index do |v,i|
        excel_value_from_ruby_value(v, Model::ExcelValue.new(pointer[i]))
      end
    when Symbol
      excel_value[:type] = :ExcelError
      excel_value[:number] = [:value, :name, :div0, :ref, :na].index(ruby_value)
    else
      raise Exception.new("Ruby value #{ruby_value.inspect} not translatable into excel")
    end
    excel_value
  end

end
    

module Model
  extend FFI::Library
  ffi_lib  File.join(File.dirname(__FILE__),FFI.map_library_name('model'))
  ExcelType = enum :ExcelEmpty, :ExcelNumber, :ExcelString, :ExcelBoolean, :ExcelError, :ExcelRange
                
  class ExcelValue < FFI::Struct
    layout :type, ExcelType,
  	       :number, :double,
  	       :string, :pointer,
         	 :array, :pointer,
           :rows, :int,
           :columns, :int             
  end
  

  # use this function to reset all cell values
  attach_function 'reset', [], :void

  # start of Model
  attach_function 'set_model_c22', [ExcelValue.by_value], :void
  attach_function 'set_model_c46', [ExcelValue.by_value], :void
  attach_function 'set_model_c31', [ExcelValue.by_value], :void
  attach_function 'set_model_c59', [ExcelValue.by_value], :void
  attach_function 'set_model_c62', [ExcelValue.by_value], :void
  attach_function 'set_model_c60', [ExcelValue.by_value], :void
  attach_function 'set_model_c63', [ExcelValue.by_value], :void
  attach_function 'set_model_c24', [ExcelValue.by_value], :void
  attach_function 'set_model_c47', [ExcelValue.by_value], :void
  attach_function 'set_model_c26', [ExcelValue.by_value], :void
  attach_function 'set_model_c25', [ExcelValue.by_value], :void
  attach_function 'set_model_c50', [ExcelValue.by_value], :void
  attach_function 'set_model_c52', [ExcelValue.by_value], :void
  attach_function 'set_model_c57', [ExcelValue.by_value], :void
  attach_function 'set_model_c55', [ExcelValue.by_value], :void
  attach_function 'set_model_c56', [ExcelValue.by_value], :void
  attach_function 'set_model_c43', [ExcelValue.by_value], :void
  attach_function 'set_model_c42', [ExcelValue.by_value], :void
  attach_function 'set_model_c41', [ExcelValue.by_value], :void
  attach_function 'set_model_c29', [ExcelValue.by_value], :void
  attach_function 'set_model_c34', [ExcelValue.by_value], :void
  attach_function 'set_model_p31', [ExcelValue.by_value], :void
  attach_function 'set_model_p32', [ExcelValue.by_value], :void
  attach_function 'set_model_p33', [ExcelValue.by_value], :void
  attach_function 'set_model_p34', [ExcelValue.by_value], :void
  attach_function 'set_model_c39', [ExcelValue.by_value], :void
  attach_function 'set_model_c38', [ExcelValue.by_value], :void
  attach_function 'set_model_c37', [ExcelValue.by_value], :void
  attach_function 'set_model_c30', [ExcelValue.by_value], :void
  attach_function 'set_model_c35', [ExcelValue.by_value], :void
  attach_function 'set_model_c23', [ExcelValue.by_value], :void
  attach_function 'set_model_c33', [ExcelValue.by_value], :void
  attach_function 'model_c22', [], ExcelValue.by_value
  attach_function 'model_c46', [], ExcelValue.by_value
  attach_function 'model_c31', [], ExcelValue.by_value
  attach_function 'model_p24', [], ExcelValue.by_value
  attach_function 'model_p25', [], ExcelValue.by_value
  attach_function 'model_p23', [], ExcelValue.by_value
  attach_function 'model_c59', [], ExcelValue.by_value
  attach_function 'model_c62', [], ExcelValue.by_value
  attach_function 'model_p28', [], ExcelValue.by_value
  attach_function 'model_c60', [], ExcelValue.by_value
  attach_function 'model_c63', [], ExcelValue.by_value
  attach_function 'model_c24', [], ExcelValue.by_value
  attach_function 'model_p37', [], ExcelValue.by_value
  attach_function 'model_p38', [], ExcelValue.by_value
  attach_function 'model_p39', [], ExcelValue.by_value
  attach_function 'model_c47', [], ExcelValue.by_value
  attach_function 'model_c26', [], ExcelValue.by_value
  attach_function 'model_c25', [], ExcelValue.by_value
  attach_function 'model_c50', [], ExcelValue.by_value
  attach_function 'model_c52', [], ExcelValue.by_value
  attach_function 'model_c57', [], ExcelValue.by_value
  attach_function 'model_c55', [], ExcelValue.by_value
  attach_function 'model_c56', [], ExcelValue.by_value
  attach_function 'model_c43', [], ExcelValue.by_value
  attach_function 'model_c42', [], ExcelValue.by_value
  attach_function 'model_c41', [], ExcelValue.by_value
  attach_function 'model_c164', [], ExcelValue.by_value
  attach_function 'model_d164', [], ExcelValue.by_value
  attach_function 'model_e164', [], ExcelValue.by_value
  attach_function 'model_f164', [], ExcelValue.by_value
  attach_function 'model_g164', [], ExcelValue.by_value
  attach_function 'model_h164', [], ExcelValue.by_value
  attach_function 'model_i164', [], ExcelValue.by_value
  attach_function 'model_j164', [], ExcelValue.by_value
  attach_function 'model_k164', [], ExcelValue.by_value
  attach_function 'model_l164', [], ExcelValue.by_value
  attach_function 'model_m164', [], ExcelValue.by_value
  attach_function 'model_n164', [], ExcelValue.by_value
  attach_function 'model_o164', [], ExcelValue.by_value
  attach_function 'model_p164', [], ExcelValue.by_value
  attach_function 'model_q164', [], ExcelValue.by_value
  attach_function 'model_r164', [], ExcelValue.by_value
  attach_function 'model_s164', [], ExcelValue.by_value
  attach_function 'model_t164', [], ExcelValue.by_value
  attach_function 'model_u164', [], ExcelValue.by_value
  attach_function 'model_v164', [], ExcelValue.by_value
  attach_function 'model_w164', [], ExcelValue.by_value
  attach_function 'model_x164', [], ExcelValue.by_value
  attach_function 'model_y164', [], ExcelValue.by_value
  attach_function 'model_z164', [], ExcelValue.by_value
  attach_function 'model_aa164', [], ExcelValue.by_value
  attach_function 'model_ab164', [], ExcelValue.by_value
  attach_function 'model_ac164', [], ExcelValue.by_value
  attach_function 'model_ad164', [], ExcelValue.by_value
  attach_function 'model_ae164', [], ExcelValue.by_value
  attach_function 'model_af164', [], ExcelValue.by_value
  attach_function 'model_ag164', [], ExcelValue.by_value
  attach_function 'model_ah164', [], ExcelValue.by_value
  attach_function 'model_ai164', [], ExcelValue.by_value
  attach_function 'model_aj164', [], ExcelValue.by_value
  attach_function 'model_ak164', [], ExcelValue.by_value
  attach_function 'model_al164', [], ExcelValue.by_value
  attach_function 'model_am164', [], ExcelValue.by_value
  attach_function 'model_an164', [], ExcelValue.by_value
  attach_function 'model_ao164', [], ExcelValue.by_value
  attach_function 'model_c153', [], ExcelValue.by_value
  attach_function 'model_d153', [], ExcelValue.by_value
  attach_function 'model_e153', [], ExcelValue.by_value
  attach_function 'model_f153', [], ExcelValue.by_value
  attach_function 'model_g153', [], ExcelValue.by_value
  attach_function 'model_h153', [], ExcelValue.by_value
  attach_function 'model_i153', [], ExcelValue.by_value
  attach_function 'model_j153', [], ExcelValue.by_value
  attach_function 'model_k153', [], ExcelValue.by_value
  attach_function 'model_l153', [], ExcelValue.by_value
  attach_function 'model_m153', [], ExcelValue.by_value
  attach_function 'model_n153', [], ExcelValue.by_value
  attach_function 'model_o153', [], ExcelValue.by_value
  attach_function 'model_p153', [], ExcelValue.by_value
  attach_function 'model_q153', [], ExcelValue.by_value
  attach_function 'model_r153', [], ExcelValue.by_value
  attach_function 'model_s153', [], ExcelValue.by_value
  attach_function 'model_t153', [], ExcelValue.by_value
  attach_function 'model_u153', [], ExcelValue.by_value
  attach_function 'model_v153', [], ExcelValue.by_value
  attach_function 'model_w153', [], ExcelValue.by_value
  attach_function 'model_x153', [], ExcelValue.by_value
  attach_function 'model_y153', [], ExcelValue.by_value
  attach_function 'model_z153', [], ExcelValue.by_value
  attach_function 'model_aa153', [], ExcelValue.by_value
  attach_function 'model_ab153', [], ExcelValue.by_value
  attach_function 'model_ac153', [], ExcelValue.by_value
  attach_function 'model_ad153', [], ExcelValue.by_value
  attach_function 'model_ae153', [], ExcelValue.by_value
  attach_function 'model_af153', [], ExcelValue.by_value
  attach_function 'model_ag153', [], ExcelValue.by_value
  attach_function 'model_ah153', [], ExcelValue.by_value
  attach_function 'model_ai153', [], ExcelValue.by_value
  attach_function 'model_aj153', [], ExcelValue.by_value
  attach_function 'model_ak153', [], ExcelValue.by_value
  attach_function 'model_al153', [], ExcelValue.by_value
  attach_function 'model_am153', [], ExcelValue.by_value
  attach_function 'model_an153', [], ExcelValue.by_value
  attach_function 'model_ao153', [], ExcelValue.by_value
  attach_function 'model_c29', [], ExcelValue.by_value
  attach_function 'model_c155', [], ExcelValue.by_value
  attach_function 'model_d155', [], ExcelValue.by_value
  attach_function 'model_e155', [], ExcelValue.by_value
  attach_function 'model_f155', [], ExcelValue.by_value
  attach_function 'model_g155', [], ExcelValue.by_value
  attach_function 'model_h155', [], ExcelValue.by_value
  attach_function 'model_i155', [], ExcelValue.by_value
  attach_function 'model_j155', [], ExcelValue.by_value
  attach_function 'model_k155', [], ExcelValue.by_value
  attach_function 'model_l155', [], ExcelValue.by_value
  attach_function 'model_m155', [], ExcelValue.by_value
  attach_function 'model_n155', [], ExcelValue.by_value
  attach_function 'model_o155', [], ExcelValue.by_value
  attach_function 'model_p155', [], ExcelValue.by_value
  attach_function 'model_q155', [], ExcelValue.by_value
  attach_function 'model_r155', [], ExcelValue.by_value
  attach_function 'model_s155', [], ExcelValue.by_value
  attach_function 'model_t155', [], ExcelValue.by_value
  attach_function 'model_u155', [], ExcelValue.by_value
  attach_function 'model_v155', [], ExcelValue.by_value
  attach_function 'model_w155', [], ExcelValue.by_value
  attach_function 'model_x155', [], ExcelValue.by_value
  attach_function 'model_y155', [], ExcelValue.by_value
  attach_function 'model_z155', [], ExcelValue.by_value
  attach_function 'model_aa155', [], ExcelValue.by_value
  attach_function 'model_ab155', [], ExcelValue.by_value
  attach_function 'model_ac155', [], ExcelValue.by_value
  attach_function 'model_ad155', [], ExcelValue.by_value
  attach_function 'model_ae155', [], ExcelValue.by_value
  attach_function 'model_af155', [], ExcelValue.by_value
  attach_function 'model_ag155', [], ExcelValue.by_value
  attach_function 'model_ah155', [], ExcelValue.by_value
  attach_function 'model_ai155', [], ExcelValue.by_value
  attach_function 'model_aj155', [], ExcelValue.by_value
  attach_function 'model_ak155', [], ExcelValue.by_value
  attach_function 'model_al155', [], ExcelValue.by_value
  attach_function 'model_am155', [], ExcelValue.by_value
  attach_function 'model_an155', [], ExcelValue.by_value
  attach_function 'model_ao155', [], ExcelValue.by_value
  attach_function 'model_c152', [], ExcelValue.by_value
  attach_function 'model_d152', [], ExcelValue.by_value
  attach_function 'model_e152', [], ExcelValue.by_value
  attach_function 'model_f152', [], ExcelValue.by_value
  attach_function 'model_g152', [], ExcelValue.by_value
  attach_function 'model_h152', [], ExcelValue.by_value
  attach_function 'model_i152', [], ExcelValue.by_value
  attach_function 'model_j152', [], ExcelValue.by_value
  attach_function 'model_k152', [], ExcelValue.by_value
  attach_function 'model_l152', [], ExcelValue.by_value
  attach_function 'model_m152', [], ExcelValue.by_value
  attach_function 'model_n152', [], ExcelValue.by_value
  attach_function 'model_o152', [], ExcelValue.by_value
  attach_function 'model_p152', [], ExcelValue.by_value
  attach_function 'model_q152', [], ExcelValue.by_value
  attach_function 'model_r152', [], ExcelValue.by_value
  attach_function 'model_s152', [], ExcelValue.by_value
  attach_function 'model_t152', [], ExcelValue.by_value
  attach_function 'model_u152', [], ExcelValue.by_value
  attach_function 'model_v152', [], ExcelValue.by_value
  attach_function 'model_w152', [], ExcelValue.by_value
  attach_function 'model_x152', [], ExcelValue.by_value
  attach_function 'model_y152', [], ExcelValue.by_value
  attach_function 'model_z152', [], ExcelValue.by_value
  attach_function 'model_aa152', [], ExcelValue.by_value
  attach_function 'model_ab152', [], ExcelValue.by_value
  attach_function 'model_ac152', [], ExcelValue.by_value
  attach_function 'model_ad152', [], ExcelValue.by_value
  attach_function 'model_ae152', [], ExcelValue.by_value
  attach_function 'model_af152', [], ExcelValue.by_value
  attach_function 'model_ag152', [], ExcelValue.by_value
  attach_function 'model_ah152', [], ExcelValue.by_value
  attach_function 'model_ai152', [], ExcelValue.by_value
  attach_function 'model_aj152', [], ExcelValue.by_value
  attach_function 'model_ak152', [], ExcelValue.by_value
  attach_function 'model_al152', [], ExcelValue.by_value
  attach_function 'model_am152', [], ExcelValue.by_value
  attach_function 'model_an152', [], ExcelValue.by_value
  attach_function 'model_ao152', [], ExcelValue.by_value
  attach_function 'model_c34', [], ExcelValue.by_value
  attach_function 'model_c154', [], ExcelValue.by_value
  attach_function 'model_d154', [], ExcelValue.by_value
  attach_function 'model_e154', [], ExcelValue.by_value
  attach_function 'model_f154', [], ExcelValue.by_value
  attach_function 'model_g154', [], ExcelValue.by_value
  attach_function 'model_h154', [], ExcelValue.by_value
  attach_function 'model_i154', [], ExcelValue.by_value
  attach_function 'model_j154', [], ExcelValue.by_value
  attach_function 'model_k154', [], ExcelValue.by_value
  attach_function 'model_l154', [], ExcelValue.by_value
  attach_function 'model_m154', [], ExcelValue.by_value
  attach_function 'model_n154', [], ExcelValue.by_value
  attach_function 'model_o154', [], ExcelValue.by_value
  attach_function 'model_p154', [], ExcelValue.by_value
  attach_function 'model_q154', [], ExcelValue.by_value
  attach_function 'model_r154', [], ExcelValue.by_value
  attach_function 'model_s154', [], ExcelValue.by_value
  attach_function 'model_t154', [], ExcelValue.by_value
  attach_function 'model_u154', [], ExcelValue.by_value
  attach_function 'model_v154', [], ExcelValue.by_value
  attach_function 'model_w154', [], ExcelValue.by_value
  attach_function 'model_x154', [], ExcelValue.by_value
  attach_function 'model_y154', [], ExcelValue.by_value
  attach_function 'model_z154', [], ExcelValue.by_value
  attach_function 'model_aa154', [], ExcelValue.by_value
  attach_function 'model_ab154', [], ExcelValue.by_value
  attach_function 'model_ac154', [], ExcelValue.by_value
  attach_function 'model_ad154', [], ExcelValue.by_value
  attach_function 'model_ae154', [], ExcelValue.by_value
  attach_function 'model_af154', [], ExcelValue.by_value
  attach_function 'model_ag154', [], ExcelValue.by_value
  attach_function 'model_ah154', [], ExcelValue.by_value
  attach_function 'model_ai154', [], ExcelValue.by_value
  attach_function 'model_aj154', [], ExcelValue.by_value
  attach_function 'model_ak154', [], ExcelValue.by_value
  attach_function 'model_al154', [], ExcelValue.by_value
  attach_function 'model_am154', [], ExcelValue.by_value
  attach_function 'model_an154', [], ExcelValue.by_value
  attach_function 'model_ao154', [], ExcelValue.by_value
  attach_function 'model_c159', [], ExcelValue.by_value
  attach_function 'model_d159', [], ExcelValue.by_value
  attach_function 'model_e159', [], ExcelValue.by_value
  attach_function 'model_f159', [], ExcelValue.by_value
  attach_function 'model_g159', [], ExcelValue.by_value
  attach_function 'model_h159', [], ExcelValue.by_value
  attach_function 'model_i159', [], ExcelValue.by_value
  attach_function 'model_j159', [], ExcelValue.by_value
  attach_function 'model_k159', [], ExcelValue.by_value
  attach_function 'model_l159', [], ExcelValue.by_value
  attach_function 'model_m159', [], ExcelValue.by_value
  attach_function 'model_n159', [], ExcelValue.by_value
  attach_function 'model_o159', [], ExcelValue.by_value
  attach_function 'model_p159', [], ExcelValue.by_value
  attach_function 'model_q159', [], ExcelValue.by_value
  attach_function 'model_r159', [], ExcelValue.by_value
  attach_function 'model_s159', [], ExcelValue.by_value
  attach_function 'model_t159', [], ExcelValue.by_value
  attach_function 'model_u159', [], ExcelValue.by_value
  attach_function 'model_v159', [], ExcelValue.by_value
  attach_function 'model_w159', [], ExcelValue.by_value
  attach_function 'model_x159', [], ExcelValue.by_value
  attach_function 'model_y159', [], ExcelValue.by_value
  attach_function 'model_z159', [], ExcelValue.by_value
  attach_function 'model_aa159', [], ExcelValue.by_value
  attach_function 'model_ab159', [], ExcelValue.by_value
  attach_function 'model_ac159', [], ExcelValue.by_value
  attach_function 'model_ad159', [], ExcelValue.by_value
  attach_function 'model_ae159', [], ExcelValue.by_value
  attach_function 'model_af159', [], ExcelValue.by_value
  attach_function 'model_ag159', [], ExcelValue.by_value
  attach_function 'model_ah159', [], ExcelValue.by_value
  attach_function 'model_ai159', [], ExcelValue.by_value
  attach_function 'model_aj159', [], ExcelValue.by_value
  attach_function 'model_ak159', [], ExcelValue.by_value
  attach_function 'model_al159', [], ExcelValue.by_value
  attach_function 'model_am159', [], ExcelValue.by_value
  attach_function 'model_an159', [], ExcelValue.by_value
  attach_function 'model_ao159', [], ExcelValue.by_value
  attach_function 'model_c161', [], ExcelValue.by_value
  attach_function 'model_d161', [], ExcelValue.by_value
  attach_function 'model_e161', [], ExcelValue.by_value
  attach_function 'model_f161', [], ExcelValue.by_value
  attach_function 'model_g161', [], ExcelValue.by_value
  attach_function 'model_h161', [], ExcelValue.by_value
  attach_function 'model_i161', [], ExcelValue.by_value
  attach_function 'model_j161', [], ExcelValue.by_value
  attach_function 'model_k161', [], ExcelValue.by_value
  attach_function 'model_l161', [], ExcelValue.by_value
  attach_function 'model_m161', [], ExcelValue.by_value
  attach_function 'model_n161', [], ExcelValue.by_value
  attach_function 'model_o161', [], ExcelValue.by_value
  attach_function 'model_p161', [], ExcelValue.by_value
  attach_function 'model_q161', [], ExcelValue.by_value
  attach_function 'model_r161', [], ExcelValue.by_value
  attach_function 'model_s161', [], ExcelValue.by_value
  attach_function 'model_t161', [], ExcelValue.by_value
  attach_function 'model_u161', [], ExcelValue.by_value
  attach_function 'model_v161', [], ExcelValue.by_value
  attach_function 'model_w161', [], ExcelValue.by_value
  attach_function 'model_x161', [], ExcelValue.by_value
  attach_function 'model_y161', [], ExcelValue.by_value
  attach_function 'model_z161', [], ExcelValue.by_value
  attach_function 'model_aa161', [], ExcelValue.by_value
  attach_function 'model_ab161', [], ExcelValue.by_value
  attach_function 'model_ac161', [], ExcelValue.by_value
  attach_function 'model_ad161', [], ExcelValue.by_value
  attach_function 'model_ae161', [], ExcelValue.by_value
  attach_function 'model_af161', [], ExcelValue.by_value
  attach_function 'model_ag161', [], ExcelValue.by_value
  attach_function 'model_ah161', [], ExcelValue.by_value
  attach_function 'model_ai161', [], ExcelValue.by_value
  attach_function 'model_aj161', [], ExcelValue.by_value
  attach_function 'model_ak161', [], ExcelValue.by_value
  attach_function 'model_al161', [], ExcelValue.by_value
  attach_function 'model_am161', [], ExcelValue.by_value
  attach_function 'model_an161', [], ExcelValue.by_value
  attach_function 'model_ao161', [], ExcelValue.by_value
  attach_function 'model_c158', [], ExcelValue.by_value
  attach_function 'model_d158', [], ExcelValue.by_value
  attach_function 'model_e158', [], ExcelValue.by_value
  attach_function 'model_f158', [], ExcelValue.by_value
  attach_function 'model_g158', [], ExcelValue.by_value
  attach_function 'model_h158', [], ExcelValue.by_value
  attach_function 'model_i158', [], ExcelValue.by_value
  attach_function 'model_j158', [], ExcelValue.by_value
  attach_function 'model_k158', [], ExcelValue.by_value
  attach_function 'model_l158', [], ExcelValue.by_value
  attach_function 'model_m158', [], ExcelValue.by_value
  attach_function 'model_n158', [], ExcelValue.by_value
  attach_function 'model_o158', [], ExcelValue.by_value
  attach_function 'model_p158', [], ExcelValue.by_value
  attach_function 'model_q158', [], ExcelValue.by_value
  attach_function 'model_r158', [], ExcelValue.by_value
  attach_function 'model_s158', [], ExcelValue.by_value
  attach_function 'model_t158', [], ExcelValue.by_value
  attach_function 'model_u158', [], ExcelValue.by_value
  attach_function 'model_v158', [], ExcelValue.by_value
  attach_function 'model_w158', [], ExcelValue.by_value
  attach_function 'model_x158', [], ExcelValue.by_value
  attach_function 'model_y158', [], ExcelValue.by_value
  attach_function 'model_z158', [], ExcelValue.by_value
  attach_function 'model_aa158', [], ExcelValue.by_value
  attach_function 'model_ab158', [], ExcelValue.by_value
  attach_function 'model_ac158', [], ExcelValue.by_value
  attach_function 'model_ad158', [], ExcelValue.by_value
  attach_function 'model_ae158', [], ExcelValue.by_value
  attach_function 'model_af158', [], ExcelValue.by_value
  attach_function 'model_ag158', [], ExcelValue.by_value
  attach_function 'model_ah158', [], ExcelValue.by_value
  attach_function 'model_ai158', [], ExcelValue.by_value
  attach_function 'model_aj158', [], ExcelValue.by_value
  attach_function 'model_ak158', [], ExcelValue.by_value
  attach_function 'model_al158', [], ExcelValue.by_value
  attach_function 'model_am158', [], ExcelValue.by_value
  attach_function 'model_an158', [], ExcelValue.by_value
  attach_function 'model_ao158', [], ExcelValue.by_value
  attach_function 'model_c162', [], ExcelValue.by_value
  attach_function 'model_d162', [], ExcelValue.by_value
  attach_function 'model_e162', [], ExcelValue.by_value
  attach_function 'model_f162', [], ExcelValue.by_value
  attach_function 'model_g162', [], ExcelValue.by_value
  attach_function 'model_h162', [], ExcelValue.by_value
  attach_function 'model_i162', [], ExcelValue.by_value
  attach_function 'model_j162', [], ExcelValue.by_value
  attach_function 'model_k162', [], ExcelValue.by_value
  attach_function 'model_l162', [], ExcelValue.by_value
  attach_function 'model_m162', [], ExcelValue.by_value
  attach_function 'model_n162', [], ExcelValue.by_value
  attach_function 'model_o162', [], ExcelValue.by_value
  attach_function 'model_p162', [], ExcelValue.by_value
  attach_function 'model_q162', [], ExcelValue.by_value
  attach_function 'model_r162', [], ExcelValue.by_value
  attach_function 'model_s162', [], ExcelValue.by_value
  attach_function 'model_t162', [], ExcelValue.by_value
  attach_function 'model_u162', [], ExcelValue.by_value
  attach_function 'model_v162', [], ExcelValue.by_value
  attach_function 'model_w162', [], ExcelValue.by_value
  attach_function 'model_x162', [], ExcelValue.by_value
  attach_function 'model_y162', [], ExcelValue.by_value
  attach_function 'model_z162', [], ExcelValue.by_value
  attach_function 'model_aa162', [], ExcelValue.by_value
  attach_function 'model_ab162', [], ExcelValue.by_value
  attach_function 'model_ac162', [], ExcelValue.by_value
  attach_function 'model_ad162', [], ExcelValue.by_value
  attach_function 'model_ae162', [], ExcelValue.by_value
  attach_function 'model_af162', [], ExcelValue.by_value
  attach_function 'model_ag162', [], ExcelValue.by_value
  attach_function 'model_ah162', [], ExcelValue.by_value
  attach_function 'model_ai162', [], ExcelValue.by_value
  attach_function 'model_aj162', [], ExcelValue.by_value
  attach_function 'model_ak162', [], ExcelValue.by_value
  attach_function 'model_al162', [], ExcelValue.by_value
  attach_function 'model_am162', [], ExcelValue.by_value
  attach_function 'model_an162', [], ExcelValue.by_value
  attach_function 'model_ao162', [], ExcelValue.by_value
  attach_function 'model_c160', [], ExcelValue.by_value
  attach_function 'model_d160', [], ExcelValue.by_value
  attach_function 'model_e160', [], ExcelValue.by_value
  attach_function 'model_f160', [], ExcelValue.by_value
  attach_function 'model_g160', [], ExcelValue.by_value
  attach_function 'model_h160', [], ExcelValue.by_value
  attach_function 'model_i160', [], ExcelValue.by_value
  attach_function 'model_j160', [], ExcelValue.by_value
  attach_function 'model_k160', [], ExcelValue.by_value
  attach_function 'model_l160', [], ExcelValue.by_value
  attach_function 'model_m160', [], ExcelValue.by_value
  attach_function 'model_n160', [], ExcelValue.by_value
  attach_function 'model_o160', [], ExcelValue.by_value
  attach_function 'model_p160', [], ExcelValue.by_value
  attach_function 'model_q160', [], ExcelValue.by_value
  attach_function 'model_r160', [], ExcelValue.by_value
  attach_function 'model_s160', [], ExcelValue.by_value
  attach_function 'model_t160', [], ExcelValue.by_value
  attach_function 'model_u160', [], ExcelValue.by_value
  attach_function 'model_v160', [], ExcelValue.by_value
  attach_function 'model_w160', [], ExcelValue.by_value
  attach_function 'model_x160', [], ExcelValue.by_value
  attach_function 'model_y160', [], ExcelValue.by_value
  attach_function 'model_z160', [], ExcelValue.by_value
  attach_function 'model_aa160', [], ExcelValue.by_value
  attach_function 'model_ab160', [], ExcelValue.by_value
  attach_function 'model_ac160', [], ExcelValue.by_value
  attach_function 'model_ad160', [], ExcelValue.by_value
  attach_function 'model_ae160', [], ExcelValue.by_value
  attach_function 'model_af160', [], ExcelValue.by_value
  attach_function 'model_ag160', [], ExcelValue.by_value
  attach_function 'model_ah160', [], ExcelValue.by_value
  attach_function 'model_ai160', [], ExcelValue.by_value
  attach_function 'model_aj160', [], ExcelValue.by_value
  attach_function 'model_ak160', [], ExcelValue.by_value
  attach_function 'model_al160', [], ExcelValue.by_value
  attach_function 'model_am160', [], ExcelValue.by_value
  attach_function 'model_an160', [], ExcelValue.by_value
  attach_function 'model_ao160', [], ExcelValue.by_value
  attach_function 'model_r31', [], ExcelValue.by_value
  attach_function 'model_q31', [], ExcelValue.by_value
  attach_function 'model_p31', [], ExcelValue.by_value
  attach_function 'model_r32', [], ExcelValue.by_value
  attach_function 'model_q32', [], ExcelValue.by_value
  attach_function 'model_p32', [], ExcelValue.by_value
  attach_function 'model_r33', [], ExcelValue.by_value
  attach_function 'model_q33', [], ExcelValue.by_value
  attach_function 'model_p33', [], ExcelValue.by_value
  attach_function 'model_r34', [], ExcelValue.by_value
  attach_function 'model_q34', [], ExcelValue.by_value
  attach_function 'model_p34', [], ExcelValue.by_value
  attach_function 'model_c184', [], ExcelValue.by_value
  attach_function 'model_d184', [], ExcelValue.by_value
  attach_function 'model_e184', [], ExcelValue.by_value
  attach_function 'model_f184', [], ExcelValue.by_value
  attach_function 'model_g184', [], ExcelValue.by_value
  attach_function 'model_h184', [], ExcelValue.by_value
  attach_function 'model_i184', [], ExcelValue.by_value
  attach_function 'model_j184', [], ExcelValue.by_value
  attach_function 'model_k184', [], ExcelValue.by_value
  attach_function 'model_l184', [], ExcelValue.by_value
  attach_function 'model_m184', [], ExcelValue.by_value
  attach_function 'model_n184', [], ExcelValue.by_value
  attach_function 'model_o184', [], ExcelValue.by_value
  attach_function 'model_p184', [], ExcelValue.by_value
  attach_function 'model_q184', [], ExcelValue.by_value
  attach_function 'model_r184', [], ExcelValue.by_value
  attach_function 'model_s184', [], ExcelValue.by_value
  attach_function 'model_t184', [], ExcelValue.by_value
  attach_function 'model_u184', [], ExcelValue.by_value
  attach_function 'model_v184', [], ExcelValue.by_value
  attach_function 'model_w184', [], ExcelValue.by_value
  attach_function 'model_x184', [], ExcelValue.by_value
  attach_function 'model_y184', [], ExcelValue.by_value
  attach_function 'model_z184', [], ExcelValue.by_value
  attach_function 'model_aa184', [], ExcelValue.by_value
  attach_function 'model_ab184', [], ExcelValue.by_value
  attach_function 'model_ac184', [], ExcelValue.by_value
  attach_function 'model_ad184', [], ExcelValue.by_value
  attach_function 'model_ae184', [], ExcelValue.by_value
  attach_function 'model_af184', [], ExcelValue.by_value
  attach_function 'model_ag184', [], ExcelValue.by_value
  attach_function 'model_ah184', [], ExcelValue.by_value
  attach_function 'model_ai184', [], ExcelValue.by_value
  attach_function 'model_aj184', [], ExcelValue.by_value
  attach_function 'model_ak184', [], ExcelValue.by_value
  attach_function 'model_al184', [], ExcelValue.by_value
  attach_function 'model_am184', [], ExcelValue.by_value
  attach_function 'model_an184', [], ExcelValue.by_value
  attach_function 'model_ao184', [], ExcelValue.by_value
  attach_function 'model_c182', [], ExcelValue.by_value
  attach_function 'model_d182', [], ExcelValue.by_value
  attach_function 'model_e182', [], ExcelValue.by_value
  attach_function 'model_f182', [], ExcelValue.by_value
  attach_function 'model_g182', [], ExcelValue.by_value
  attach_function 'model_h182', [], ExcelValue.by_value
  attach_function 'model_i182', [], ExcelValue.by_value
  attach_function 'model_j182', [], ExcelValue.by_value
  attach_function 'model_k182', [], ExcelValue.by_value
  attach_function 'model_l182', [], ExcelValue.by_value
  attach_function 'model_m182', [], ExcelValue.by_value
  attach_function 'model_n182', [], ExcelValue.by_value
  attach_function 'model_o182', [], ExcelValue.by_value
  attach_function 'model_p182', [], ExcelValue.by_value
  attach_function 'model_q182', [], ExcelValue.by_value
  attach_function 'model_r182', [], ExcelValue.by_value
  attach_function 'model_s182', [], ExcelValue.by_value
  attach_function 'model_t182', [], ExcelValue.by_value
  attach_function 'model_u182', [], ExcelValue.by_value
  attach_function 'model_v182', [], ExcelValue.by_value
  attach_function 'model_w182', [], ExcelValue.by_value
  attach_function 'model_x182', [], ExcelValue.by_value
  attach_function 'model_y182', [], ExcelValue.by_value
  attach_function 'model_z182', [], ExcelValue.by_value
  attach_function 'model_aa182', [], ExcelValue.by_value
  attach_function 'model_ab182', [], ExcelValue.by_value
  attach_function 'model_ac182', [], ExcelValue.by_value
  attach_function 'model_ad182', [], ExcelValue.by_value
  attach_function 'model_ae182', [], ExcelValue.by_value
  attach_function 'model_af182', [], ExcelValue.by_value
  attach_function 'model_ag182', [], ExcelValue.by_value
  attach_function 'model_ah182', [], ExcelValue.by_value
  attach_function 'model_ai182', [], ExcelValue.by_value
  attach_function 'model_aj182', [], ExcelValue.by_value
  attach_function 'model_ak182', [], ExcelValue.by_value
  attach_function 'model_al182', [], ExcelValue.by_value
  attach_function 'model_am182', [], ExcelValue.by_value
  attach_function 'model_an182', [], ExcelValue.by_value
  attach_function 'model_ao182', [], ExcelValue.by_value
  attach_function 'model_c185', [], ExcelValue.by_value
  attach_function 'model_d185', [], ExcelValue.by_value
  attach_function 'model_e185', [], ExcelValue.by_value
  attach_function 'model_f185', [], ExcelValue.by_value
  attach_function 'model_g185', [], ExcelValue.by_value
  attach_function 'model_h185', [], ExcelValue.by_value
  attach_function 'model_i185', [], ExcelValue.by_value
  attach_function 'model_j185', [], ExcelValue.by_value
  attach_function 'model_k185', [], ExcelValue.by_value
  attach_function 'model_l185', [], ExcelValue.by_value
  attach_function 'model_m185', [], ExcelValue.by_value
  attach_function 'model_n185', [], ExcelValue.by_value
  attach_function 'model_o185', [], ExcelValue.by_value
  attach_function 'model_p185', [], ExcelValue.by_value
  attach_function 'model_q185', [], ExcelValue.by_value
  attach_function 'model_r185', [], ExcelValue.by_value
  attach_function 'model_s185', [], ExcelValue.by_value
  attach_function 'model_t185', [], ExcelValue.by_value
  attach_function 'model_u185', [], ExcelValue.by_value
  attach_function 'model_v185', [], ExcelValue.by_value
  attach_function 'model_w185', [], ExcelValue.by_value
  attach_function 'model_x185', [], ExcelValue.by_value
  attach_function 'model_y185', [], ExcelValue.by_value
  attach_function 'model_z185', [], ExcelValue.by_value
  attach_function 'model_aa185', [], ExcelValue.by_value
  attach_function 'model_ab185', [], ExcelValue.by_value
  attach_function 'model_ac185', [], ExcelValue.by_value
  attach_function 'model_ad185', [], ExcelValue.by_value
  attach_function 'model_ae185', [], ExcelValue.by_value
  attach_function 'model_af185', [], ExcelValue.by_value
  attach_function 'model_ag185', [], ExcelValue.by_value
  attach_function 'model_ah185', [], ExcelValue.by_value
  attach_function 'model_ai185', [], ExcelValue.by_value
  attach_function 'model_aj185', [], ExcelValue.by_value
  attach_function 'model_ak185', [], ExcelValue.by_value
  attach_function 'model_al185', [], ExcelValue.by_value
  attach_function 'model_am185', [], ExcelValue.by_value
  attach_function 'model_an185', [], ExcelValue.by_value
  attach_function 'model_ao185', [], ExcelValue.by_value
  attach_function 'model_c186', [], ExcelValue.by_value
  attach_function 'model_d186', [], ExcelValue.by_value
  attach_function 'model_e186', [], ExcelValue.by_value
  attach_function 'model_f186', [], ExcelValue.by_value
  attach_function 'model_g186', [], ExcelValue.by_value
  attach_function 'model_h186', [], ExcelValue.by_value
  attach_function 'model_i186', [], ExcelValue.by_value
  attach_function 'model_j186', [], ExcelValue.by_value
  attach_function 'model_k186', [], ExcelValue.by_value
  attach_function 'model_l186', [], ExcelValue.by_value
  attach_function 'model_m186', [], ExcelValue.by_value
  attach_function 'model_n186', [], ExcelValue.by_value
  attach_function 'model_o186', [], ExcelValue.by_value
  attach_function 'model_p186', [], ExcelValue.by_value
  attach_function 'model_q186', [], ExcelValue.by_value
  attach_function 'model_r186', [], ExcelValue.by_value
  attach_function 'model_s186', [], ExcelValue.by_value
  attach_function 'model_t186', [], ExcelValue.by_value
  attach_function 'model_u186', [], ExcelValue.by_value
  attach_function 'model_v186', [], ExcelValue.by_value
  attach_function 'model_w186', [], ExcelValue.by_value
  attach_function 'model_x186', [], ExcelValue.by_value
  attach_function 'model_y186', [], ExcelValue.by_value
  attach_function 'model_z186', [], ExcelValue.by_value
  attach_function 'model_aa186', [], ExcelValue.by_value
  attach_function 'model_ab186', [], ExcelValue.by_value
  attach_function 'model_ac186', [], ExcelValue.by_value
  attach_function 'model_ad186', [], ExcelValue.by_value
  attach_function 'model_ae186', [], ExcelValue.by_value
  attach_function 'model_af186', [], ExcelValue.by_value
  attach_function 'model_ag186', [], ExcelValue.by_value
  attach_function 'model_ah186', [], ExcelValue.by_value
  attach_function 'model_ai186', [], ExcelValue.by_value
  attach_function 'model_aj186', [], ExcelValue.by_value
  attach_function 'model_ak186', [], ExcelValue.by_value
  attach_function 'model_al186', [], ExcelValue.by_value
  attach_function 'model_am186', [], ExcelValue.by_value
  attach_function 'model_an186', [], ExcelValue.by_value
  attach_function 'model_ao186', [], ExcelValue.by_value
  attach_function 'model_c188', [], ExcelValue.by_value
  attach_function 'model_d188', [], ExcelValue.by_value
  attach_function 'model_e188', [], ExcelValue.by_value
  attach_function 'model_f188', [], ExcelValue.by_value
  attach_function 'model_g188', [], ExcelValue.by_value
  attach_function 'model_h188', [], ExcelValue.by_value
  attach_function 'model_i188', [], ExcelValue.by_value
  attach_function 'model_j188', [], ExcelValue.by_value
  attach_function 'model_k188', [], ExcelValue.by_value
  attach_function 'model_l188', [], ExcelValue.by_value
  attach_function 'model_m188', [], ExcelValue.by_value
  attach_function 'model_n188', [], ExcelValue.by_value
  attach_function 'model_o188', [], ExcelValue.by_value
  attach_function 'model_p188', [], ExcelValue.by_value
  attach_function 'model_q188', [], ExcelValue.by_value
  attach_function 'model_r188', [], ExcelValue.by_value
  attach_function 'model_s188', [], ExcelValue.by_value
  attach_function 'model_t188', [], ExcelValue.by_value
  attach_function 'model_u188', [], ExcelValue.by_value
  attach_function 'model_v188', [], ExcelValue.by_value
  attach_function 'model_w188', [], ExcelValue.by_value
  attach_function 'model_x188', [], ExcelValue.by_value
  attach_function 'model_y188', [], ExcelValue.by_value
  attach_function 'model_z188', [], ExcelValue.by_value
  attach_function 'model_aa188', [], ExcelValue.by_value
  attach_function 'model_ab188', [], ExcelValue.by_value
  attach_function 'model_ac188', [], ExcelValue.by_value
  attach_function 'model_ad188', [], ExcelValue.by_value
  attach_function 'model_ae188', [], ExcelValue.by_value
  attach_function 'model_af188', [], ExcelValue.by_value
  attach_function 'model_ag188', [], ExcelValue.by_value
  attach_function 'model_ah188', [], ExcelValue.by_value
  attach_function 'model_ai188', [], ExcelValue.by_value
  attach_function 'model_aj188', [], ExcelValue.by_value
  attach_function 'model_ak188', [], ExcelValue.by_value
  attach_function 'model_al188', [], ExcelValue.by_value
  attach_function 'model_am188', [], ExcelValue.by_value
  attach_function 'model_an188', [], ExcelValue.by_value
  attach_function 'model_ao188', [], ExcelValue.by_value
  attach_function 'model_c187', [], ExcelValue.by_value
  attach_function 'model_d187', [], ExcelValue.by_value
  attach_function 'model_e187', [], ExcelValue.by_value
  attach_function 'model_f187', [], ExcelValue.by_value
  attach_function 'model_g187', [], ExcelValue.by_value
  attach_function 'model_h187', [], ExcelValue.by_value
  attach_function 'model_i187', [], ExcelValue.by_value
  attach_function 'model_j187', [], ExcelValue.by_value
  attach_function 'model_k187', [], ExcelValue.by_value
  attach_function 'model_l187', [], ExcelValue.by_value
  attach_function 'model_m187', [], ExcelValue.by_value
  attach_function 'model_n187', [], ExcelValue.by_value
  attach_function 'model_o187', [], ExcelValue.by_value
  attach_function 'model_p187', [], ExcelValue.by_value
  attach_function 'model_q187', [], ExcelValue.by_value
  attach_function 'model_r187', [], ExcelValue.by_value
  attach_function 'model_s187', [], ExcelValue.by_value
  attach_function 'model_t187', [], ExcelValue.by_value
  attach_function 'model_u187', [], ExcelValue.by_value
  attach_function 'model_v187', [], ExcelValue.by_value
  attach_function 'model_w187', [], ExcelValue.by_value
  attach_function 'model_x187', [], ExcelValue.by_value
  attach_function 'model_y187', [], ExcelValue.by_value
  attach_function 'model_z187', [], ExcelValue.by_value
  attach_function 'model_aa187', [], ExcelValue.by_value
  attach_function 'model_ab187', [], ExcelValue.by_value
  attach_function 'model_ac187', [], ExcelValue.by_value
  attach_function 'model_ad187', [], ExcelValue.by_value
  attach_function 'model_ae187', [], ExcelValue.by_value
  attach_function 'model_af187', [], ExcelValue.by_value
  attach_function 'model_ag187', [], ExcelValue.by_value
  attach_function 'model_ah187', [], ExcelValue.by_value
  attach_function 'model_ai187', [], ExcelValue.by_value
  attach_function 'model_aj187', [], ExcelValue.by_value
  attach_function 'model_ak187', [], ExcelValue.by_value
  attach_function 'model_al187', [], ExcelValue.by_value
  attach_function 'model_am187', [], ExcelValue.by_value
  attach_function 'model_an187', [], ExcelValue.by_value
  attach_function 'model_ao187', [], ExcelValue.by_value
  attach_function 'model_c177', [], ExcelValue.by_value
  attach_function 'model_d177', [], ExcelValue.by_value
  attach_function 'model_e177', [], ExcelValue.by_value
  attach_function 'model_f177', [], ExcelValue.by_value
  attach_function 'model_g177', [], ExcelValue.by_value
  attach_function 'model_h177', [], ExcelValue.by_value
  attach_function 'model_i177', [], ExcelValue.by_value
  attach_function 'model_j177', [], ExcelValue.by_value
  attach_function 'model_k177', [], ExcelValue.by_value
  attach_function 'model_l177', [], ExcelValue.by_value
  attach_function 'model_m177', [], ExcelValue.by_value
  attach_function 'model_n177', [], ExcelValue.by_value
  attach_function 'model_o177', [], ExcelValue.by_value
  attach_function 'model_p177', [], ExcelValue.by_value
  attach_function 'model_q177', [], ExcelValue.by_value
  attach_function 'model_r177', [], ExcelValue.by_value
  attach_function 'model_s177', [], ExcelValue.by_value
  attach_function 'model_t177', [], ExcelValue.by_value
  attach_function 'model_u177', [], ExcelValue.by_value
  attach_function 'model_v177', [], ExcelValue.by_value
  attach_function 'model_w177', [], ExcelValue.by_value
  attach_function 'model_x177', [], ExcelValue.by_value
  attach_function 'model_y177', [], ExcelValue.by_value
  attach_function 'model_z177', [], ExcelValue.by_value
  attach_function 'model_aa177', [], ExcelValue.by_value
  attach_function 'model_ab177', [], ExcelValue.by_value
  attach_function 'model_ac177', [], ExcelValue.by_value
  attach_function 'model_ad177', [], ExcelValue.by_value
  attach_function 'model_ae177', [], ExcelValue.by_value
  attach_function 'model_af177', [], ExcelValue.by_value
  attach_function 'model_ag177', [], ExcelValue.by_value
  attach_function 'model_ah177', [], ExcelValue.by_value
  attach_function 'model_ai177', [], ExcelValue.by_value
  attach_function 'model_aj177', [], ExcelValue.by_value
  attach_function 'model_ak177', [], ExcelValue.by_value
  attach_function 'model_al177', [], ExcelValue.by_value
  attach_function 'model_am177', [], ExcelValue.by_value
  attach_function 'model_an177', [], ExcelValue.by_value
  attach_function 'model_ao177', [], ExcelValue.by_value
  attach_function 'model_c179', [], ExcelValue.by_value
  attach_function 'model_d179', [], ExcelValue.by_value
  attach_function 'model_e179', [], ExcelValue.by_value
  attach_function 'model_f179', [], ExcelValue.by_value
  attach_function 'model_g179', [], ExcelValue.by_value
  attach_function 'model_h179', [], ExcelValue.by_value
  attach_function 'model_i179', [], ExcelValue.by_value
  attach_function 'model_j179', [], ExcelValue.by_value
  attach_function 'model_k179', [], ExcelValue.by_value
  attach_function 'model_l179', [], ExcelValue.by_value
  attach_function 'model_m179', [], ExcelValue.by_value
  attach_function 'model_n179', [], ExcelValue.by_value
  attach_function 'model_o179', [], ExcelValue.by_value
  attach_function 'model_p179', [], ExcelValue.by_value
  attach_function 'model_q179', [], ExcelValue.by_value
  attach_function 'model_r179', [], ExcelValue.by_value
  attach_function 'model_s179', [], ExcelValue.by_value
  attach_function 'model_t179', [], ExcelValue.by_value
  attach_function 'model_u179', [], ExcelValue.by_value
  attach_function 'model_v179', [], ExcelValue.by_value
  attach_function 'model_w179', [], ExcelValue.by_value
  attach_function 'model_x179', [], ExcelValue.by_value
  attach_function 'model_y179', [], ExcelValue.by_value
  attach_function 'model_z179', [], ExcelValue.by_value
  attach_function 'model_aa179', [], ExcelValue.by_value
  attach_function 'model_ab179', [], ExcelValue.by_value
  attach_function 'model_ac179', [], ExcelValue.by_value
  attach_function 'model_ad179', [], ExcelValue.by_value
  attach_function 'model_ae179', [], ExcelValue.by_value
  attach_function 'model_af179', [], ExcelValue.by_value
  attach_function 'model_ag179', [], ExcelValue.by_value
  attach_function 'model_ah179', [], ExcelValue.by_value
  attach_function 'model_ai179', [], ExcelValue.by_value
  attach_function 'model_aj179', [], ExcelValue.by_value
  attach_function 'model_ak179', [], ExcelValue.by_value
  attach_function 'model_al179', [], ExcelValue.by_value
  attach_function 'model_am179', [], ExcelValue.by_value
  attach_function 'model_an179', [], ExcelValue.by_value
  attach_function 'model_ao179', [], ExcelValue.by_value
  attach_function 'model_c176', [], ExcelValue.by_value
  attach_function 'model_d176', [], ExcelValue.by_value
  attach_function 'model_e176', [], ExcelValue.by_value
  attach_function 'model_f176', [], ExcelValue.by_value
  attach_function 'model_g176', [], ExcelValue.by_value
  attach_function 'model_h176', [], ExcelValue.by_value
  attach_function 'model_i176', [], ExcelValue.by_value
  attach_function 'model_j176', [], ExcelValue.by_value
  attach_function 'model_k176', [], ExcelValue.by_value
  attach_function 'model_l176', [], ExcelValue.by_value
  attach_function 'model_m176', [], ExcelValue.by_value
  attach_function 'model_n176', [], ExcelValue.by_value
  attach_function 'model_o176', [], ExcelValue.by_value
  attach_function 'model_p176', [], ExcelValue.by_value
  attach_function 'model_q176', [], ExcelValue.by_value
  attach_function 'model_r176', [], ExcelValue.by_value
  attach_function 'model_s176', [], ExcelValue.by_value
  attach_function 'model_t176', [], ExcelValue.by_value
  attach_function 'model_u176', [], ExcelValue.by_value
  attach_function 'model_v176', [], ExcelValue.by_value
  attach_function 'model_w176', [], ExcelValue.by_value
  attach_function 'model_x176', [], ExcelValue.by_value
  attach_function 'model_y176', [], ExcelValue.by_value
  attach_function 'model_z176', [], ExcelValue.by_value
  attach_function 'model_aa176', [], ExcelValue.by_value
  attach_function 'model_ab176', [], ExcelValue.by_value
  attach_function 'model_ac176', [], ExcelValue.by_value
  attach_function 'model_ad176', [], ExcelValue.by_value
  attach_function 'model_ae176', [], ExcelValue.by_value
  attach_function 'model_af176', [], ExcelValue.by_value
  attach_function 'model_ag176', [], ExcelValue.by_value
  attach_function 'model_ah176', [], ExcelValue.by_value
  attach_function 'model_ai176', [], ExcelValue.by_value
  attach_function 'model_aj176', [], ExcelValue.by_value
  attach_function 'model_ak176', [], ExcelValue.by_value
  attach_function 'model_al176', [], ExcelValue.by_value
  attach_function 'model_am176', [], ExcelValue.by_value
  attach_function 'model_an176', [], ExcelValue.by_value
  attach_function 'model_ao176', [], ExcelValue.by_value
  attach_function 'model_c178', [], ExcelValue.by_value
  attach_function 'model_d178', [], ExcelValue.by_value
  attach_function 'model_e178', [], ExcelValue.by_value
  attach_function 'model_f178', [], ExcelValue.by_value
  attach_function 'model_g178', [], ExcelValue.by_value
  attach_function 'model_h178', [], ExcelValue.by_value
  attach_function 'model_i178', [], ExcelValue.by_value
  attach_function 'model_j178', [], ExcelValue.by_value
  attach_function 'model_k178', [], ExcelValue.by_value
  attach_function 'model_l178', [], ExcelValue.by_value
  attach_function 'model_m178', [], ExcelValue.by_value
  attach_function 'model_n178', [], ExcelValue.by_value
  attach_function 'model_o178', [], ExcelValue.by_value
  attach_function 'model_p178', [], ExcelValue.by_value
  attach_function 'model_q178', [], ExcelValue.by_value
  attach_function 'model_r178', [], ExcelValue.by_value
  attach_function 'model_s178', [], ExcelValue.by_value
  attach_function 'model_t178', [], ExcelValue.by_value
  attach_function 'model_u178', [], ExcelValue.by_value
  attach_function 'model_v178', [], ExcelValue.by_value
  attach_function 'model_w178', [], ExcelValue.by_value
  attach_function 'model_x178', [], ExcelValue.by_value
  attach_function 'model_y178', [], ExcelValue.by_value
  attach_function 'model_z178', [], ExcelValue.by_value
  attach_function 'model_aa178', [], ExcelValue.by_value
  attach_function 'model_ab178', [], ExcelValue.by_value
  attach_function 'model_ac178', [], ExcelValue.by_value
  attach_function 'model_ad178', [], ExcelValue.by_value
  attach_function 'model_ae178', [], ExcelValue.by_value
  attach_function 'model_af178', [], ExcelValue.by_value
  attach_function 'model_ag178', [], ExcelValue.by_value
  attach_function 'model_ah178', [], ExcelValue.by_value
  attach_function 'model_ai178', [], ExcelValue.by_value
  attach_function 'model_aj178', [], ExcelValue.by_value
  attach_function 'model_ak178', [], ExcelValue.by_value
  attach_function 'model_al178', [], ExcelValue.by_value
  attach_function 'model_am178', [], ExcelValue.by_value
  attach_function 'model_an178', [], ExcelValue.by_value
  attach_function 'model_ao178', [], ExcelValue.by_value
  attach_function 'model_c114', [], ExcelValue.by_value
  attach_function 'model_c171', [], ExcelValue.by_value
  attach_function 'model_d171', [], ExcelValue.by_value
  attach_function 'model_e171', [], ExcelValue.by_value
  attach_function 'model_f171', [], ExcelValue.by_value
  attach_function 'model_g171', [], ExcelValue.by_value
  attach_function 'model_h171', [], ExcelValue.by_value
  attach_function 'model_i171', [], ExcelValue.by_value
  attach_function 'model_j171', [], ExcelValue.by_value
  attach_function 'model_k171', [], ExcelValue.by_value
  attach_function 'model_l171', [], ExcelValue.by_value
  attach_function 'model_m171', [], ExcelValue.by_value
  attach_function 'model_n171', [], ExcelValue.by_value
  attach_function 'model_o171', [], ExcelValue.by_value
  attach_function 'model_p171', [], ExcelValue.by_value
  attach_function 'model_q171', [], ExcelValue.by_value
  attach_function 'model_r171', [], ExcelValue.by_value
  attach_function 'model_s171', [], ExcelValue.by_value
  attach_function 'model_t171', [], ExcelValue.by_value
  attach_function 'model_u171', [], ExcelValue.by_value
  attach_function 'model_v171', [], ExcelValue.by_value
  attach_function 'model_w171', [], ExcelValue.by_value
  attach_function 'model_x171', [], ExcelValue.by_value
  attach_function 'model_y171', [], ExcelValue.by_value
  attach_function 'model_z171', [], ExcelValue.by_value
  attach_function 'model_aa171', [], ExcelValue.by_value
  attach_function 'model_ab171', [], ExcelValue.by_value
  attach_function 'model_ac171', [], ExcelValue.by_value
  attach_function 'model_ad171', [], ExcelValue.by_value
  attach_function 'model_ae171', [], ExcelValue.by_value
  attach_function 'model_af171', [], ExcelValue.by_value
  attach_function 'model_ag171', [], ExcelValue.by_value
  attach_function 'model_ah171', [], ExcelValue.by_value
  attach_function 'model_ai171', [], ExcelValue.by_value
  attach_function 'model_aj171', [], ExcelValue.by_value
  attach_function 'model_ak171', [], ExcelValue.by_value
  attach_function 'model_al171', [], ExcelValue.by_value
  attach_function 'model_am171', [], ExcelValue.by_value
  attach_function 'model_an171', [], ExcelValue.by_value
  attach_function 'model_ao171', [], ExcelValue.by_value
  attach_function 'model_c173', [], ExcelValue.by_value
  attach_function 'model_d173', [], ExcelValue.by_value
  attach_function 'model_e173', [], ExcelValue.by_value
  attach_function 'model_f173', [], ExcelValue.by_value
  attach_function 'model_g173', [], ExcelValue.by_value
  attach_function 'model_h173', [], ExcelValue.by_value
  attach_function 'model_i173', [], ExcelValue.by_value
  attach_function 'model_j173', [], ExcelValue.by_value
  attach_function 'model_k173', [], ExcelValue.by_value
  attach_function 'model_l173', [], ExcelValue.by_value
  attach_function 'model_m173', [], ExcelValue.by_value
  attach_function 'model_n173', [], ExcelValue.by_value
  attach_function 'model_o173', [], ExcelValue.by_value
  attach_function 'model_p173', [], ExcelValue.by_value
  attach_function 'model_q173', [], ExcelValue.by_value
  attach_function 'model_r173', [], ExcelValue.by_value
  attach_function 'model_s173', [], ExcelValue.by_value
  attach_function 'model_t173', [], ExcelValue.by_value
  attach_function 'model_u173', [], ExcelValue.by_value
  attach_function 'model_v173', [], ExcelValue.by_value
  attach_function 'model_w173', [], ExcelValue.by_value
  attach_function 'model_x173', [], ExcelValue.by_value
  attach_function 'model_y173', [], ExcelValue.by_value
  attach_function 'model_z173', [], ExcelValue.by_value
  attach_function 'model_aa173', [], ExcelValue.by_value
  attach_function 'model_ab173', [], ExcelValue.by_value
  attach_function 'model_ac173', [], ExcelValue.by_value
  attach_function 'model_ad173', [], ExcelValue.by_value
  attach_function 'model_ae173', [], ExcelValue.by_value
  attach_function 'model_af173', [], ExcelValue.by_value
  attach_function 'model_ag173', [], ExcelValue.by_value
  attach_function 'model_ah173', [], ExcelValue.by_value
  attach_function 'model_ai173', [], ExcelValue.by_value
  attach_function 'model_aj173', [], ExcelValue.by_value
  attach_function 'model_ak173', [], ExcelValue.by_value
  attach_function 'model_al173', [], ExcelValue.by_value
  attach_function 'model_am173', [], ExcelValue.by_value
  attach_function 'model_an173', [], ExcelValue.by_value
  attach_function 'model_ao173', [], ExcelValue.by_value
  attach_function 'model_c170', [], ExcelValue.by_value
  attach_function 'model_d170', [], ExcelValue.by_value
  attach_function 'model_e170', [], ExcelValue.by_value
  attach_function 'model_f170', [], ExcelValue.by_value
  attach_function 'model_g170', [], ExcelValue.by_value
  attach_function 'model_h170', [], ExcelValue.by_value
  attach_function 'model_i170', [], ExcelValue.by_value
  attach_function 'model_j170', [], ExcelValue.by_value
  attach_function 'model_k170', [], ExcelValue.by_value
  attach_function 'model_l170', [], ExcelValue.by_value
  attach_function 'model_m170', [], ExcelValue.by_value
  attach_function 'model_n170', [], ExcelValue.by_value
  attach_function 'model_o170', [], ExcelValue.by_value
  attach_function 'model_p170', [], ExcelValue.by_value
  attach_function 'model_q170', [], ExcelValue.by_value
  attach_function 'model_r170', [], ExcelValue.by_value
  attach_function 'model_s170', [], ExcelValue.by_value
  attach_function 'model_t170', [], ExcelValue.by_value
  attach_function 'model_u170', [], ExcelValue.by_value
  attach_function 'model_v170', [], ExcelValue.by_value
  attach_function 'model_w170', [], ExcelValue.by_value
  attach_function 'model_x170', [], ExcelValue.by_value
  attach_function 'model_y170', [], ExcelValue.by_value
  attach_function 'model_z170', [], ExcelValue.by_value
  attach_function 'model_aa170', [], ExcelValue.by_value
  attach_function 'model_ab170', [], ExcelValue.by_value
  attach_function 'model_ac170', [], ExcelValue.by_value
  attach_function 'model_ad170', [], ExcelValue.by_value
  attach_function 'model_ae170', [], ExcelValue.by_value
  attach_function 'model_af170', [], ExcelValue.by_value
  attach_function 'model_ag170', [], ExcelValue.by_value
  attach_function 'model_ah170', [], ExcelValue.by_value
  attach_function 'model_ai170', [], ExcelValue.by_value
  attach_function 'model_aj170', [], ExcelValue.by_value
  attach_function 'model_ak170', [], ExcelValue.by_value
  attach_function 'model_al170', [], ExcelValue.by_value
  attach_function 'model_am170', [], ExcelValue.by_value
  attach_function 'model_an170', [], ExcelValue.by_value
  attach_function 'model_ao170', [], ExcelValue.by_value
  attach_function 'model_c172', [], ExcelValue.by_value
  attach_function 'model_d172', [], ExcelValue.by_value
  attach_function 'model_e172', [], ExcelValue.by_value
  attach_function 'model_f172', [], ExcelValue.by_value
  attach_function 'model_g172', [], ExcelValue.by_value
  attach_function 'model_h172', [], ExcelValue.by_value
  attach_function 'model_i172', [], ExcelValue.by_value
  attach_function 'model_j172', [], ExcelValue.by_value
  attach_function 'model_k172', [], ExcelValue.by_value
  attach_function 'model_l172', [], ExcelValue.by_value
  attach_function 'model_m172', [], ExcelValue.by_value
  attach_function 'model_n172', [], ExcelValue.by_value
  attach_function 'model_o172', [], ExcelValue.by_value
  attach_function 'model_p172', [], ExcelValue.by_value
  attach_function 'model_q172', [], ExcelValue.by_value
  attach_function 'model_r172', [], ExcelValue.by_value
  attach_function 'model_s172', [], ExcelValue.by_value
  attach_function 'model_t172', [], ExcelValue.by_value
  attach_function 'model_u172', [], ExcelValue.by_value
  attach_function 'model_v172', [], ExcelValue.by_value
  attach_function 'model_w172', [], ExcelValue.by_value
  attach_function 'model_x172', [], ExcelValue.by_value
  attach_function 'model_y172', [], ExcelValue.by_value
  attach_function 'model_z172', [], ExcelValue.by_value
  attach_function 'model_aa172', [], ExcelValue.by_value
  attach_function 'model_ab172', [], ExcelValue.by_value
  attach_function 'model_ac172', [], ExcelValue.by_value
  attach_function 'model_ad172', [], ExcelValue.by_value
  attach_function 'model_ae172', [], ExcelValue.by_value
  attach_function 'model_af172', [], ExcelValue.by_value
  attach_function 'model_ag172', [], ExcelValue.by_value
  attach_function 'model_ah172', [], ExcelValue.by_value
  attach_function 'model_ai172', [], ExcelValue.by_value
  attach_function 'model_aj172', [], ExcelValue.by_value
  attach_function 'model_ak172', [], ExcelValue.by_value
  attach_function 'model_al172', [], ExcelValue.by_value
  attach_function 'model_am172', [], ExcelValue.by_value
  attach_function 'model_an172', [], ExcelValue.by_value
  attach_function 'model_ao172', [], ExcelValue.by_value
  attach_function 'model_c169', [], ExcelValue.by_value
  attach_function 'model_d169', [], ExcelValue.by_value
  attach_function 'model_e169', [], ExcelValue.by_value
  attach_function 'model_f169', [], ExcelValue.by_value
  attach_function 'model_g169', [], ExcelValue.by_value
  attach_function 'model_h169', [], ExcelValue.by_value
  attach_function 'model_i169', [], ExcelValue.by_value
  attach_function 'model_j169', [], ExcelValue.by_value
  attach_function 'model_k169', [], ExcelValue.by_value
  attach_function 'model_l169', [], ExcelValue.by_value
  attach_function 'model_m169', [], ExcelValue.by_value
  attach_function 'model_n169', [], ExcelValue.by_value
  attach_function 'model_o169', [], ExcelValue.by_value
  attach_function 'model_p169', [], ExcelValue.by_value
  attach_function 'model_q169', [], ExcelValue.by_value
  attach_function 'model_r169', [], ExcelValue.by_value
  attach_function 'model_s169', [], ExcelValue.by_value
  attach_function 'model_t169', [], ExcelValue.by_value
  attach_function 'model_u169', [], ExcelValue.by_value
  attach_function 'model_v169', [], ExcelValue.by_value
  attach_function 'model_w169', [], ExcelValue.by_value
  attach_function 'model_x169', [], ExcelValue.by_value
  attach_function 'model_y169', [], ExcelValue.by_value
  attach_function 'model_z169', [], ExcelValue.by_value
  attach_function 'model_aa169', [], ExcelValue.by_value
  attach_function 'model_ab169', [], ExcelValue.by_value
  attach_function 'model_ac169', [], ExcelValue.by_value
  attach_function 'model_ad169', [], ExcelValue.by_value
  attach_function 'model_ae169', [], ExcelValue.by_value
  attach_function 'model_af169', [], ExcelValue.by_value
  attach_function 'model_ag169', [], ExcelValue.by_value
  attach_function 'model_ah169', [], ExcelValue.by_value
  attach_function 'model_ai169', [], ExcelValue.by_value
  attach_function 'model_aj169', [], ExcelValue.by_value
  attach_function 'model_ak169', [], ExcelValue.by_value
  attach_function 'model_al169', [], ExcelValue.by_value
  attach_function 'model_am169', [], ExcelValue.by_value
  attach_function 'model_an169', [], ExcelValue.by_value
  attach_function 'model_ao169', [], ExcelValue.by_value
  attach_function 'model_c39', [], ExcelValue.by_value
  attach_function 'model_c38', [], ExcelValue.by_value
  attach_function 'model_c165', [], ExcelValue.by_value
  attach_function 'model_d165', [], ExcelValue.by_value
  attach_function 'model_e165', [], ExcelValue.by_value
  attach_function 'model_f165', [], ExcelValue.by_value
  attach_function 'model_g165', [], ExcelValue.by_value
  attach_function 'model_h165', [], ExcelValue.by_value
  attach_function 'model_i165', [], ExcelValue.by_value
  attach_function 'model_j165', [], ExcelValue.by_value
  attach_function 'model_k165', [], ExcelValue.by_value
  attach_function 'model_l165', [], ExcelValue.by_value
  attach_function 'model_m165', [], ExcelValue.by_value
  attach_function 'model_n165', [], ExcelValue.by_value
  attach_function 'model_o165', [], ExcelValue.by_value
  attach_function 'model_p165', [], ExcelValue.by_value
  attach_function 'model_q165', [], ExcelValue.by_value
  attach_function 'model_r165', [], ExcelValue.by_value
  attach_function 'model_s165', [], ExcelValue.by_value
  attach_function 'model_t165', [], ExcelValue.by_value
  attach_function 'model_u165', [], ExcelValue.by_value
  attach_function 'model_v165', [], ExcelValue.by_value
  attach_function 'model_w165', [], ExcelValue.by_value
  attach_function 'model_x165', [], ExcelValue.by_value
  attach_function 'model_y165', [], ExcelValue.by_value
  attach_function 'model_z165', [], ExcelValue.by_value
  attach_function 'model_aa165', [], ExcelValue.by_value
  attach_function 'model_ab165', [], ExcelValue.by_value
  attach_function 'model_ac165', [], ExcelValue.by_value
  attach_function 'model_ad165', [], ExcelValue.by_value
  attach_function 'model_ae165', [], ExcelValue.by_value
  attach_function 'model_af165', [], ExcelValue.by_value
  attach_function 'model_ag165', [], ExcelValue.by_value
  attach_function 'model_ah165', [], ExcelValue.by_value
  attach_function 'model_ai165', [], ExcelValue.by_value
  attach_function 'model_aj165', [], ExcelValue.by_value
  attach_function 'model_ak165', [], ExcelValue.by_value
  attach_function 'model_al165', [], ExcelValue.by_value
  attach_function 'model_am165', [], ExcelValue.by_value
  attach_function 'model_an165', [], ExcelValue.by_value
  attach_function 'model_ao165', [], ExcelValue.by_value
  attach_function 'model_c37', [], ExcelValue.by_value
  attach_function 'model_c166', [], ExcelValue.by_value
  attach_function 'model_d166', [], ExcelValue.by_value
  attach_function 'model_e166', [], ExcelValue.by_value
  attach_function 'model_f166', [], ExcelValue.by_value
  attach_function 'model_g166', [], ExcelValue.by_value
  attach_function 'model_h166', [], ExcelValue.by_value
  attach_function 'model_i166', [], ExcelValue.by_value
  attach_function 'model_j166', [], ExcelValue.by_value
  attach_function 'model_k166', [], ExcelValue.by_value
  attach_function 'model_l166', [], ExcelValue.by_value
  attach_function 'model_m166', [], ExcelValue.by_value
  attach_function 'model_n166', [], ExcelValue.by_value
  attach_function 'model_o166', [], ExcelValue.by_value
  attach_function 'model_p166', [], ExcelValue.by_value
  attach_function 'model_q166', [], ExcelValue.by_value
  attach_function 'model_r166', [], ExcelValue.by_value
  attach_function 'model_s166', [], ExcelValue.by_value
  attach_function 'model_t166', [], ExcelValue.by_value
  attach_function 'model_u166', [], ExcelValue.by_value
  attach_function 'model_v166', [], ExcelValue.by_value
  attach_function 'model_w166', [], ExcelValue.by_value
  attach_function 'model_x166', [], ExcelValue.by_value
  attach_function 'model_y166', [], ExcelValue.by_value
  attach_function 'model_z166', [], ExcelValue.by_value
  attach_function 'model_aa166', [], ExcelValue.by_value
  attach_function 'model_ab166', [], ExcelValue.by_value
  attach_function 'model_ac166', [], ExcelValue.by_value
  attach_function 'model_ad166', [], ExcelValue.by_value
  attach_function 'model_ae166', [], ExcelValue.by_value
  attach_function 'model_af166', [], ExcelValue.by_value
  attach_function 'model_ag166', [], ExcelValue.by_value
  attach_function 'model_ah166', [], ExcelValue.by_value
  attach_function 'model_ai166', [], ExcelValue.by_value
  attach_function 'model_aj166', [], ExcelValue.by_value
  attach_function 'model_ak166', [], ExcelValue.by_value
  attach_function 'model_al166', [], ExcelValue.by_value
  attach_function 'model_am166', [], ExcelValue.by_value
  attach_function 'model_an166', [], ExcelValue.by_value
  attach_function 'model_ao166', [], ExcelValue.by_value
  attach_function 'model_c30', [], ExcelValue.by_value
  attach_function 'model_c35', [], ExcelValue.by_value
  attach_function 'model_c191', [], ExcelValue.by_value
  attach_function 'model_d191', [], ExcelValue.by_value
  attach_function 'model_e191', [], ExcelValue.by_value
  attach_function 'model_f191', [], ExcelValue.by_value
  attach_function 'model_g191', [], ExcelValue.by_value
  attach_function 'model_h191', [], ExcelValue.by_value
  attach_function 'model_i191', [], ExcelValue.by_value
  attach_function 'model_j191', [], ExcelValue.by_value
  attach_function 'model_k191', [], ExcelValue.by_value
  attach_function 'model_l191', [], ExcelValue.by_value
  attach_function 'model_m191', [], ExcelValue.by_value
  attach_function 'model_n191', [], ExcelValue.by_value
  attach_function 'model_o191', [], ExcelValue.by_value
  attach_function 'model_p191', [], ExcelValue.by_value
  attach_function 'model_q191', [], ExcelValue.by_value
  attach_function 'model_r191', [], ExcelValue.by_value
  attach_function 'model_s191', [], ExcelValue.by_value
  attach_function 'model_t191', [], ExcelValue.by_value
  attach_function 'model_u191', [], ExcelValue.by_value
  attach_function 'model_v191', [], ExcelValue.by_value
  attach_function 'model_w191', [], ExcelValue.by_value
  attach_function 'model_x191', [], ExcelValue.by_value
  attach_function 'model_y191', [], ExcelValue.by_value
  attach_function 'model_z191', [], ExcelValue.by_value
  attach_function 'model_aa191', [], ExcelValue.by_value
  attach_function 'model_ab191', [], ExcelValue.by_value
  attach_function 'model_ac191', [], ExcelValue.by_value
  attach_function 'model_ad191', [], ExcelValue.by_value
  attach_function 'model_ae191', [], ExcelValue.by_value
  attach_function 'model_af191', [], ExcelValue.by_value
  attach_function 'model_ag191', [], ExcelValue.by_value
  attach_function 'model_ah191', [], ExcelValue.by_value
  attach_function 'model_ai191', [], ExcelValue.by_value
  attach_function 'model_aj191', [], ExcelValue.by_value
  attach_function 'model_ak191', [], ExcelValue.by_value
  attach_function 'model_al191', [], ExcelValue.by_value
  attach_function 'model_am191', [], ExcelValue.by_value
  attach_function 'model_an191', [], ExcelValue.by_value
  attach_function 'model_ao191', [], ExcelValue.by_value
  attach_function 'model_c194', [], ExcelValue.by_value
  attach_function 'model_d194', [], ExcelValue.by_value
  attach_function 'model_e194', [], ExcelValue.by_value
  attach_function 'model_f194', [], ExcelValue.by_value
  attach_function 'model_g194', [], ExcelValue.by_value
  attach_function 'model_h194', [], ExcelValue.by_value
  attach_function 'model_i194', [], ExcelValue.by_value
  attach_function 'model_j194', [], ExcelValue.by_value
  attach_function 'model_k194', [], ExcelValue.by_value
  attach_function 'model_l194', [], ExcelValue.by_value
  attach_function 'model_m194', [], ExcelValue.by_value
  attach_function 'model_n194', [], ExcelValue.by_value
  attach_function 'model_o194', [], ExcelValue.by_value
  attach_function 'model_p194', [], ExcelValue.by_value
  attach_function 'model_q194', [], ExcelValue.by_value
  attach_function 'model_r194', [], ExcelValue.by_value
  attach_function 'model_s194', [], ExcelValue.by_value
  attach_function 'model_t194', [], ExcelValue.by_value
  attach_function 'model_u194', [], ExcelValue.by_value
  attach_function 'model_v194', [], ExcelValue.by_value
  attach_function 'model_w194', [], ExcelValue.by_value
  attach_function 'model_x194', [], ExcelValue.by_value
  attach_function 'model_y194', [], ExcelValue.by_value
  attach_function 'model_z194', [], ExcelValue.by_value
  attach_function 'model_aa194', [], ExcelValue.by_value
  attach_function 'model_ab194', [], ExcelValue.by_value
  attach_function 'model_ac194', [], ExcelValue.by_value
  attach_function 'model_ad194', [], ExcelValue.by_value
  attach_function 'model_ae194', [], ExcelValue.by_value
  attach_function 'model_af194', [], ExcelValue.by_value
  attach_function 'model_ag194', [], ExcelValue.by_value
  attach_function 'model_ah194', [], ExcelValue.by_value
  attach_function 'model_ai194', [], ExcelValue.by_value
  attach_function 'model_aj194', [], ExcelValue.by_value
  attach_function 'model_ak194', [], ExcelValue.by_value
  attach_function 'model_al194', [], ExcelValue.by_value
  attach_function 'model_am194', [], ExcelValue.by_value
  attach_function 'model_an194', [], ExcelValue.by_value
  attach_function 'model_ao194', [], ExcelValue.by_value
  attach_function 'model_c193', [], ExcelValue.by_value
  attach_function 'model_d193', [], ExcelValue.by_value
  attach_function 'model_e193', [], ExcelValue.by_value
  attach_function 'model_f193', [], ExcelValue.by_value
  attach_function 'model_g193', [], ExcelValue.by_value
  attach_function 'model_h193', [], ExcelValue.by_value
  attach_function 'model_i193', [], ExcelValue.by_value
  attach_function 'model_j193', [], ExcelValue.by_value
  attach_function 'model_k193', [], ExcelValue.by_value
  attach_function 'model_l193', [], ExcelValue.by_value
  attach_function 'model_m193', [], ExcelValue.by_value
  attach_function 'model_n193', [], ExcelValue.by_value
  attach_function 'model_o193', [], ExcelValue.by_value
  attach_function 'model_p193', [], ExcelValue.by_value
  attach_function 'model_q193', [], ExcelValue.by_value
  attach_function 'model_r193', [], ExcelValue.by_value
  attach_function 'model_s193', [], ExcelValue.by_value
  attach_function 'model_t193', [], ExcelValue.by_value
  attach_function 'model_u193', [], ExcelValue.by_value
  attach_function 'model_v193', [], ExcelValue.by_value
  attach_function 'model_w193', [], ExcelValue.by_value
  attach_function 'model_x193', [], ExcelValue.by_value
  attach_function 'model_y193', [], ExcelValue.by_value
  attach_function 'model_z193', [], ExcelValue.by_value
  attach_function 'model_aa193', [], ExcelValue.by_value
  attach_function 'model_ab193', [], ExcelValue.by_value
  attach_function 'model_ac193', [], ExcelValue.by_value
  attach_function 'model_ad193', [], ExcelValue.by_value
  attach_function 'model_ae193', [], ExcelValue.by_value
  attach_function 'model_af193', [], ExcelValue.by_value
  attach_function 'model_ag193', [], ExcelValue.by_value
  attach_function 'model_ah193', [], ExcelValue.by_value
  attach_function 'model_ai193', [], ExcelValue.by_value
  attach_function 'model_aj193', [], ExcelValue.by_value
  attach_function 'model_ak193', [], ExcelValue.by_value
  attach_function 'model_al193', [], ExcelValue.by_value
  attach_function 'model_am193', [], ExcelValue.by_value
  attach_function 'model_an193', [], ExcelValue.by_value
  attach_function 'model_ao193', [], ExcelValue.by_value
  attach_function 'model_c192', [], ExcelValue.by_value
  attach_function 'model_d192', [], ExcelValue.by_value
  attach_function 'model_e192', [], ExcelValue.by_value
  attach_function 'model_f192', [], ExcelValue.by_value
  attach_function 'model_g192', [], ExcelValue.by_value
  attach_function 'model_h192', [], ExcelValue.by_value
  attach_function 'model_i192', [], ExcelValue.by_value
  attach_function 'model_j192', [], ExcelValue.by_value
  attach_function 'model_k192', [], ExcelValue.by_value
  attach_function 'model_l192', [], ExcelValue.by_value
  attach_function 'model_m192', [], ExcelValue.by_value
  attach_function 'model_n192', [], ExcelValue.by_value
  attach_function 'model_o192', [], ExcelValue.by_value
  attach_function 'model_p192', [], ExcelValue.by_value
  attach_function 'model_q192', [], ExcelValue.by_value
  attach_function 'model_r192', [], ExcelValue.by_value
  attach_function 'model_s192', [], ExcelValue.by_value
  attach_function 'model_t192', [], ExcelValue.by_value
  attach_function 'model_u192', [], ExcelValue.by_value
  attach_function 'model_v192', [], ExcelValue.by_value
  attach_function 'model_w192', [], ExcelValue.by_value
  attach_function 'model_x192', [], ExcelValue.by_value
  attach_function 'model_y192', [], ExcelValue.by_value
  attach_function 'model_z192', [], ExcelValue.by_value
  attach_function 'model_aa192', [], ExcelValue.by_value
  attach_function 'model_ab192', [], ExcelValue.by_value
  attach_function 'model_ac192', [], ExcelValue.by_value
  attach_function 'model_ad192', [], ExcelValue.by_value
  attach_function 'model_ae192', [], ExcelValue.by_value
  attach_function 'model_af192', [], ExcelValue.by_value
  attach_function 'model_ag192', [], ExcelValue.by_value
  attach_function 'model_ah192', [], ExcelValue.by_value
  attach_function 'model_ai192', [], ExcelValue.by_value
  attach_function 'model_aj192', [], ExcelValue.by_value
  attach_function 'model_ak192', [], ExcelValue.by_value
  attach_function 'model_al192', [], ExcelValue.by_value
  attach_function 'model_am192', [], ExcelValue.by_value
  attach_function 'model_an192', [], ExcelValue.by_value
  attach_function 'model_ao192', [], ExcelValue.by_value
  attach_function 'model_c195', [], ExcelValue.by_value
  attach_function 'model_d195', [], ExcelValue.by_value
  attach_function 'model_e195', [], ExcelValue.by_value
  attach_function 'model_f195', [], ExcelValue.by_value
  attach_function 'model_g195', [], ExcelValue.by_value
  attach_function 'model_h195', [], ExcelValue.by_value
  attach_function 'model_i195', [], ExcelValue.by_value
  attach_function 'model_j195', [], ExcelValue.by_value
  attach_function 'model_k195', [], ExcelValue.by_value
  attach_function 'model_l195', [], ExcelValue.by_value
  attach_function 'model_m195', [], ExcelValue.by_value
  attach_function 'model_n195', [], ExcelValue.by_value
  attach_function 'model_o195', [], ExcelValue.by_value
  attach_function 'model_p195', [], ExcelValue.by_value
  attach_function 'model_q195', [], ExcelValue.by_value
  attach_function 'model_r195', [], ExcelValue.by_value
  attach_function 'model_s195', [], ExcelValue.by_value
  attach_function 'model_t195', [], ExcelValue.by_value
  attach_function 'model_u195', [], ExcelValue.by_value
  attach_function 'model_v195', [], ExcelValue.by_value
  attach_function 'model_w195', [], ExcelValue.by_value
  attach_function 'model_x195', [], ExcelValue.by_value
  attach_function 'model_y195', [], ExcelValue.by_value
  attach_function 'model_z195', [], ExcelValue.by_value
  attach_function 'model_aa195', [], ExcelValue.by_value
  attach_function 'model_ab195', [], ExcelValue.by_value
  attach_function 'model_ac195', [], ExcelValue.by_value
  attach_function 'model_ad195', [], ExcelValue.by_value
  attach_function 'model_ae195', [], ExcelValue.by_value
  attach_function 'model_af195', [], ExcelValue.by_value
  attach_function 'model_ag195', [], ExcelValue.by_value
  attach_function 'model_ah195', [], ExcelValue.by_value
  attach_function 'model_ai195', [], ExcelValue.by_value
  attach_function 'model_aj195', [], ExcelValue.by_value
  attach_function 'model_ak195', [], ExcelValue.by_value
  attach_function 'model_al195', [], ExcelValue.by_value
  attach_function 'model_am195', [], ExcelValue.by_value
  attach_function 'model_an195', [], ExcelValue.by_value
  attach_function 'model_ao195', [], ExcelValue.by_value
  attach_function 'model_p20', [], ExcelValue.by_value
  attach_function 'model_c113', [], ExcelValue.by_value
  attach_function 'model_c23', [], ExcelValue.by_value
  attach_function 'model_c33', [], ExcelValue.by_value
  # end of Model

  # start of Charts
  # end of Charts
  # Start of named references
  attach_function 'n_2012_onwards_electricity_demand_growth_rate', [], ExcelValue.by_value
  attach_function 'n_2020_fossil_fuel_emissions_factor', [], ExcelValue.by_value
  attach_function 'n_2020_non_renewable_low_carbon_generation_i_e_nuclear_ccs', [], ExcelValue.by_value
  attach_function 'n_2020_renewables_target', [], ExcelValue.by_value
  attach_function 'n_2020_renewables_target_gco2_kwh', [], ExcelValue.by_value
  attach_function 'n_2020_renewables_target_twh', [], ExcelValue.by_value
  attach_function 'n_2030_cost_of_carbon', [], ExcelValue.by_value
  attach_function 'n_2030_cost_of_fossil_fuel', [], ExcelValue.by_value
  attach_function 'n_2030_decarbonisation_level', [], ExcelValue.by_value
  attach_function 'n_2050_cost_of_carbon', [], ExcelValue.by_value
  attach_function 'n_2050_cost_of_fossil_fuel', [], ExcelValue.by_value
  attach_function 'n_2050_electricity_demand', [], ExcelValue.by_value
  attach_function 'n_2050_emissions_electricity', [], ExcelValue.by_value
  attach_function 'n_2050_emissions_industry', [], ExcelValue.by_value
  attach_function 'n_2050_emissions_total', [], ExcelValue.by_value
  attach_function 'n_2050_fossil_fuel_emissions_factor', [], ExcelValue.by_value
  attach_function 'n_2050_maximum_electricity_demand', [], ExcelValue.by_value
  attach_function 'n_2050_minimum_electricity_demand', [], ExcelValue.by_value
  attach_function 'annual_change_in_non_electricity_traded_emissions', [], ExcelValue.by_value
  attach_function 'annual_change_in_non_electricity_traded_emissions_after_radical_change', [], ExcelValue.by_value
  attach_function 'annual_reduction_in_cost_of_high_carbon_generation', [], ExcelValue.by_value
  attach_function 'annual_reduction_in_cost_of_intermittent_generation', [], ExcelValue.by_value
  attach_function 'annual_reduction_in_cost_of_other_low_carbon_generation', [], ExcelValue.by_value
  attach_function 'average_life_high_carbon', [], ExcelValue.by_value
  attach_function 'average_life_other_low_carbon', [], ExcelValue.by_value
  attach_function 'average_life_wind', [], ExcelValue.by_value
  attach_function 'baseload_demand', [], ExcelValue.by_value
  attach_function 'build_rate_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'build_rate_from_now_to_2020', [], ExcelValue.by_value
  attach_function 'build_rate_high_carbon', [], ExcelValue.by_value
  attach_function 'build_rate_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'build_rate_target_in_second_build', [], ExcelValue.by_value
  attach_function 'build_rate_total_low_carbon', [], ExcelValue.by_value
  attach_function 'capacity_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'capacity_high_carbon', [], ExcelValue.by_value
  attach_function 'capacity_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'capacity_total', [], ExcelValue.by_value
  attach_function 'capacity_total_low_carbon', [], ExcelValue.by_value
  attach_function 'cb2_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb2_scenario', [], ExcelValue.by_value
  attach_function 'cb2_traded_cap', [], ExcelValue.by_value
  attach_function 'cb3_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb3_scenario', [], ExcelValue.by_value
  attach_function 'cb3_traded_cap', [], ExcelValue.by_value
  attach_function 'cb4_current_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb4_current_scenario', [], ExcelValue.by_value
  attach_function 'cb4_current_traded_cap', [], ExcelValue.by_value
  attach_function 'cb4_revised_net_ets_purchase', [], ExcelValue.by_value
  attach_function 'cb4_revised_scenario', [], ExcelValue.by_value
  attach_function 'cb4_revised_traded_cap', [], ExcelValue.by_value
  attach_function 'emissions_electicity', [], ExcelValue.by_value
  attach_function 'emissions_factor', [], ExcelValue.by_value
  attach_function 'emissions_non_electricity_traded', [], ExcelValue.by_value
  attach_function 'emissions_total_traded', [], ExcelValue.by_value
  attach_function 'emissions_uk_share_of_eu_ets_cap_alternative', [], ExcelValue.by_value
  attach_function 'emissions_uk_share_of_eu_ets_cap_current', [], ExcelValue.by_value
  attach_function 'energy_output_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'energy_output_high_carbon', [], ExcelValue.by_value
  attach_function 'energy_output_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'energy_output_total_low_carbon', [], ExcelValue.by_value
  attach_function 'gw_per_twh', [], ExcelValue.by_value
  attach_function 'load_factor_average_low_carbon', [], ExcelValue.by_value
  attach_function 'load_factor_demand', [], ExcelValue.by_value
  attach_function 'load_factor_dispatchable_low_carbon', [], ExcelValue.by_value
  attach_function 'load_factor_high_carbon', [], ExcelValue.by_value
  attach_function 'load_factor_intermittent_low_carbon', [], ExcelValue.by_value
  attach_function 'maximum_industry_contraction', [], ExcelValue.by_value
  attach_function 'maximum_industry_expansion', [], ExcelValue.by_value
  attach_function 'mean_demand', [], ExcelValue.by_value
  attach_function 'minimum_build_rate', [], ExcelValue.by_value
  attach_function 'peak_demand', [], ExcelValue.by_value
  attach_function 'proportion_of_build_rate_to_2020_that_is_wind_rest_is_bio', [], ExcelValue.by_value
  attach_function 'proportion_of_second_build_that_is_wind', [], ExcelValue.by_value
  attach_function 'total_costs_capital', [], ExcelValue.by_value
  attach_function 'total_costs_carbon', [], ExcelValue.by_value
  attach_function 'total_costs_fuel', [], ExcelValue.by_value
  attach_function 'total_costs_operating', [], ExcelValue.by_value
  attach_function 'total_costs_total', [], ExcelValue.by_value
  attach_function 'total_system_cost', [], ExcelValue.by_value
  attach_function 'twh_per_gw', [], ExcelValue.by_value
  attach_function 'year_electricity_demand_starts_to_increase', [], ExcelValue.by_value
  attach_function 'year_second_wave_of_building_starts', [], ExcelValue.by_value
  attach_function 'set_n_2012_onwards_electricity_demand_growth_rate', [ExcelValue.by_value], :void
  attach_function 'set_n_2020_fossil_fuel_emissions_factor', [ExcelValue.by_value], :void
  attach_function 'set_n_2020_non_renewable_low_carbon_generation_i_e_nuclear_ccs', [ExcelValue.by_value], :void
  attach_function 'set_n_2030_cost_of_carbon', [ExcelValue.by_value], :void
  attach_function 'set_n_2030_cost_of_fossil_fuel', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_cost_of_carbon', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_cost_of_fossil_fuel', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_electricity_demand', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_fossil_fuel_emissions_factor', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_maximum_electricity_demand', [ExcelValue.by_value], :void
  attach_function 'set_n_2050_minimum_electricity_demand', [ExcelValue.by_value], :void
  attach_function 'set_annual_change_in_non_electricity_traded_emissions', [ExcelValue.by_value], :void
  attach_function 'set_annual_change_in_non_electricity_traded_emissions_after_radical_change', [ExcelValue.by_value], :void
  attach_function 'set_annual_reduction_in_cost_of_high_carbon_generation', [ExcelValue.by_value], :void
  attach_function 'set_annual_reduction_in_cost_of_intermittent_generation', [ExcelValue.by_value], :void
  attach_function 'set_annual_reduction_in_cost_of_other_low_carbon_generation', [ExcelValue.by_value], :void
  attach_function 'set_average_life_high_carbon', [ExcelValue.by_value], :void
  attach_function 'set_average_life_other_low_carbon', [ExcelValue.by_value], :void
  attach_function 'set_average_life_wind', [ExcelValue.by_value], :void
  attach_function 'set_build_rate_from_now_to_2020', [ExcelValue.by_value], :void
  attach_function 'set_build_rate_target_in_second_build', [ExcelValue.by_value], :void
  attach_function 'set_cb2_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_cb3_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_cb4_current_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_cb4_revised_traded_cap', [ExcelValue.by_value], :void
  attach_function 'set_maximum_industry_contraction', [ExcelValue.by_value], :void
  attach_function 'set_maximum_industry_expansion', [ExcelValue.by_value], :void
  attach_function 'set_minimum_build_rate', [ExcelValue.by_value], :void
  attach_function 'set_proportion_of_build_rate_to_2020_that_is_wind_rest_is_bio', [ExcelValue.by_value], :void
  attach_function 'set_proportion_of_second_build_that_is_wind', [ExcelValue.by_value], :void
  attach_function 'set_year_electricity_demand_starts_to_increase', [ExcelValue.by_value], :void
  attach_function 'set_year_second_wave_of_building_starts', [ExcelValue.by_value], :void
  # End of named references
end
